---
title: "tcga_tumor_norm_Anna"
author: "Anna von Bachmann"
date: '2022-05-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Load data
tcga_tumor_norm = readRDS("../data/tcga_tumor_normal_datascience_proj_2022.RDS")
```

```{r}
#extract expression data of KIRK cancer type, divided into tumor normal and annotation data, one data frame each
tcga_KIRC_tumor = data.matrix(tcga_tumor_norm[["KIRC"]][["tumor"]])
tcga_KIRC_norm = data.matrix(tcga_tumor_norm[["KIRC"]][["normal"]])
tcga_KIRC_annot = data.matrix(tcga_tumor_norm[["KIRC"]][["clinical"]])
```

```{r}

library(biomaRt)
library(dplyr)
##biotypes of the tcga_KIRC_tumor dataset
gene_identifier_tumor = strsplit(rownames(tcga_KIRC_tumor), split = "|", fixed = TRUE)

genes_ens_tumor<- sapply(gene_identifier_tumor, FUN = function(gene_identifier_tumor){
  ens = gene_identifier_tumor[1]
  return(ens)
})

genes_symbol_tumor<- sapply(gene_identifier_tumor, FUN = function(gene_identifier_tumor){
  ens = gene_identifier_tumor[2]
  return(ens)
})

genes_ens_vn_tumor <- strsplit(genes_ens_tumor, split = ".", fixed = TRUE)
genes_ensembl_tumor <- sapply(genes_ens_vn_tumor, FUN = function(genes_ens_vn_tumor){
  ens = genes_ens_vn_tumor[1]
  return(ens)
})

mart = useEnsembl(dataset = "hsapiens_gene_ensembl", biomart='ensembl')

list_biotype_tumor = getBM(attributes = c("ensembl_gene_id", "gene_biotype"), filters = "ensembl_gene_id", 
                                    values = genes_ensembl_tumor, mart = mart, useCache = FALSE)

#View(list_biotype_tumor)
#dim(list_biotype_tumor) = 19349 x 2 --> für manche gene kein biotype in der datenbank, Lösung überlegen?
#filter for protein coding genes in tcga_KIRC_tumor and norm
tcga_biotype_filter_tumor = as.matrix(list_biotype_tumor[which(list_biotype_tumor$gene_biotype=="protein_coding"),])
dim(tcga_biotype_filter_tumor) #19186
rownames(tcga_KIRC_tumor) = genes_ensembl_tumor
tcga_KIRC_tumor_protein_coding = tcga_KIRC_tumor[tcga_biotype_filter_tumor[,1],]
dim(tcga_KIRC_tumor_protein_coding)

rownames(tcga_KIRC_norm) = genes_ensembl_tumor
tcga_KIRC_norm_protein_coding = tcga_KIRC_norm[tcga_biotype_filter_tumor[,1],]
dim(tcga_KIRC_norm_protein_coding)


```                                      
```{r}
#filtering genes with constant expression (problematic for shapiro test (no normality of the data of constant values) and hence ttest (only usable for normal distributed data))
tcga_KIRC_norm_min = apply(tcga_KIRC_norm_protein_coding, 1, min)
tcga_KIRC_norm_max= apply(tcga_KIRC_norm_protein_coding, 1, max) #for normal cell data set
tcga_KIRC_tumor_min = apply(tcga_KIRC_tumor_protein_coding, 1, min)
tcga_KIRC_tumor_max= apply(tcga_KIRC_tumor_protein_coding, 1, max)#fpr tumor cell data set
#determine genes with constant expression
tcga_KIRC_norm_constant = c(names(which(tcga_KIRC_norm_min==tcga_KIRC_norm_max)))
length(tcga_KIRC_norm_constant)#for normal cell data set
tcga_KIRC_tumor_constant = c(names(which(tcga_KIRC_tumor_max==tcga_KIRC_tumor_min)))
length(tcga_KIRC_tumor_constant)#for normal cell data set
tcga_KIRC_both_constant = c(tcga_KIRC_norm_constant,tcga_KIRC_tumor_constant)
length(tcga_KIRC_both_constant)#combine constant expressed gene names from normal and tumor data set as these genes have to be removed from both data sets
#remove the constant expressed genes from both data sets (cl for clean)
tcga_KIRC_norm_cl = tcga_KIRC_norm_protein_coding[!rownames(tcga_KIRC_norm_protein_coding) %in% tcga_KIRC_both_constant,]
dim(tcga_KIRC_norm_cl)#18941 genes left
tcga_KIRC_tumor_cl = tcga_KIRC_tumor_protein_coding[!rownames(tcga_KIRC_tumor_protein_coding) %in% tcga_KIRC_both_constant,]
dim(tcga_KIRC_tumor_cl)

```


```{r}
#rename colnames of norm and tumor KIRC data frame
#ONLY RUN first line ONCE!!!!!!!!
tcga_KIRC_norm_colnames = c(substr(colnames(tcga_KIRC_norm),1, nchar(colnames(tcga_KIRC_norm))-3))
colnames(tcga_KIRC_norm_cl) = tcga_KIRC_norm_colnames #first tcga_KIRC_norm
colnames(tcga_KIRC_tumor_cl) = tcga_KIRC_norm_colnames #same for tcga_KIRC_tumor

```


```{r}#
#aim: calculate Foldchange(condition 1/condition 2)
#first: calculation of  mean values for each gene (gene = condition)
tcga_KIRC_norm_cl_Meanexpr = data.matrix(apply(tcga_KIRC_norm_cl, 1, mean))
colnames(tcga_KIRC_norm_cl_Meanexpr) = "Norm_Average_expr" #for  normal cell data
#same for tumor cell data
tcga_KIRC_tumor_cl_Meanexpr = data.matrix(apply(tcga_KIRC_tumor_cl,1,mean))
colnames(tcga_KIRC_tumor_cl_Meanexpr) = "Tumor_Average_expr" #for  normal cell data

#calculation of log2(foldchange = mean  cond 1/mean cond 2)
tcga_KIRC_cl_logFC = data.matrix(log2(tcga_KIRC_norm_cl_Meanexpr/tcga_KIRC_tumor_cl_Meanexpr))
colnames(tcga_KIRC_cl_logFC) = "KIRC_logfoldchange"
#PROBLEM : still some NaNs when mean (cond1) / mean(cond2) neagtive
```
```{r}
#transforming log back into absolute trasncripts to avoid getting NaNs because of negative mean1/mean2
tcga_KIRC_norm_cl_abs = as.matrix(2^tcga_KIRC_norm_cl)
tcga_KIRC_tumor_cl_abs = as.matrix(2^tcga_KIRC_tumor_cl)

#calculate Foldchange for absolute TPM (condition 1/condition 2)
#first: calculation of  mean values for each gene (gene = condition)
tcga_KIRC_norm_cl_abs_Meanexpr = data.matrix(apply(tcga_KIRC_norm_cl_abs, 1, mean))
colnames(tcga_KIRC_norm_cl_abs_Meanexpr) = "Norm_Average_expr" #for  normal cell data
#same for tumor cell data
tcga_KIRC_tumor_cl_abs_Meanexpr = data.matrix(apply(tcga_KIRC_tumor_cl_abs,1,mean))
colnames(tcga_KIRC_tumor_cl_abs_Meanexpr) = "Tumor_Average_expr" #for  tumor cell data

#calculation of log2(foldchange = mean  cond 1/mean cond 2)
tcga_KIRC_cl_abs_logFC = data.matrix(log2(tcga_KIRC_norm_cl_abs_Meanexpr/tcga_KIRC_tumor_cl_abs_Meanexpr))
colnames(tcga_KIRC_cl_abs_logFC) = "KIRC_logfoldchange"
```


```{r}
#check Normality of each gene by shapiro test
tcga_KIRC_norm_cl_shapiro = data.matrix(sapply ( 1:nrow(tcga_KIRC_norm_cl), function (x) {
  shapiro.test(tcga_KIRC_norm_cl[x,])
}$p.value)) #normal cell data
rownames(tcga_KIRC_norm_cl_shapiro)=rownames(tcga_KIRC_norm_cl)
colnames(tcga_KIRC_norm_cl_shapiro)="shapiro_pv"

tcga_KIRC_tumor_cl_shapiro = data.matrix(sapply ( 1:nrow(tcga_KIRC_tumor_cl), function (x) {
  shapiro.test(tcga_KIRC_tumor_cl[x,])
}$p.value)) # tumor cell data 
rownames(tcga_KIRC_tumor_cl_shapiro)=rownames(tcga_KIRC_tumor_cl)
colnames(tcga_KIRC_tumor_cl_shapiro)="shapiro_pv"

#how many genes are not normal distributed?--> reminder: if p-value>0.05, then not normal distributed
length(which(tcga_KIRC_norm_cl_shapiro>0.05))#10407 (of 18941)

#extract the gene names that are not normal distributed (=notnd)/normal distrtibuted
tcga_KIRC_norm_cl_notnd = as.matrix((tcga_KIRC_norm_cl_shapiro[(which(tcga_KIRC_norm_cl_shapiro>0.05)),]))
tcga_KIRC_norm_cl_nd= as.matrix((tcga_KIRC_norm_cl_shapiro[-(which(tcga_KIRC_norm_cl_shapiro>0.05)),]))
nrow(tcga_KIRC_norm_cl_shapiro)==nrow(tcga_KIRC_norm_cl_nd)+nrow(tcga_KIRC_norm_cl_notnd)#TRUE--> it worked
#same for tumor data

tcga_KIRC_tumor_cl_notnd = as.matrix((tcga_KIRC_tumor_cl_shapiro[(which(tcga_KIRC_tumor_cl_shapiro>0.05)),]))
tcga_KIRC_tumor_cl_nd= as.matrix((tcga_KIRC_tumor_cl_shapiro[-(which(tcga_KIRC_tumor_cl_shapiro>0.05)),]))
```
```{r}
#wilcoxon test if one of the data of gene expressionn is not normal distributed; if both are normal distributed--> ttest
#extract ´gene names that are not normal distributed in normal tissue and/or tumor tissue

tcga_KIRC_norm_cl_notnd_names = c(rownames(tcga_KIRC_norm_cl_notnd))#rownames of not normal distributed genes in normal tissue
tcga_KIRC_tumor_cl_notnd_names = c(rownames(tcga_KIRC_tumor_cl_notnd))# in tumor tissue
tcga_KIRC_cl_notnd_names = c(tcga_KIRC_norm_cl_notnd_names,tcga_KIRC_tumor_cl_notnd_names)#tumor and normal tissue
#extract gene expression data for genes that are nd in normal tissue
tcga_KIRC_norm_cl_nd = tcga_KIRC_norm_cl[!rownames(tcga_KIRC_norm_cl) %in% tcga_KIRC_cl_notnd_names,]
tcga_KIRC_norm_cl_notnd = tcga_KIRC_norm_cl[rownames(tcga_KIRC_norm_cl) %in% tcga_KIRC_cl_notnd_names,]#not nd data
nrow(tcga_KIRC_norm_cl_nd)+nrow(tcga_KIRC_norm_cl_notnd)==nrow(tcga_KIRC_norm_cl)
#worked

#for tumor tissue
tcga_KIRC_tumor_cl_nd = tcga_KIRC_tumor_cl[!rownames(tcga_KIRC_tumor_cl) %in% tcga_KIRC_cl_notnd_names,]
tcga_KIRC_tumor_cl_notnd = tcga_KIRC_tumor_cl[rownames(tcga_KIRC_tumor_cl) %in% tcga_KIRC_cl_notnd_names,]#not nd data
nrow(tcga_KIRC_tumor_cl_nd)+nrow(tcga_KIRC_tumor_cl_notnd)==nrow(tcga_KIRC_tumor_cl)
```


```{r}
#paired wilcoxon test for not nd expressed genes, to see if expression differs significant 
tcga_KIRC_cl_Expr_wilcox_pv  = data.matrix(sapply ( 1:nrow(tcga_KIRC_tumor_cl_notnd),function (x) {
  wilcox.test(tcga_KIRC_norm_cl_notnd[x,],tcga_KIRC_tumor_cl_notnd[x,],paired=TRUE)
}$p.value))
rownames(tcga_KIRC_cl_Expr_wilcox_pv)=rownames(tcga_KIRC_norm_cl_notnd)
colnames(tcga_KIRC_cl_Expr_wilcox_pv)="paired_tt_pvalue"
#Bonferroni-Korrektur
alpha=0.05/(nrow(tcga_KIRC_cl_Expr_wilcox_pv))
#how many genes are different expressed??
length(which(tcga_KIRC_cl_Expr_wilcox_pv<alpha)) 

```
```{r}
#paired t test for nd expressed genes, to see if expression differs significant 
tcga_KIRC_cl_Expr_tt_pv  = data.matrix(sapply ( 1:nrow(tcga_KIRC_tumor_cl_nd),function (x) {
  t.test(tcga_KIRC_norm_cl_nd[x,],tcga_KIRC_tumor_cl_nd[x,],paired=TRUE)
}$p.value))
rownames(tcga_KIRC_cl_Expr_tt_pv)=rownames(tcga_KIRC_norm_cl_nd)
colnames(tcga_KIRC_cl_Expr_tt_pv)="paired_tt_pvalue"
#Bonferroni-Korrektur
alpha=0.05/(nrow(tcga_KIRC_cl_Expr_tt_pv))
#how many genes are different expressed??
length(which(tcga_KIRC_cl_Expr_tt_pv<alpha)) 
```




