---
title: "tcga_norm_tumor_PCA_Anna"
author: "Anna von Bachmann"
date: '2022-05-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#working with tcga_norm_tumor
#cleaned version: 1. run whole skript tcga_tumor_norm_Volcano_Anna ; 2. work with KIRC_cl (see next chunk)
library(ggplot2)
#plotting
ggplot(tcga_KIRC_cl_pv_FC_sig, aes(KIRC_logfoldchange,neg_log10_pv))+
  geom_point( size =0.3)

```


```{r}
#work with this data frame!!!!

KIRC_cl = tcga_KIRC_tumor_protein_coding[rownames(tcga_KIRC_tumor_protein_coding) %in% rownames(tcga_KIRC_cl_pv_FC_sig),]
```

```{r}
KIRC_pca = prcomp(t(KIRC_cl))#, center = F, scale. = F???
length(KIRC_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs
```


```{r}
#kommt später nochmal mit funktion deswegen unnötig aber mal da gelassen
#plotting the variance that is explained by each PC
KIRC_pca_variance = (KIRC_pca$sdev)^2
KIRC_pca_prop.variance = KIRC_pca_variance/sum(KIRC_pca_variance) #calculating the proportion of variance taht is explained by PC ("In linear algebra, the rank of a matrix A is the dimension of the vector space generated (or spanned) by its columns. This corresponds to the maximal number of linearly independent columns of A")
names(KIRC_pca_prop.variance) = 1:length(KIRC_pca_prop.variance)
barplot(KIRC_pca_prop.variance[1:72],ylab='Proportion of variance', xlab = "Principal Components") # we only plot the first 20 PCs
```


```{r}
KIRC_pca_x = data.frame(KIRC_pca[["x"]])
#plot the data (patients) in the first principal components
KIRC_gender = ifelse(tcga_KIRC_annot$gender == "FEMALE", "red", "blue")
sum(tcga_KIRC_annot$gender=="FEMALE")

ggplot(KIRC_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

ggplot(KIRC_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

KIRC_tumorstatus = ifelse(tcga_KIRC_annot$tumor_status == "TUMOR FREE", "red", "blue") #tumor free or with tumor
sum(tcga_KIRC_annot$tumor_status=="TUMOR FREE")

ggplot(KIRC_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_tumorstatus)+
  ggtitle("PCA with regard to tumorstatus ")

ggplot(KIRC_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_tumorstatus)+
  ggtitle("PCA with regard to tumorstatus ")

KIRC_tumorstage = ifelse(tcga_KIRC_annot$ajcc_pathologic_tumor_stage == "Stage IV", "red", "blue") #cancer stage I-III or IV
sum(tcga_KIRC_annot$ajcc_pathologic_tumor_stage == "Stage IV")

ggplot(KIRC_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_tumorstage)+
  ggtitle("PCA with regard to tumorstage ")

ggplot(KIRC_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_tumorstage)+
  ggtitle("PCA with regard to tumorstage ")

mean(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis)#62.51 as mean--> visualization of age with cut off at age 63 
KIRC_age = ifelse(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis < 63, "red", "blue") #cancer stage I-III or IV
sum(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis < 63)

ggplot(KIRC_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_age)+
  ggtitle("PCA with regard to age at initial pathologic diagnosis ")


ggplot(KIRC_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_age)+
  ggtitle("PCA with regard to age at initial pathologic diagnosis ")
```
```{r}
#same as before but with package
#examine the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
library("factoextra")
KIRC_pca_eigval = get_eigenvalue(KIRC_pca)
rownames(KIRC_pca_eigval) = colnames (KIRC_pca_x)
barplot(KIRC_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")
```



```{r}
fviz_pca_var(KIRC_pca, col.var = "black")
fviz_contrib(KIRC_pca, choice = "var", axes = 1, top = 50)

KIRC_annot_matrix = data.matrix(tcga_KIRC_annot)
KIRC_annot_matrix_na = data.matrix(t(sapply(1:ncol(KIRC_annot_matrix), function(x){
  sum(is.na(KIRC_annot_matrix[,x]))
  })))
```


```{r}
#pca for annotations--> was a try but in the end pointless
KIRC_annot_matrix= KIRC_annot_matrix[,-which(KIRC_annot_matrix_na>0)]
KIRC_annot_pca = prcomp(KIRC_annot_matrix)

KIRC_annot_pca_x = data.frame(KIRC_annot_pca[["x"]])
library("factoextra")
KIRC_annot_pca_eigval = get_eigenvalue(KIRC_annot_pca)
rownames(KIRC_annot_pca_eigval) = colnames (KIRC_annot_pca_x)
barplot(KIRC_annot_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")


ggplot(KIRC_annot_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_gender)


fviz_contrib(KIRC_annot_pca, choice = "var", axes = 1, top = 10)

KIRC_annot_matrix1= KIRC_annot_matrix[,-13] # as days since birth shows the highest conrtribution to PCs but is also contained in age, we remove it
KIRC_annot_pca1 = prcomp(KIRC_annot_matrix1)
fviz_contrib(KIRC_annot_pca1, choice = "var", axes = 1, top = 10)
#TO DO: welche annotationen finde ich wichtig ? rausnehmen
```
