---
title: "tcga_norm_tumor_PCA_Anna"
author: "Anna von Bachmann"
date: '2022-05-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(factoextra)
library(stats)
```



```{r}
#Load data
tcga_tumor_norm = readRDS("data/tcga_tumor_normal_datascience_proj_2022.RDS")
tcga_KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]])

KIRC_tumor_cl = readRDS("data/tcga_KIRC_tumor_cl.rds")

KIRC_norm_cl = readRDS("data/tcga_KIRC_norm_cl.rds")

```

```{r}
KIRC_t_pca = prcomp(t(KIRC_tumor_cl))
length(KIRC_t_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs
```


```{r}
#get the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
KIRC_t_pca_eigval = get_eigenvalue(KIRC_t_pca)
rownames(KIRC_t_pca_eigval) = colnames (KIRC_t_pca_x)
barplot(KIRC_t_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")
```

```{r}
KIRC_t_pca_x = data.frame(KIRC_t_pca[["x"]])
#plot the data (patients) in the first principal components
KIRC_gender = ifelse(tcga_KIRC_annot$gender == "FEMALE", "red", "blue")
sum(tcga_KIRC_annot$gender=="FEMALE")

ggplot(KIRC_t_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

ggplot(KIRC_t_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

KIRC_tumorstatus = ifelse(tcga_KIRC_annot$tumor_status == "TUMOR FREE", "red", "blue") #tumor free or with tumor
sum(tcga_KIRC_annot$tumor_status=="TUMOR FREE")

ggplot(KIRC_t_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_tumorstatus)+
  ggtitle("PCA with regard to tumorstatus ")

ggplot(KIRC_t_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_tumorstatus)+
  ggtitle("PCA with regard to tumorstatus ")

KIRC_tumorstage = ifelse(tcga_KIRC_annot$ajcc_pathologic_tumor_stage == "Stage IV", "red", "blue") #cancer stage I-III or IV
sum(tcga_KIRC_annot$ajcc_pathologic_tumor_stage == "Stage IV")

ggplot(KIRC_t_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_tumorstage)+
  ggtitle("PCA with regard to tumorstage ")

ggplot(KIRC_t_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_tumorstage)+
  ggtitle("PCA with regard to tumorstage ")

mean(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis)#62.51 as mean--> visualization of age with cut off at age 63 
KIRC_age = ifelse(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis < 63, "red", "blue") #cancer stage I-III or IV
sum(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis < 63)

ggplot(KIRC_t_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_age)+
  ggtitle("PCA with regard to age at initial pathologic diagnosis ")


ggplot(KIRC_t_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_age)+
  ggtitle("PCA with regard to age at initial pathologic diagnosis ")
```




```{r}
fviz_pca_var(KIRC_t_pca, col.var = "black")
fviz_contrib(KIRC_t_pca, choice = "var", axes = 1, top = 50)

```

```{r}
#pca for combined data (pca for tumor and tissue data--> each patient represented twice as tumor and normal tissue --> is there a clustering for tumor and normal expression data???)
KIRC_tn_cl = cbind(KIRC_tumor_cl, KIRC_norm_cl)
KIRC_tn_cl_pca = prcomp(t(KIRC_tn_cl))

KIRC_tn_cl_pca_x= data.frame(KIRC_tn_cl_pca[["x"]])
#plot the data (patients) in the first principal components
KIRC_gender = ifelse(tcga_KIRC_annot$gender == "FEMALE", "red", "blue")
sum(tcga_KIRC_annot$gender=="FEMALE")

KIRC_tn_cl_pca_x_tumor = data.frame(KIRC_tn_cl_pca_x[1:72,])

ggplot(KIRC_tn_cl_pca_x, aes(PC1, PC2, color = "normal"))+
  geom_point( size =2)+
  geom_point(data=KIRC_tn_cl_pca_x_tumor, aes(PC1,PC2,color ="tumor"), size =2, color = "orange")+
  ggtitle("PCA regarding tumor and normal tissue data")+
  scale_color_manual(name="", breaks=c("tumor", "normal"),
                     values=c("tumor" = "orange", "normal" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))

ggplot(KIRC_tn_cl_pca_x, aes(PC1, PC3, color = "normal"))+
  geom_point( size =2)+
  geom_point(data=KIRC_tn_cl_pca_x_tumor, aes(PC1,PC3,color ="tumor"), size =2, color = "orange")+
  ggtitle("PCA regarding tumor and normal tissue data")+
  scale_color_manual(name="", breaks=c("tumor", "normal"),
                     values=c("tumor" = "orange", "normal" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))

KIRC_tn_cl_pca_eigval = get_eigenvalue(KIRC_tn_cl_pca)
rownames(KIRC_tn_cl_pca_eigval) = colnames (KIRC_tn_cl_pca_x)
barplot(KIRC_tn_cl_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")
```




```{r}
#pca for normal data only, as it seems like there are two clusters
KIRC_n_pca = prcomp(t(KIRC_norm_cl))

KIRC_n_pca_x = data.frame(KIRC_n_pca[["x"]])
#plot the data (patients) in the first principal components
KIRC_gender = ifelse(tcga_KIRC_annot$gender == "FEMALE", "red", "blue")
sum(tcga_KIRC_annot$gender=="FEMALE")

ggplot(KIRC_n_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

ggplot(KIRC_n_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

KIRC_tumorstatus = ifelse(tcga_KIRC_annot$tumor_status == "TUMOR FREE", "red", "blue") #tumor free or with tumor
sum(tcga_KIRC_annot$tumor_status=="TUMOR FREE")

ggplot(KIRC_n_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_tumorstatus)+
  ggtitle("PCA with regard to tumorstatus ")

ggplot(KIRC_n_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_tumorstatus)+
  ggtitle("PCA with regard to tumorstatus ")

KIRC_tumorstage = ifelse(tcga_KIRC_annot$ajcc_pathologic_tumor_stage == "Stage IV", "red", "blue") #cancer stage I-III or IV
sum(tcga_KIRC_annot$ajcc_pathologic_tumor_stage == "Stage IV")

ggplot(KIRC_n_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_tumorstage)+
  ggtitle("PCA with regard to tumorstage ")

ggplot(KIRC_n_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_tumorstage)+
  ggtitle("PCA with regard to tumorstage ")

mean(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis)#62.51 as mean--> visualization of age with cut off at age 63 
KIRC_age = ifelse(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis < 63, "red", "blue") #cancer stage I-III or IV
sum(tcga_KIRC_annot$age_at_initial_pathologic_diagnosis < 63)

ggplot(KIRC_n_pca_x, aes(PC1, PC2))+
  geom_point( size =2, color = KIRC_age)+
  ggtitle("PCA with regard to age at initial pathologic diagnosis ")


ggplot(KIRC_n_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_age)+
  ggtitle("PCA with regard to age at initial pathologic diagnosis ")
```



