---
title: "PCA_pan_cancer"
author: "Linda Blaier"
date: '2022-05-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load data = run Biotypes.Rmd 
```

```{r}
# work with tcga_exp_prc_clean -> w/o low variable under p50
dim (tcga_exp_prc_clean)
tcga_exp_pca = prcomp (t(tcga_exp_prc_clean), center = F, scale. = F)
pca_var = tcga_exp_pca$sdev^2
proportion_pca_var = pca_var/sum(pca_var)
names_prop_pca_var = 1:length(proportion_pca_var)
barplot(proportion_pca_var[1:20])
tcga_exp_pca$sdev
```

```{r}
#attempt to save data from environment
saveRDS(tcga_exp_prc_clean, file = "exp_prc_clean.Rds")
tcga_exp_prc_clean_copy = readRDS(file = "exp_prc_clean.Rds")
```

```{r}
# tcga_exp_pca2 = PCA(tcga_exp_prc_clean)

```

```{r}
library(Seurat)
PCA_exp = RunPCA(as.matrix(tcga_exp_prc_clean))
#create data frame with PCs and respective genes
PCA_exp_PCs = PCA_exp@cell.embeddings
#visualize PCs with respect to explained variance
PCA_exp_var = PCA_exp@stdev^2
PCA_exp_proportion_var = PCA_exp_var/sum(PCA_exp_var)
PC_exp = (PCA_exp_PCs[1:20])
PCs_20 = PCA_exp@cell.embeddings[1:20]

PCA_exp_scatter2 = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y = PC_2 )) +
  geom_point(color = "blue")
print(PCA_exp_scatter2) 

PCA_exp_scatter3 = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y = PC_3 )) +
  geom_point(color = "blue")
print(PCA_exp_scatter3) 

# plot scatter plot regarding gender
exp_gender = ifelse(tcga_annot$gender
                        == "FEMALE", "orange", "blue")
PCA_exp_gender = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y= PC_2)) + 
  geom_point(size = 2, color = exp_gender) + 
  ggtitle ("PCA regarding gender")
PCA_exp_gender
```
```{r}
library(tidyverse)
cancer_types = tcga_annot$cancer_type_abbreviation

UMAP_exp= uwot::umap(PCA_exp@cell.embeddings)
UMAP_plot = ggplot (data = as.data.frame(UMAP_exp), 
                    aes(x = V1, y= V2, color = cancer_types))+
  geom_point(size = 2)
UMAP_plot

```

