---
title: "Project 02 KIRC"
author: "Maja Glotz"
date: "5/1/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
```

# Topic 02: Cancer Hallmark and Metabolic Pathways in Cancer - KIRC

```{r read_data}
tcga_exp = readRDS("/Users/majaglotz/Uni/4. FS/Data Analysis/Datens채tze/tcga_tumor_log2TPM.RDS")
tcga_annot = readRDS("/Users/majaglotz/Uni/4. FS/Data Analysis/Datens채tze/tcga_tumor_annotation.RDS")
tcga_tumor_norm = readRDS("/Users/majaglotz/Uni/4. FS/Data Analysis/Datens채tze/tcga_tumor_normal_datascience_proj_2022.RDS")
genesets = readRDS("/Users/majaglotz/Uni/4. FS/Data Analysis/Datens채tze/hallmarks_genesets.RDS")
```

```{r}
dim(tcga_exp)
dim(tcga_annot)
```


```{r}
kirc = tcga_tumor_norm[["KIRC"]]
kirc.tumor = kirc[["tumor"]]
kirc.norm = kirc[["normal"]]
kirc.annot = kirc[["clinical"]]

dim(kirc.tumor)
dim(kirc.norm)
dim(kirc.annot)

```

```{r}
str(tcga_exp)
str(tcga_annot)
str(tcga_tumor_norm)
str(genesets)
```

