---
title: "PID_KEGG_cluster_Vgl_Anna"
author: "Anna von Bachmann"
date: '2022-06-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

#The same code as in the beginning of KIRC_KEGG_clustering!!!!
```{r Load data}
#Load data

tcga_tumor_norm = readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_tumor_normal_datascience_proj_2022.RDS")
KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]]) #annotation
KIRC_KEGG = readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity_KEGG.rds")

```

```{r KEGG PCA, UMAP}
#run pca 
KIRC_KEGG_pca = prcomp(t(KIRC_KEGG))#center = F, scale. = F???
length(KIRC_KEGG_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_KEGG_pca_x = data.frame(KIRC_KEGG_pca[["x"]])

#get the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
library("factoextra")
KIRC_KEGG_pca_eigval = get_eigenvalue(KIRC_KEGG_pca)
rownames(KIRC_KEGG_pca_eigval) = colnames (KIRC_KEGG_pca_x)
barplot(KIRC_KEGG_pca_eigval$variance.percent, main= "KEGG Pathways", ylab='Proportion of variance in percent', xlab = "Principal Components")

#UMAP for better clusterin/visualization, running on PCA result
library(uwot)
KIRC_KEGG_UMAP= uwot::umap(KIRC_KEGG_pca_x)
KIRC_KEGG_UMAP = data.frame(KIRC_KEGG_UMAP)
#plot
ggplot (data = KIRC_KEGG_UMAP, 
                    aes(x = X1, y = X2))+
  geom_point(size = 2)

#for KEGG pathways: optimal number of cluster: 3 
KEGG_km3 =kmeans(KIRC_KEGG_UMAP, 3 ,nstart = 200)
fviz_cluster(KEGG_km3, KIRC_KEGG_UMAP,
             palette = c("orange", "blue", "forestgreen"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

```

#The same code as in the beginning of KIRC_PID_clustering!!!!
```{r Load data}

#Load data
tcga_tumor_norm = readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_tumor_normal_datascience_proj_2022.RDS")
KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]]) #annotation



KIRC_PID_cl = readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_PID_cl.RDS")
KIRC_PID = KIRC_PID_cl
```

```{r PID PCA, UMAP}
#run pca 
KIRC_PID_pca = prcomp(t(KIRC_PID_cl))#center = F, scale. = F???
length(KIRC_PID_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_PID_pca_x = data.frame(KIRC_PID_pca[["x"]])


#UMAP for better clusterin/visualization, running on PCA result
library(uwot)
KIRC_PID_UMAP= uwot::umap(KIRC_PID_pca_x)
KIRC_PID_UMAP = data.frame(KIRC_PID_UMAP)
#plot
ggplot (data = KIRC_PID_UMAP, 
                    aes(x = X1, y = X2))+
  geom_point(size = 2)

PID_km2 =kmeans(KIRC_PID_UMAP, 2 ,nstart = 200)

```



#New code!!!

```{r Compare KEGG and PID clusters}
#vizualization of PID clusters in KIRC cluster plot
#data preparation
KEGG_UMAP_cluster = KIRC_KEGG_UMAP
KEGG_UMAP_cluster$KEGG_cluster = factor(KEGG_km3$cluster)
PID_UMAP_cluster = KIRC_PID_UMAP
PID_UMAP_cluster$PID_cluster = factor(PID_km2$cluster)

KEGG_UMAP_viz = KIRC_KEGG_UMAP #"viz" because df used for vizualization
KEGG_UMAP_viz$KEGG_cluster = factor(KEGG_km3$cluster)
KEGG_UMAP_viz$PID_cluster = factor(PID_km2$cluster)



ggscatter(
  KEGG_UMAP_viz, x = "X1", y = "X2", 
  color = "KEGG_cluster", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "PID_cluster", size = 1.5,  legend = "right", ggtheme = theme_bw(),
) +
  stat_mean(aes(color = KEGG_cluster), size = 4)
```

