---
title: "KIRC_Hallmarks_clustering"
author: "Anna von Bachmann"
date: '2022-06-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

##Identifying Clusters in KIRC based on Hallmark genesets 


```{r Load data}
#Load data

tcga_tumor_norm = readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_tumor_normal_datascience_proj_2022.RDS")
KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]]) #annotation
KIRC_HM = readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity_hallmark.rds")

```

```{r Load packages}
#packages
library(uwot)
library(cluster)
library(ggpubr)
library(factoextra)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(stats)
```

```{r PCA}
#run pca 
KIRC_HM_pca = prcomp(t(KIRC_HM))
length(KIRC_HM_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_HM_pca_x = data.frame(KIRC_HM_pca[["x"]])

#get the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
KIRC_HM_pca_eigval = get_eigenvalue(KIRC_HM_pca)
rownames(KIRC_HM_pca_eigval) = colnames (KIRC_HM_pca_x)
barplot(KIRC_HM_pca_eigval$variance.percent, main= "HM Pathways", ylab='Proportion of variance in percent', xlab = "Principal Components")
```


```{r  PCA plot}
#plot the data (patients in coordinate system with PC1, PC2/PC3 as axes)

ggplot(KIRC_HM_pca_x, aes(PC1, PC2))+  #plot PC1 and PC2
  geom_point( size =2)

ggplot(KIRC_HM_pca_x, aes(PC1, PC3))+   #plot in PC1  and PC3
  geom_point( size =2)
  

#plot the data (patients) in the first principal components regarding gender
KIRC_gender = ifelse(KIRC_annot$gender == "FEMALE", "red", "blue")#gender-vector
sum(KIRC_annot$gender=="FEMALE")

ggplot(KIRC_HM_pca_x, aes(PC1, PC2))+  #plot PC1 and pC2
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA for HM pw with regard to gender ")

ggplot(KIRC_HM_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA for HM pw with regard to gender ")
```

```{r  UMAP}
#UMAP for better clusterin/visualization, running on PCA result

KIRC_HM_UMAP= uwot::umap(KIRC_HM_pca_x)
KIRC_HM_UMAP = data.frame(KIRC_HM_UMAP)
#plot
ggplot (data = KIRC_HM_UMAP, 
                    aes(x = X1, y = X2))+
  geom_point(size = 2)

#plot with colors for gender

KIRC_tumorstatus = KIRC_annot$tumor_status
KIRC_gender_Umap = KIRC_annot$gender  #vector for coloring 
KIRC_HM_UMAP = data.frame(KIRC_HM_UMAP)

ggplot (data =KIRC_HM_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_tumorstatus))+
  geom_point(size = 1)

ggplot (data =KIRC_HM_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_gender_Umap))+
  geom_point(size = 1)
```


```{r KEGG Kmeans }
library(cluster)
#perform kmeans with 2:5 centers on UMAP results
KIRC_HM_kmeans = sapply(2:5, function(k){
  kmeans(x = KIRC_HM_UMAP , centers = k, nstart = 100 )})



#find the optimal number of clusters

#extract tot.withinss --> for silhouette plot (elbow method)
KIRC_HM_kmeans_tw = sapply(1:5, function(k){
  kmeans(x = KIRC_HM_UMAP , centers = k, nstart = 100 )$tot.withinss})

#elbow plot
plot(KIRC_HM_kmeans_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#extract cluster values for silhouette plot
KIRC_HM_kmeans_c = sapply(2:7, function(k){
  kmeans(x = KIRC_HM_UMAP , centers = k, nstart = 100 )$cluster})

#silhouette plot
sapply(1:6, function(x){
  plot(silhouette(KIRC_HM_kmeans_c[,x], dist(KIRC_HM_UMAP)), main ="Silhouette plot")})


#find the optimal number clusters, silhouette plot (average silhouette width)
fviz_nbclust(KIRC_HM_UMAP, kmeans, method='silhouette')
```

```{r  Kmeans Plot}
# visualize the clusters in plot
#for 2 centers
km.2 = kmeans(KIRC_HM_UMAP, centers = 2, nstart = 100)
fviz_cluster(km.2, KIRC_HM_UMAP,
             palette = c("orange", "blue"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 3 centers
km.3 = kmeans(KIRC_HM_UMAP, centers = 3, nstart = 100)
fviz_cluster(km.3, KIRC_HM_UMAP,
             palette = c("orange", "blue", "forestgreen"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 4 centers
km.4 = kmeans(KIRC_HM_UMAP, centers = 4, nstart = 100)
fviz_cluster(km.4, KIRC_HM_UMAP,
             palette = c("orange", "blue", "forestgreen", "black"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

```

```{r}
#for Hallmark pathways: optimal number ckusters = 2
HM_km2 =kmeans(KIRC_HM_UMAP, 2 ,nstart = 200)
HM_km = HM_km2$cluster
HM_c1_names = names(HM_km[which(HM_km == 1)]) #patient names of cluster1
HM_c2_names = names(HM_km[which(HM_km == 2)]) # patient names of cluster2
fviz_cluster(HM_km2, KIRC_HM_UMAP,
             palette = c("orange", "blue"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )


HM_c1 = KIRC_HM[,colnames(KIRC_HM) %in% HM_c1_names] # df with patients of cluster1
HM_c2 = KIRC_HM[,!colnames(KIRC_HM) %in% HM_c1_names] #df with patients cluster 2
HM_c1_mean = data.frame(apply(HM_c1, 1,mean)) #pw activity mean for patients of cluster 1
HM_c2_mean = data.frame (apply (HM_c2, 1, mean)) #fpr cluster 2
HM_c1_c2 = cbind(HM_c2_mean, HM_c1_mean) #combine mean cluster 1 and cluster2 
HM_c1_c2_dif = HM_c1_mean - HM_c2_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 1 

#rank the compared pw-matrix to see the most differently expressed pw
HM_c1_c2_dif_rank = data.frame(HM_c1_c2_dif$apply.HM_c1..1..mean.[order(HM_c1_c2_dif[,1],decreasing = TRUE)])
HM_rownames = c(rownames(HM_c1_c2_dif))
HM_rownames_rank = c(HM_rownames[order(HM_c1_c2_dif[,1],decreasing = TRUE)])

HM_c1_c2_dif_rank = as.data.frame(cbind(HM_rownames_rank, HM_c1_c2_dif_rank))
colnames(HM_c1_c2_dif_rank) = c("Pathway", "diff")

  
ggplot(HM_c1_c2_dif_rank, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()
 

HM_c1_c2_dif_rank %>%
  filter(HM_c1_c2_dif_rank$diff !=0) %>%
  ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
    geom_bar(stat="identity")+
    coord_flip()
  
 
HM_c1_c2_dif_rank%>%
  filter(abs(HM_c1_c2_dif_rank$dif)>0.20)%>%
  ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()

#!!! until now there was no testing for significance--> these pw are differentially expressed but we dont now yet if significant--> see below
```

```{r HM calculations (wilcoxon, FC)}
#working with FC and not with difference (minus)
HM_c1_c2_FC = data.matrix(HM_c1_mean/HM_c2_mean)
colnames(HM_c1_c2_FC) = "FC"
HM_c1_c2_FC[is.nan(HM_c1_c2_FC)]=0
#PROBLEM: what to do with INF??? (because of e.g. 0.1/0)


#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
HM_c1_m = as.matrix(HM_c1) #matrix needed for wilcoxon
HM_c2_m = as.matrix(HM_c2)
HM_wilcox_pv  = data.matrix(sapply ( 1:nrow(HM_c1_m),function (x) {
  wilcox.test(HM_c1_m[x,],HM_c2_m[x,],paired=FALSE)
}$p.value))
rownames(HM_wilcox_pv)=rownames(HM_c1)
colnames(HM_wilcox_pv)="pvalue"


#Bonferroni-Korrektur
alpha_HM=0.05/(nrow(HM_wilcox_pv))
#how many pathways have sign different NES??
length(which(HM_wilcox_pv<alpha_HM))


HM_wilcox_pv[is.nan(HM_wilcox_pv)] = 1
```

```{r Volcano Plot}
#data preparation for Volcano Plot

#problem with FC as there are a lot of Inf(if e.g. 0.1/0)--> what to do with those??
#thus not the FC value data is used but the difference (minus)
#calculate -log10 of p-value for plotting
HM_wilcox_pv_log =-log10(HM_wilcox_pv)
colnames(HM_wilcox_pv_log) = "neg_log10_pv"
HM_wilcox_pv_log [HM_wilcox_pv_log  == Inf] <- 0

#combine FC and pv matrix
HM_pv_dif =as.data.frame(cbind(HM_c1_c2_dif,HM_wilcox_pv_log))
colnames(HM_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv_HM = -log10(alpha_HM)#=3.593286, cut off later in plot 
HM_pv_dif_sig = HM_pv_dif[which(HM_pv_dif$neg_log10_pv>cutoffpv_HM),]
min(HM_pv_dif_sig$neg_log10_pv)
#upregulated genes of the sig diff expressed genes (blue in plot)
HM_pv_dif_sigup = HM_pv_dif_sig[which(HM_pv_dif_sig$diff>0),]

#plotting
ggplot(HM_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= HM_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = HM_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("differences in NES between two Hallmark clusters")+
  geom_text_repel(data =HM_pv_dif_sig, aes(diff, neg_log10_pv), label = row.names(HM_pv_dif_sig), size = 2, show.legend = FALSE)+
  xlab ("mean(c1)-mean(c2)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))


#which Pathways are sign different??
HM_dif_sig = data.frame(HM_pv_dif_sig$diff)
HM_dif_sig_names= c(rownames(HM_pv_dif_sig))
HM_dif_sig = cbind( HM_dif_sig_names, HM_dif_sig)
colnames(HM_dif_sig) = c("Pathway", "diff")

ggplot(HM_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("Hallmark pw with signif different NES in 2 KIRC clusters")+
  theme(plot.title = element_text(size=10))
  

```

```{r top ten diff pw }
#top ten pathways
abs_HM_dif_sig<- HM_dif_sig %>% 
  select_if(is.numeric) %>%
  abs()#absolute values

abs_HM_dif_sig = cbind(HM_dif_sig_names, abs_HM_dif_sig)
colnames( abs_HM_dif_sig) = c("Pathway", "abs.diff")#matrix with absolute difference in NES and pw names

abs_HM_dif_sig_rank = abs_HM_dif_sig[order(abs_HM_dif_sig$abs.diff, decreasing = T),] #ranked matrix

names_abs_HM_dif_sig_rank = c(abs_HM_dif_sig_rank[1:10,1])#names of top ten pw

top_HM_dif_sig = HM_dif_sig[which(HM_dif_sig[,1] %in% names_abs_HM_dif_sig_rank),]# df with top ten dif (significant) pw
  
ggplot(top_HM_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("top ten PA pw with signif different NES")+
  theme(plot.title = element_text(size=6))

```