---
title: "KIRC_PID_clustering"
author: "Anna von Bachmann"
date: '2022-06-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

```{r Packages}
library(uwot)
library(cluster)
library(ggpubr)
library(factoextra)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(reshape)
library(stringr)
library(dplyr)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(stats)


library(Seurat) #for final result not used
library(patchwork) #for final result not used
library(RColorBrewer) #for final result not used
```


#PID pathways

```{r Load data}

#Load data
tcga_tumor_norm = readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_tumor_normal_datascience_proj_2022.RDS")
KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]]) #annotation


KIRC_PID_cl = readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_PID_cl.RDS")
KIRC_PID = KIRC_PID_cl
```

```{r PCA}
#run pca 
KIRC_PID_pca = prcomp(t(KIRC_PID_cl))
length(KIRC_PID_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_PID_pca_x = data.frame(KIRC_PID_pca[["x"]])

#get the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
KIRC_PID_pca_eigval = get_eigenvalue(KIRC_PID_pca)
rownames(KIRC_PID_pca_eigval) = colnames (KIRC_PID_pca_x)
barplot(KIRC_PID_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")
```


```{r PCA plot}
#plot the data (patients in coordinate system with PC1, PC2/PC3 as axes)

ggplot(KIRC_PID_pca_x, aes(PC1, PC2))+  #plot PC1 and PC2
  geom_point( size =2)

ggplot(KIRC_PID_pca_x, aes(PC1, PC3))+   #plot in PC1  and PC3
  geom_point( size =2)
  

#plot the data (patients) in the first principal components regarding gender
KIRC_gender = ifelse(KIRC_annot$gender == "FEMALE", "red", "blue")#gender-vector
sum(KIRC_annot$gender=="FEMALE")

ggplot(KIRC_PID_pca_x, aes(PC1, PC2))+  #plot PC1 and pC2
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

ggplot(KIRC_PID_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")
```

```{r UMAP}
#UMAP for better clusterin/visualization, running on PCA result
KIRC_PID_UMAP= uwot::umap(KIRC_PID_pca_x)
KIRC_PID_UMAP = data.frame(KIRC_PID_UMAP)
#plot
ggplot (data = KIRC_PID_UMAP, 
                    aes(x = X1, y = X2))+
  geom_point(size = 2)

```


```{r Kmeans }
#perform kmeans with 2:5 centers on UMAP results
KIRC_PID_kmeans = sapply(2:5, function(k){
  kmeans(x = KIRC_PID_UMAP , centers = k, nstart = 100 )})



#find the optimal number of clusters

#extract tot.withinss --> for silhouette plot (elbow method)
KIRC_PID_kmeans_tw = sapply(1:5, function(k){
  kmeans(x = KIRC_PID_UMAP , centers = k, nstart = 100 )$tot.withinss})

#elbow plot
plot(KIRC_PID_kmeans_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#extract cluster values for silhouette plot
KIRC_PID_kmeans_c = sapply(2:7, function(k){
  kmeans(x = KIRC_PID_UMAP , centers = k, nstart = 100 )$cluster})

#silhouette plot
sapply(1:6, function(x){
  plot(silhouette(KIRC_PID_kmeans_c[,x], dist(KIRC_PID_UMAP)), main ="Silhouette plot")})


#find the optimal number clusters, silhouette plot (average silhouette width)
fviz_nbclust(KIRC_PID_UMAP, kmeans, method='silhouette')
```

```{r Kmeans Plot}
# visualize the clusters in plot
#for 2 centers
km.2 = kmeans(KIRC_PID_UMAP, centers = 2, nstart = 200)
fviz_cluster(km.2, KIRC_PID_UMAP,
             palette = c("orange", "blue"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw(),
             title = "PID clusters"
                         )

# for 3 centers
km.3 = kmeans(KIRC_PID_UMAP, centers = 3, nstart = 50)
fviz_cluster(km.3, KIRC_PID_UMAP,
             palette = c("orange", "blue", "forestgreen"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 4 centers
km.4 = kmeans(KIRC_PID_UMAP, centers = 4, nstart = 50)
fviz_cluster(km.4, KIRC_PID_UMAP,
             palette = c("orange", "blue", "forestgreen", "black"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

```


```{r}
#for PID pathways: optimal number ckusters = 2
PID_km2 =kmeans(KIRC_PID_UMAP, 2 ,nstart = 200)
PID_km = PID_km2$cluster
PID_c1_names = names(PID_km[which(PID_km == 1)]) #patient names of cluster1
PID_c2_names = names(PID_km[which(PID_km == 2)]) # patient names of cluster2
fviz_cluster(PID_km2, KIRC_PID_UMAP,
             palette = c("red", "blue"), 
             geom = "point",
             ellipse.type = "convex",
             xlab   = "UMAP1",
             ylab ="UMAP2",
             main = "PID clusters",
             ggtheme = theme_grey()
             )


PID_c1 = KIRC_PID[,colnames(KIRC_PID) %in% PID_c1_names] # df with patients of cluster1
PID_c2 = KIRC_PID[,!colnames(KIRC_PID) %in% PID_c1_names] #df with patients cluster 2
PID_c1_mean = data.frame(apply(PID_c1, 1,mean)) #pw activity mean for patients of cluster 1
PID_c2_mean = data.frame (apply (PID_c2, 1, mean)) #fpr cluster 2
PID_c1_c2 = cbind(PID_c2_mean, PID_c1_mean) #combine mean cluster 1 and cluster2 
PID_c1_c2_dif = PID_c1_mean - PID_c2_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 1 

#rank the compared pw-matrix to see the most differently expressed pw
PID_c1_c2_dif_rank = data.frame(PID_c1_c2_dif$apply.PID_c1..1..mean.[order(PID_c1_c2_dif[,1],decreasing = TRUE)])
PID_rownames = c(rownames(PID_c1_c2_dif))
PID_rownames_rank = c(PID_rownames[order(PID_c1_c2_dif[,1],decreasing = TRUE)])

PID_c1_c2_dif_rank = as.data.frame(cbind(PID_rownames_rank, PID_c1_c2_dif_rank))
colnames(PID_c1_c2_dif_rank) = c("Pathway", "diff")

  
ggplot(PID_c1_c2_dif_rank, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()


PID_c1_c2_dif_rank %>%
  filter(PID_c1_c2_dif_rank$diff !=0) %>%
  ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
    geom_bar(stat="identity")+
    coord_flip()
  

  
 
PID_c1_c2_dif_rank%>%
  filter(abs(PID_c1_c2_dif_rank$dif)>0.20)%>%
  ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()

#!!! until now there was no testing for significance--> these pw are differentially expressed but we dont now yet if significant--> see below
```


```{r calculations (wilcoxon, FC)}
#working with FC and not with difference (minus)
PID_c1_c2_FC = data.matrix(PID_c1_mean/PID_c2_mean)
colnames(PID_c1_c2_FC) = "FC"
PID_c1_c2_FC[is.nan(PID_c1_c2_FC)]=0
#PROBLEM: what to do with INF??? (because of e.g. 0.1/0)

#work with wilcoxon test as some of the pw have an enrichment score of zero for all patients, thus no normality, as shown below
PID_c1_min = apply(PID_c1, 1, min)
PID_c1_max = apply(PID_c1, 1, max) 
PID_c1_constant = c(names(which(PID_c1_min==PID_c1_max)))
length(PID_c1_constant) #there are 271 pw with constant NES, hence we use wilcoxon test 


#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
PID_c1_m = as.matrix(PID_c1) #matrix needed for wilcoxon
PID_c2_m = as.matrix(PID_c2)
PID_wilcox_pv  = data.matrix(sapply ( 1:nrow(PID_c1_m),function (x) {
  wilcox.test(PID_c1_m[x,],PID_c2_m[x,],paired=FALSE)
}$p.value))
rownames(PID_wilcox_pv)=rownames(PID_c1)
colnames(PID_wilcox_pv)="pvalue"

#Bonferroni-Korrektur
alpha_PID=0.05/(nrow(PID_wilcox_pv))
#how many pathways have sign different NES??
length(which(PID_wilcox_pv<alpha_PID))


PID_wilcox_pv[is.nan(PID_wilcox_pv)] = 1
```

```{r Volcano Plot}
#data preparation for Volcano Plot

PID_wilcox_pv_log =-log10(PID_wilcox_pv)
colnames(PID_wilcox_pv_log) = "neg_log10_pv"
PID_wilcox_pv_log [PID_wilcox_pv_log  == Inf] <- 0

#combine diff and pv matrix
PID_pv_dif =as.data.frame(cbind(PID_c1_c2_dif,PID_wilcox_pv_log))
colnames(PID_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv_PID = -log10(alpha_PID) 
PID_pv_dif_sig = PID_pv_dif[which(PID_pv_dif$neg_log10_pv>cutoffpv_PID),]
min(PID_pv_dif_sig$neg_log10_pv)
#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_pv_dif_sigup = PID_pv_dif_sig[which(PID_pv_dif_sig$diff>0),]

#volcano plot, there are no sign downregulated pw
#plotting
ggplot(PID_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= PID_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = PID_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("differences in NES between two PID clusters")+
  geom_text_repel(data = PID_pv_dif_sig, aes(diff, neg_log10_pv), label = row.names(PID_pv_dif_sig), size = 2, show.legend = FALSE)+
  xlab ("mean(c1)-mean(c2)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))


#which Pathways are sign different??
PID_dif_sig = data.frame(PID_pv_dif_sig$diff)
PID_dif_sig_names= c(rownames(PID_pv_dif_sig))
PID_dif_sig = cbind( PID_dif_sig_names, PID_dif_sig)
colnames(PID_dif_sig) = c("Pathway", "diff")

ggplot(PID_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PID pw with signif different NES in 2 KIRC clusters")+
  theme(plot.title = element_text(size=10))

```


```{r top ten diff pw }
#top ten pathways
abs_PID_dif_sig<- PID_dif_sig %>% 
  select_if(is.numeric) %>%
  abs()#absolute values

abs_PID_dif_sig = cbind(PID_dif_sig_names, abs_PID_dif_sig)
colnames( abs_PID_dif_sig) = c("Pathway", "abs.diff")#matrix with absolute difference in NES and pw names

abs_PID_dif_sig_rank = abs_PID_dif_sig[order(abs_PID_dif_sig$abs.diff, decreasing = T),] #ranked matrix

names_abs_PID_dif_sig_rank = c(abs_PID_dif_sig_rank[1:10,1])#names of top ten pw

top_PID_dif_sig = PID_dif_sig[which(PID_dif_sig[,1] %in% names_abs_PID_dif_sig_rank),]# df with top ten dif (significant) pw
  
ggplot(top_PID_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("top ten PID pw with signif different NES in cluster 1 vs 2")+
  theme(plot.title = element_text(size=6))

```



```{r}
#Are the pathways in both clusters upregulated compared to normal tissue and in one of the clusters even more? or are the pw in one cluster up and one downregulated compared to normal tissue?? -->whats the absolute NES in the top ten pw for both clusters?

PID_top_c1 = PID_c1[which(rownames(PID_c1) %in% names_abs_PID_dif_sig_rank),]
PID_top_c2 = PID_c2[which(rownames(PID_c2) %in% names_abs_PID_dif_sig_rank),]

PID_top_c1_mean = data.frame(apply(PID_top_c1, 1, mean))
PID_top_c2_mean = data.frame(apply(PID_top_c2, 1, mean))
colnames(PID_top_c1_mean) = "cluster 1"
colnames(PID_top_c2_mean) = "cluster 2"
PID_top_c1_c2_mean = as.matrix(cbind(PID_top_c1_mean, PID_top_c2_mean))


PID_top_c1_c2_mean_melted = (melt(PID_top_c1_c2_mean))
colnames(PID_top_c1_c2_mean_melted) = c("Pathway", "cluster", "NES")
ggplot(PID_top_c1_c2_mean_melted, aes( fill = Pathway, y=NES, x=cluster)) + 
    geom_bar(position="dodge", stat="identity")
```



```{r Seurat Plots}
KIRC_PCA_x1=data.frame(KIRC_PID_pca_x)
Seurat_PID = CreateSeuratObject(counts= KIRC_PID_cl)#create a Seurat object wiht the data, this object will be filled by the following commands (PCA;UMAP;clustering...)
VlnPlot(Seurat_PID, features = c("PID-TCR-PATHWAY"))

all.pathways = rownames(Seurat_PID)
Seurat_PID = ScaleData(Seurat_PID, features = all.pathways, verbose = FALSE)#scaling 
Seurat_PID = FindVariableFeatures(object = Seurat_PID)  #to run the PCA, otherwise Error
Seurat_PID = RunPCA(Seurat_PID, features = VariableFeatures(object = Seurat_PID), approx = FALSE, npcs = 71)

print(Seurat_PID[["pca"]], dims = 1:5, nfeatures = 5) #what influences the PCs?

DimPlot(Seurat_PID, reduction = "pca")#plot PCA
DimHeatmap(Seurat_PID, cells = 300, balance = TRUE) #heatmap for the influence on first PC

#clustering
Seurat_PID = FindNeighbors(Seurat_PID, dims =1:7)
Seurat_PID = FindClusters(Seurat_PID, n.start = 20, n.iter = 50, resolution = 0.3)


#rename the clusters
cluster.ids = c("cluster1", "cluster2", "cluster3")
names(cluster.ids) = levels(Seurat_PID) 
Seurat_PID = RenameIdents(Seurat_PID, cluster.ids)



Seurat_PID= RunUMAP(Seurat_PID, dims = 1:10) #UMAP
DimPlot(Seurat_PID, reduction = "umap", label = TRUE, pt.size = 0.5) #umap plot

cluster1.marker = FindMarkers(Seurat_PID, ident.1 = "cluster1", min.pct = 0.25)#find markers for cluster 1--> runs a wilcoxon between clusters to identify markers
VlnPlot(Seurat_PID, features = c(row.names(cluster1.marker)[1:nrow(cluster1.marker)]))#plot the markers


Seurat_PID_markers = FindAllMarkers(Seurat_PID, min.pct = 0.25) #find markers for all clusters

Seurat_PID_top_pw = Seurat_PID_markers %>% group_by(cluster) %>% top_n(n =5, wt =avg_log2FC) #top 10 pw that identify clusters (top 5 for each cluster)
FeaturePlot(Seurat_PID, features = Seurat_PID_top_pw$gene[1:10]) #umap with color for pw activity for top 10
FeaturePlot(Seurat_PID, features = "PID-CD8-TCR-DOWNSTREAM-PATHWAY")#umap with color for pw activity for one pathway

DoHeatmap(Seurat_PID, features = Seurat_PID_markers$gene)#heatmap clusterwise

```

```{r Heatmap}
#with complex Heatmap clustering --> problem: same Clusters as identified by kmeans??? --> thus manually coded (see below)
#get data matrix with only sign different pathways ranked by pvalue
PID_sig = KIRC_PID_cl[which(rownames(KIRC_PID_cl) %in% PID_dif_sig_names),]
PID_sig_rank = PID_pv_dif_sig[order(PID_pv_dif_sig$neg_log10_pv, decreasing = T),]
PID_sig_rank_names = c(rownames(PID_sig_rank))
PID_all_sig = cbind(rownames(PID_sig), PID_sig)
PID_all_sig_ordered = data.matrix(PID_sig[match(PID_sig_rank_names, PID_all_sig$`rownames(PID_sig)`),])




#pal <- colorRampPalette(brewer.pal(11, "RdYlBu"))
#Heatmap(PID_all_sig_ordered, name = "PID_all_sig_ordered", column_km = 2, cluster_rows = FALSE,  col = pal(50), column_names_gp = gpar(fontsize = 2),row_names_gp = gpar(fontsize = 10))

PIDClusterHeatmap = Heatmap(PID_all_sig_ordered, name = "PID_all_sig_ordered", column_km = 2, cluster_rows = FALSE, column_names_gp = gpar(fontsize = 7),row_names_gp = gpar(fontsize = 10), col = colorRamp2(c(-2, 0, 2.5), c("blue", "black", "red")), heatmap_legend_param = list(title= "NES"))

PIDClusterHeatmap


```


```{r Heatmap}
#Heatmap based on our own clusters from kmeans on umap (see above)

PID_sig_rank = PID_pv_dif_sig[order(PID_pv_dif_sig$neg_log10_pv, decreasing = T),]
PID_sig_rank_names = c(rownames(PID_sig_rank))

PID_c1_sig = PID_c1[which(rownames(PID_c1) %in% PID_dif_sig_names),]
PID_c1_sig = cbind(rownames(PID_c1_sig), PID_c1_sig)

PID_c1_sig_ordered = data.matrix(PID_c1_sig[match(PID_sig_rank_names, PID_c1_sig$`rownames(PID_c1_sig)`),])
PID_c1_sig_ordered =PID_c1_sig_ordered[,-1]#only run once!!

PID_c2_sig = PID_c2[which(rownames(PID_c2) %in% PID_dif_sig_names),]
PID_c2_sig = cbind(rownames(PID_c2_sig), PID_c2_sig)

PID_c2_sig_ordered = data.matrix(PID_c2_sig[match(PID_sig_rank_names, PID_c2_sig$`rownames(PID_c2_sig)`),])
PID_c2_sig_ordered =PID_c2_sig_ordered[,-1]#only run once!!

common1_min = min(c(PID_c1_sig_ordered,PID_c2_sig_ordered))
common1_max = max(c(PID_c1_sig_ordered,PID_c2_sig_ordered))
col_fun1 = circlize::colorRamp2(c(common1_min,0, common1_max), c("blue","black", "red"))


PID_Heatmap=Heatmap(PID_c1_sig_ordered, column_title = "Upregulated", column_title_gp = gpar(fontsize = 16,fontface="bold"),col = col_fun1,cluster_rows = FALSE, cluster_columns =  F,column_names_gp = gpar(fontsize = 6),row_names_gp = gpar(fontsize = 11),heatmap_legend_param = list(title = "NES",title_gp = gpar(fontsize = 7),labels_gp = gpar(fontsize = 7)),width=15*unit(5,"mm"))+
  Heatmap(PID_c2_sig_ordered, column_title = "Neutral", column_title_gp = gpar(fontsize = 16,fontface="bold"),col = col_fun1,cluster_rows = FALSE, cluster_columns =  F,column_names_gp = gpar(fontsize = 6),row_names_gp = gpar(fontsize = 11),show_heatmap_legend = FALSE,width=15*unit(5,"mm")) 

draw(PID_Heatmap,heatmap_legend_side="left")
```



```{r annotation UMAPs}
#UMAP plot with colors form annotation matrix or pw activity (gender, tumorstatus,...)
KIRC_PID_UMAP = data.frame(KIRC_PID_UMAP)

KIRC_tumorstatus = KIRC_annot$tumor_status

#convert "" to "NA"
KIRC_tumorstatus_updated= c()
for (i in 1:length(KIRC_tumorstatus)){
  if (KIRC_tumorstatus[i] == "") {KIRC_tumorstatus_updated[i]= "NA"}
  else {KIRC_tumorstatus_updated[i]=KIRC_tumorstatus[i]}
}
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_tumorstatus_updated))+
  scale_color_manual(values = c("WITH TUMOR" = "red",
                                "TUMOR FREE"="blue",
                                "NA" = "purple"))+
  labs(x = "UMAP1", y = "UMAP2", col = "Tumor stage", title = "PID pathways" )+
  geom_point(size = 1.3)


#correlation of tumor stage and PID cluster ???

KIRC_tumorfree = c(KIRC_annot$PATIENT[which(KIRC_annot$tumor_status== "TUMOR FREE")])
PID_c1_names_rmv = str_sub(PID_c1_names,1,nchar(PID_c1_names)-3)
PID_c1_tumorfree = (intersect(PID_c1_names_rmv, KIRC_tumorfree ))
length(PID_c1_tumorfree)/length(PID_c1) #=0.7

PID_c2_names_rmv = str_sub(PID_c2_names,1,nchar(PID_c2_names)-3)
PID_c2_tumorfree = (intersect(PID_c2_names_rmv, KIRC_tumorfree ))
length(PID_c2_tumorfree)/length(PID_c2) #=0.28125


KIRC_gender_Umap = KIRC_annot$gender  
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_gender_Umap))
  geom_point(size = 1)

#OS	Overall Survival, 0 = alive, 1 = death from any cause, 
#(Time (not visualized): overall survival time in days, last_contact_days_to or death_days_to, whichever is larger.)
KIRC_OS = KIRC_annot$OS
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_OS))+
  geom_point(size = 1)

#DSS   Disease-Specific Survival (Approximate for most tumor types, not 100% accurate definition), 0 = alive, 1 =  patient whose vital_status was Dead and tumor_status was WITH TUMOR or If patient died from the disease shown in field of cause_of_death., 
#(Time (not visualized): disease-specific survival time in days, last_contact_days_to or death_days_to, whichever is larger.)

KIRC_DSS = KIRC_annot$DSS
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_DSS))+
  geom_point(size = 1)

KIRC_tumorstage = KIRC_annot$ajcc_pathologic_tumor_stage
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_tumorstage))+
  geom_point(size = 1)


#PFI	Progression-Free Interval (Relatively accurate, PFI is preferred over OS due to relatively short follow-up time), 0 = censored otherwise, 1 = patient having new tumor event whether it was a progression of disease, local recurrence, distant metastasis, new primary tumors all sites , or died with the cancer without new tumor event, including cases with a new tumor event whose type is N/A. 
#Time: progression-free interval time in days, for events, either new_tumor_event_dx_days_to or death_days_to,  whichever is applicable; or for censored cases, either last_contact_days_to or death_days_to, whichever is applicable.

KIRC_PFI_time = KIRC_annot$PFI_time
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_PFI_time))+
  geom_point(size = 1)

KIRC_PFI = KIRC_annot$PFI
ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_PFI))+
  geom_point(size = 1)


#NES visualized on UMAP
KIRC_PID_t = data.frame(t(KIRC_PID_cl))


KIRC_CD8_TCR = KIRC_PID_t$PID_CD8_TCR_PATHWAY
p1=ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_CD8_TCR))+
 geom_point(size = 0.5)+
  scale_color_gradient(low="blue", high="red", limits=c(0,2.5))+
  labs(x = "UMAP1", y = "UMAP2", col = "NES ", title = "PID_CD8_TCR_PATHWAY")+
  theme(plot.title = element_text(size=10))


KIRC_TCR_PATHWAY= KIRC_PID_t$PID_TCR_PATHWAY
p2=ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_TCR_PATHWAY))+
  geom_point(size = 0.5)+
  scale_color_gradient(low="blue", high="red", limits=c(0,2.5))+
  labs(x = "UMAP1", y = "UMAP2", col = "NES",title= "PID_TCR_PATHWAY ")+
   theme(plot.title = element_text(size=10))


PID_CD8_TCR =  KIRC_PID_t$PID_CD8_TCR_DOWNSTREAM_PATHWAY
p3=ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = PID_CD8_TCR))+
  geom_point(size = 0.5)+
  scale_color_gradient(low="blue", high="red", limits=c(0,2.5))+
  labs(x = "UMAP1", y = "UMAP2", col = "NES", title = "PID_CD8_TCR_DOWNSTREAM_PATHWAY")+
   theme(plot.title = element_text(size=10))

PID_IL1 =  KIRC_PID_t$PID_IL1_PATHWAY
p4=ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = PID_IL1))+
   geom_point(size = 0.5)+
  scale_color_gradient(low="blue", high="red", limits=c(0,2.5))+
  labs(x = "UMAP1", y = "UMAP2", col = "NES", title = "PID_IL1_PATHWAY")+
   theme(plot.title = element_text(size=10))

PID_CXCR4 =  KIRC_PID_t$PID_CXCR4_PATHWAY
p5 = ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = PID_CXCR4 ))+
  geom_point(size = 0.5)+
  scale_color_gradient(low="blue", high="red", limits=c(0,2.5))+
  labs(x = "UMAP1", y = "UMAP2", col = "NES", title =  "PID_CXCR4_PATHWAY")+
   theme(plot.title = element_text(size=10))

PID_IL27 =  KIRC_PID_t$PID_IL27_PATHWAY
p6 = ggplot (data =KIRC_PID_UMAP, 
                    aes(x = X1, y = X2 , color = PID_IL27))+
  geom_point(size = 0.5)+
  scale_color_gradient(low="blue", high="red", limits=c(0,2.5))+
  labs(x = "UMAP1", y = "UMAP2", col = "NES", title =  "PID_IL27_PATHWAY")+
   theme(plot.title = element_text(size=10))

plotliste = list(p1,p2,p3,p4,p5,p6)

ggarrange(plotlist = plotliste)

```








