---
title: "KIRC_Pathway_activity_PCA_Anna"
author: "Anna von Bachmann"
date: '2022-06-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Load data}
#Load data
tcga_tumor_norm = readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_tumor_normal_datascience_proj_2022.RDS")
KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]]) #annotation

KIRC_pa =  readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity.rds") #PA for Pathway activity (all data)

```

# for all datasets combined (KIRC_pa)

```{r PCA}
#run pca 
KIRC_pa_pca = prcomp(t(KIRC_pa))#center = F, scale. = F???
length(KIRC_pa_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_pa_pca_x = data.frame(KIRC_pa_pca[["x"]])

#get the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
library("factoextra")
KIRC_pa_pca_eigval = get_eigenvalue(KIRC_pa_pca)
rownames(KIRC_pa_pca_eigval) = colnames (KIRC_pa_pca_x)
barplot(KIRC_pa_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")
```


```{r PCA plot}
#plot the data (patients in coordinate system with PC1, PC2/PC3 as axes)

ggplot(KIRC_pa_pca_x, aes(PC1, PC2))+  #plot PC1 and PC2
  geom_point( size =2)

ggplot(KIRC_pa_pca_x, aes(PC1, PC3))+   #plot in PC1  and PC3
  geom_point( size =2)
  

#plot the data (patients) in the first principal components regarding gender
KIRC_gender = ifelse(KIRC_annot$gender == "FEMALE", "red", "blue")#gender-vector
sum(KIRC_annot$gender=="FEMALE")

ggplot(KIRC_pa_pca_x, aes(PC1, PC2))+  #plot PC1 and pC2
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

ggplot(KIRC_pa_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")
```
```{r UMAP}
#UMAP for better clusterin/visualization, running on PCA result
library(uwot)
KIRC_pa_UMAP= uwot::umap(KIRC_pa_pca_x)
KIRC_pa_UMAP = data.frame(KIRC_pa_UMAP)
#plot
ggplot (data = KIRC_pa_UMAP, 
                    aes(x = X1, y = X2))+
  geom_point(size = 2)

#plot with colors for gender

KIRC_tumorstatus = KIRC_annot$tumor_status
KIRC_gender_Umap = KIRC_annot$gender  #vector for coloring 
KIRC_pa_UMAP = data.frame(KIRC_pa_UMAP)

ggplot (data =KIRC_pa_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_tumorstatus))+
  geom_point(size = 1)

ggplot (data =KIRC_pa_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_gender_Umap))+
  geom_point(size = 1)
```


```{r Kmeans }
library(cluster)
#perform kmeans with 2:5 centers on UMAP results
KIRC_UMAP_kmeans = sapply(2:5, function(k){
  kmeans(x = KIRC_pa_UMAP , centers = k, nstart = 50 )})



#find the optimal number of clusters

#extract tot.withinss --> for silhouette plot (elbow method)
KIRC_UMAP_kmeans_tw = sapply(1:5, function(k){
  kmeans(x = KIRC_pa_UMAP , centers = k, nstart = 50 )$tot.withinss})

#elbow plot
plot(KIRC_UMAP_kmeans_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#extract cluster values for silhouette plot
KIRC_UMAP_kmeans_c = sapply(2:7, function(k){
  kmeans(x = KIRC_pa_UMAP , centers = k, nstart = 50 )$cluster})

#silhouette plot
sapply(1:6, function(x){
  plot(silhouette(KIRC_UMAP_kmeans_c[,x], dist(KIRC_pa_UMAP)), main ="Silhouette plot")})


#find the optimal number clusters, silhouette plot (average silhouette width)
fviz_nbclust(KIRC_pa_UMAP, kmeans, method='silhouette')
```
```{r Kmeans Plot}
# visualize the clusters in plot
library(ggpubr)
library(factoextra)
#for 2 centers
km.2 = kmeans(KIRC_pa_UMAP, centers = 2, nstart = 200)
fviz_cluster(km.2, KIRC_pa_UMAP,
             palette = c("orange", "blue"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 3 centers
km.3 = kmeans(KIRC_pa_UMAP, centers = 3, nstart = 50)
fviz_cluster(km.3, KIRC_pa_UMAP,
             palette = c("orange", "blue", "forestgreen"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 4 centers
km.4 = kmeans(KIRC_pa_UMAP, centers = 4, nstart = 50)
fviz_cluster(km.4, KIRC_pa_UMAP,
             palette = c("orange", "blue", "forestgreen", "black"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

```



```{r KEGG culsters}
#for all pathways: optimal number of cluster: 3 
PA_km3 =kmeans(KIRC_pa_UMAP, 3 ,nstart = 50)
fviz_cluster(PA_km3, KIRC_pa_UMAP,
             palette = c("orange", "blue", "forestgreen"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
PA_km = PA_km3$cluster

#assign the patients to corresponding cluster
PA_c1_names = names(PA_km[which(PA_km == 1)]) #patient names of cluster1 #22 patients
PA_c2_names = names(PA_km[which(PA_km == 2)])#23 patients
PA_c3_names = names(PA_km[which(PA_km == 3)])#27 patients

PA_c1 = KIRC_pa[,colnames(KIRC_pa) %in% PA_c1_names] # df with patients of cluster1
PA_c2 = KIRC_pa[,colnames(KIRC_pa) %in% PA_c2_names]
PA_c3 = KIRC_pa[,colnames(KIRC_pa) %in% PA_c3_names]
```

##Cluster 1 vs 2+3

```{r Cluster 1 vs cluster 2+3}
#first: compare cluster 1 to cluster(2+3)
PA_c23 = cbind(PA_c2,PA_c3)

PA_c1_mean = data.frame(apply(PA_c1, 1,mean)) #pw activity mean for patients of cluster 1
PA_c23_mean = data.frame (apply (PA_c23, 1, mean))

PA_c1_c23_dif = PA_c1_mean - PA_c23_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 1 

#rank the compared pw-matrix to see the most differently expressed pw
PA_c1_c23_dif_rank = data.frame(PA_c1_c23_dif$apply.PA_c1..1..mean.[order(PA_c1_c23_dif[,1],decreasing = TRUE)])
PA_rownames = c(rownames(PA_c1_c23_dif))
PA_rownames_rank = c(PA_rownames[order(PA_c1_c23_dif[,1],decreasing = TRUE)])

PA_c1_c23_dif_rank = as.data.frame(cbind(PA_rownames_rank, PA_c1_c23_dif_rank))
colnames(PA_c1_c23_dif_rank) = c("Pathway", "diff")

```

```{r Wilcoxon Cluster 1 vs 2+3}

#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
PA_c1_m = as.matrix(PA_c1) #matrix needed for wilcoxon
PA_c23_m = as.matrix(PA_c23)
#clsuer 1 compared to the other clusters --> named as KEGG_1_...
PA_1_wilcox_pv  = data.matrix(sapply ( 1:nrow(PA_c1_m),function (x) {
  wilcox.test(PA_c1_m[x,],PA_c23_m[x,],paired=FALSE)
}$p.value))
rownames(PA_1_wilcox_pv)=rownames(PA_c1)
colnames(PA_1_wilcox_pv)="pvalue"
#a lot of NaNs--> Maybe because of constant NES??

#Bonferroni-Korrektur
alpha_PA=0.05/(nrow(PA_1_wilcox_pv))#0.0001157407
#how many pathways have sign different NES??
length(which(PA_1_wilcox_pv<alpha_PA))


PA_1_wilcox_pv[is.nan(PA_1_wilcox_pv)] = 1
```


```{r Volcano Cluster 1 vs 2+3}
#data preparation for Volcano Plot

#problem with FC as there are a lot of Inf(if e.g. 0.1/0)--> what to do with those??
#NaNs in FC could be converted to zero ??
#hence not the FC value data is used but the difference (minus)

#calculate -log10 of p-value for plotting
PA_1_wilcox_pv_log =-log10(PA_1_wilcox_pv)
colnames(PA_1_wilcox_pv_log) = "neg_log10_pv"

#combine differnece and pv matrix
PA_1_pv_dif =as.data.frame(cbind(PA_c1_c23_dif,PA_1_wilcox_pv_log))
colnames(PA_1_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv_PA = -log10(alpha_PA) 
PA_1_pv_dif_sig = PA_1_pv_dif[which(PA_1_pv_dif$neg_log10_pv>cutoffpv_PA),]
min(PA_1_pv_dif_sig$neg_log10_pv)
#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PA_1_pv_dif_sigup = PA_1_pv_dif_sig[which(PA_1_pv_dif_sig$diff>0),]

#volcano plot, there are no sign downregulated pw
library(ggplot2)
library(ggrepel)
#plotting
ggplot(PA_1_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= PA_1_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = PA_1_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("differences in NES between PA custer 1 compared to cluster (2+3) ")+
  geom_text_repel(data = PA_1_pv_dif_sig, aes(diff, neg_log10_pv), label = row.names(PA_1_pv_dif_sig), size = 2, show.legend = FALSE)+
  xlab ("mean(c1)-mean(c2,c3)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))


#which Pathways are sign different??
PA_1_dif_sig = data.frame(PA_1_pv_dif_sig$diff)
PA_1_dif_sig_names= c(rownames(PA_1_pv_dif_sig))
PA_1_dif_sig = cbind(PA_1_dif_sig_names, PA_1_dif_sig)
colnames( PA_1_dif_sig) = c("Pathway", "diff")

ggplot(PA_1_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PA pw with signif different NES in cluster 1")+
  theme(plot.title = element_text(size=10))
```


```{r top ten diff pw Cluster 1 vs 2+3}
#top ten pathways
library(dplyr)
abs_PA_1_dif_sig<- PA_1_dif_sig %>% 
  select_if(is.numeric) %>%
  abs()#absolute values

abs_PA_1_dif_sig = cbind(PA_1_dif_sig_names, abs_PA_1_dif_sig)
colnames( abs_PA_1_dif_sig) = c("Pathway", "abs.diff")#matrix with absolute difference in NES and pw names

abs_PA_1_dif_sig_rank = abs_PA_1_dif_sig[order(abs_PA_1_dif_sig$abs.diff, decreasing = T),] #ranked matrix

names_abs_PA_1_dif_sig_rank = c(abs_PA_1_dif_sig_rank[1:10,1])#names of top ten pw

top_PA_1_dif_sig = PA_1_dif_sig[which(PA_1_dif_sig[,1] %in% names_abs_PA_1_dif_sig_rank),]# df with top ten dif (significant) pw
  
ggplot(top_PA_1_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("top ten PA pw with signif different NES in cluster 1")+
  theme(plot.title = element_text(size=6))

```

##Cluster 2 vs 1+3

```{r Cluster 2 vs cluster 1+3}
#first: compare cluster 2 to cluster(1+3)
PA_c13 = cbind(PA_c1,PA_c3)

PA_c2_mean = data.frame(apply(PA_c2, 1,mean)) #pw activity mean for patients of cluster 2
PA_c13_mean = data.frame (apply (PA_c13, 1, mean))

PA_c2_c13_dif = PA_c2_mean - PA_c13_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 2

#rank the compared pw-matrix to see the most differently expressed pw
PA_c2_c13_dif_rank = data.frame(PA_c2_c13_dif$apply.PA_c2..1..mean.[order(PA_c2_c13_dif[,1],decreasing = TRUE)])
PA_2_rownames = c(rownames(PA_c2_c13_dif))
PA_2_rownames_rank = c(PA_2_rownames[order(PA_c2_c13_dif[,1],decreasing = TRUE)])

PA_c2_c13_dif_rank = as.data.frame(cbind(PA_2_rownames_rank, PA_c2_c13_dif_rank))
colnames(PA_c2_c13_dif_rank) = c("Pathway", "diff")

```

```{r Wilcoxon Cluster 1 vs 2+3}

#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
PA_c2_m = as.matrix(PA_c2) #matrix needed for wilcoxon
PA_c13_m = as.matrix(PA_c13)
#clsuer 2 compared to the other clusters --> named as KEGG_2_...
PA_2_wilcox_pv  = data.matrix(sapply ( 1:nrow(PA_c2_m),function (x) {
  wilcox.test(PA_c2_m[x,],PA_c13_m[x,],paired=FALSE)
}$p.value))
rownames(PA_2_wilcox_pv)=rownames(PA_c2)
colnames(PA_2_wilcox_pv)="pvalue"
#a lot of NaNs--> Maybe because of constant NES??

#Bonferroni-Korrektur
alpha_PA=0.05/(nrow(PA_2_wilcox_pv))#0.0001157407
#how many pathways have sign different NES??
length(which(PA_2_wilcox_pv<alpha_PA))#66


PA_2_wilcox_pv[is.nan(PA_2_wilcox_pv)] = 1
```


```{r Volcano Cluster 2 vs 1+3}
#data preparation for Volcano Plot

#problem with FC as there are a lot of Inf(if e.g. 0.1/0)--> what to do with those??
#NaNs in FC could be converted to zero ??
#hence not the FC value data is used but the difference (minus)

#calculate -log10 of p-value for plotting
PA_2_wilcox_pv_log =-log10(PA_2_wilcox_pv)
colnames(PA_2_wilcox_pv_log) = "neg_log10_pv"

#combine differnece and pv matrix
PA_2_pv_dif =as.data.frame(cbind(PA_c2_c13_dif,PA_2_wilcox_pv_log))
colnames(PA_2_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv_PA = -log10(alpha_PA)#=3.593286, cut off later in plot 
PA_2_pv_dif_sig = PA_2_pv_dif[which(PA_2_pv_dif$neg_log10_pv>cutoffpv_PA),]
min(PA_2_pv_dif_sig$neg_log10_pv)
#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PA_2_pv_dif_sigup = PA_2_pv_dif_sig[which(PA_2_pv_dif_sig$diff>0),]

#volcano plot, there are no sign downregulated pw
library(ggplot2)
library(ggrepel)
#plotting
ggplot(PA_2_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= PA_2_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = PA_2_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("differences in NES between PA custer 2 compared to cluster (1+3) ")+
  geom_text_repel(data = PA_2_pv_dif_sig, aes(diff, neg_log10_pv), label = row.names(PA_2_pv_dif_sig), size = 2, show.legend = FALSE)+
  xlab ("mean(c2)-mean(c1,c3)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))

#which Pathways are sign different??
PA_2_dif_sig = data.frame(PA_2_pv_dif_sig$diff)
PA_2_dif_sig_names= c(rownames(PA_2_pv_dif_sig))
PA_2_dif_sig = cbind( PA_2_dif_sig_names, PA_2_dif_sig)
colnames(PA_2_dif_sig) = c("Pathway", "diff")

ggplot(PA_2_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PA pw with signif different NES in cluster 2")+
  theme(plot.title = element_text(size=10))
```
```{r top ten diff pw Cluster 2 vs 1+3}
#top ten pathways
library(dplyr)
abs_PA_2_dif_sig<- PA_2_dif_sig %>% 
  select_if(is.numeric) %>%
  abs()#absolute values

abs_PA_2_dif_sig = cbind(PA_2_dif_sig_names, abs_PA_2_dif_sig)
colnames( abs_PA_2_dif_sig) = c("Pathway", "abs.diff")#matrix with absolute difference in NES and pw names

abs_PA_2_dif_sig_rank = abs_PA_2_dif_sig[order(abs_PA_2_dif_sig$abs.diff, decreasing = T),] #ranked matrix

names_abs_PA_2_dif_sig_rank = c(abs_PA_2_dif_sig_rank[1:10,1])#names of top ten pw

top_PA_2_dif_sig = PA_2_dif_sig[which(PA_2_dif_sig[,1] %in% names_abs_PA_2_dif_sig_rank),]# df with top ten dif (significant) pw
  
ggplot(top_PA_2_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("top ten PA pw with signif different NES in cluster 2")+
  theme(plot.title = element_text(size=6))

```

##Cluster 3 vs 1+2

```{r Cluster 3 vs cluster 1+2}

PA_c12 = cbind(PA_c1,PA_c2)

PA_c3_mean = data.frame(apply(PA_c3, 1,mean)) #pw activity mean for patients of cluster 2
PA_c12_mean = data.frame (apply (PA_c12, 1, mean))

PA_c3_c12_dif = PA_c3_mean - PA_c12_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 2

#rank the compared pw-matrix to see the most differently expressed pw
PA_c3_c12_dif_rank = data.frame(PA_c3_c12_dif$apply.PA_c3..1..mean.[order(PA_c3_c12_dif[,1],decreasing = TRUE)])
PA_3_rownames = c(rownames(PA_c3_c12_dif))
PA_3_rownames_rank = c(PA_3_rownames[order(PA_c3_c12_dif[,1],decreasing = TRUE)])

PA_c3_c12_dif_rank = as.data.frame(cbind(PA_3_rownames_rank, PA_c3_c12_dif_rank))
colnames(PA_c3_c12_dif_rank) = c("Pathway", "diff")

```

```{r Wilcoxon Cluster 3 vs 1+2}

#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
PA_c3_m = as.matrix(PA_c3) #matrix needed for wilcoxon
PA_c12_m = as.matrix(PA_c12)
#clsuer 2 compared to the other clusters --> named as KEGG_2_...
PA_3_wilcox_pv  = data.matrix(sapply ( 1:nrow(PA_c3_m),function (x) {
  wilcox.test(PA_c3_m[x,],PA_c12_m[x,],paired=FALSE)
}$p.value))
rownames(PA_3_wilcox_pv)=rownames(PA_c3)
colnames(PA_3_wilcox_pv)="pvalue"
#a lot of NaNs--> Maybe because of constant NES??

#Bonferroni-Korrektur
alpha_PA=0.05/(nrow(PA_3_wilcox_pv))#0.0001157407
#how many pathways have sign different NES??
length(which(PA_3_wilcox_pv<alpha_PA))


PA_3_wilcox_pv[is.nan(PA_3_wilcox_pv)] = 1
```


```{r Volcano Cluster 3 vs 1+2}
#data preparation for Volcano Plot

#problem with FC as there are a lot of Inf(if e.g. 0.1/0)--> what to do with those??
#NaNs in FC could be converted to zero ??
#hence not the FC value data is used but the difference (minus)

#calculate -log10 of p-value for plotting
PA_3_wilcox_pv_log =-log10(PA_3_wilcox_pv)
colnames(PA_3_wilcox_pv_log) = "neg_log10_pv"

#combine differnece and pv matrix
PA_3_pv_dif =as.data.frame(cbind(PA_c3_c12_dif,PA_3_wilcox_pv_log))
colnames(PA_3_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv_PA = -log10(alpha_PA)#=3.593286, cut off later in plot 
PA_3_pv_dif_sig = PA_3_pv_dif[which(PA_3_pv_dif$neg_log10_pv>cutoffpv_PA),]
min(PA_3_pv_dif_sig$neg_log10_pv)
#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PA_3_pv_dif_sigup =PA_3_pv_dif_sig[which(PA_3_pv_dif_sig$diff>0),]

#volcano plot, there are no sign downregulated pw
library(ggplot2)
library(ggrepel)
#plotting
ggplot(PA_3_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= PA_3_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = PA_3_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("differences in NES between KEGG custer 3 compared to cluster (1+2) ")+
  geom_text_repel(data = PA_3_pv_dif_sig, aes(diff, neg_log10_pv), label = row.names(PA_3_pv_dif_sig), size = 2, show.legend = FALSE)+
  xlab ("mean(c3)-mean(c1,c2)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))


#which Pathways are sign different??
PA_3_dif_sig = data.frame(PA_3_pv_dif_sig$diff)
PA_3_dif_sig_names= c(rownames(PA_3_pv_dif_sig))
PA_3_dif_sig = cbind( PA_3_dif_sig_names, PA_3_dif_sig)
colnames(PA_3_dif_sig) = c("Pathway", "diff")

ggplot(PA_3_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PA with signif different NES in cluster 3")+
  theme(plot.title = element_text(size=10))
```

```{r top ten diff pw Cluster 3 vs 1+2}
#top ten pathways
library(dplyr)
abs_PA_3_dif_sig<- PA_3_dif_sig %>% 
  select_if(is.numeric) %>%
  abs()#absolute values

abs_PA_3_dif_sig = cbind(PA_3_dif_sig_names, abs_PA_3_dif_sig)
colnames( abs_PA_3_dif_sig) = c("Pathway", "abs.diff")#matrix with absolute difference in NES and pw names

abs_PA_3_dif_sig_rank = abs_PA_3_dif_sig[order(abs_PA_3_dif_sig$abs.diff, decreasing = T),] #ranked matrix

names_abs_PA_3_dif_sig_rank = c(abs_PA_3_dif_sig_rank[1:10,1])#names of top ten pw

top_PA_3_dif_sig = PA_3_dif_sig[which(PA_3_dif_sig[,1] %in% names_abs_PA_3_dif_sig_rank),]# df with top ten dif (significant) pw
  
ggplot(top_PA_3_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("top ten PA pw with signif different NES in cluster 3")+
  theme(plot.title = element_text(size=6))

```

