---
title: "UMAP_PID_clustering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```
```{r}

#load data
NES_OVERALL_PID_cl <- readRDS("~/GitHub/2022-topic-02-team-02/data/NES_OVERALL_PID_cl.RDS")

library(rlist)
NES_OVERALL_PID_cl_bound = list.cbind(NES_OVERALL_PID_cl)
```


```{r Kmeans }
#further investigation of PID clusters
#find optimal cluster number
library(ggpubr)
library(factoextra)

#elbow plot
km_PID_tw = sapply(1:20, function(k){
  kmeans(x = umap_umap_PID_layout, centers = k, nstart = 50 )$tot.withinss})

km_PID_elbow = plot(km_PID_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#find the optimal number clusters, silhouette plot (average silhouette width)
library(cluster)
fviz_nbclust(umap_umap_PID_layout, kmeans, method='silhouette') #-> opt. cluster = 2
```

```{r}
#define variables
KIRC_PID_UMAP = umap_umap_PID_layout
KIRC_PID = NES_OVERALL_PID_cl_bound

#for PID pathways: optimal number of clusters = 2
PID_km2 =kmeans(KIRC_PID_UMAP, 2 ,nstart = 200)
PID_km = PID_km2$cluster
PID_c1_names = names(PID_km[which(PID_km == 1)]) #patient names of cluster1
PID_c2_names = names(PID_km[which(PID_km == 2)]) # patient names of cluster2
fviz_cluster(PID_km2, KIRC_PID_UMAP,
             palette = c("red", "blue"), 
             geom = "point",
             ellipse.type = "convex",
             xlab   = "UMAP1",
             ylab ="UMAP2",
             main = "PID clusters",
             ggtheme = theme_grey()
             )

PID_c1 = KIRC_PID[,colnames(KIRC_PID) %in% PID_c1_names] # df with patients of cluster1
PID_c2 = KIRC_PID[,!colnames(KIRC_PID) %in% PID_c1_names] #df with patients cluster 2
PID_c1_mean = data.frame(apply(PID_c1, 1,mean)) #pw activity mean for patients of cluster 1
PID_c2_mean = data.frame (apply (PID_c2, 1, mean)) #fpr cluster 2
PID_c1_c2 = cbind(PID_c2_mean, PID_c1_mean) #combine mean cluster 1 and cluster2 
PID_c1_c2_dif = PID_c1_mean - PID_c2_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 1 

#rank the compared pw-matrix to see the most differently expressed pw
PID_c1_c2_dif_rank = data.frame(PID_c1_c2_dif$apply.PID_c1..1..mean.[order(PID_c1_c2_dif[,1],decreasing = TRUE)])
PID_rownames = c(rownames(PID_c1_c2_dif))
PID_rownames_rank = c(PID_rownames[order(PID_c1_c2_dif[,1],decreasing = TRUE)])

PID_c1_c2_dif_rank = as.data.frame(cbind(PID_rownames_rank, PID_c1_c2_dif_rank))
colnames(PID_c1_c2_dif_rank) = c("Pathway", "diff")

  
ggplot(PID_c1_c2_dif_rank, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()


PID_c1_c2_dif_rank %>%
  filter(PID_c1_c2_dif_rank$diff !=0) %>%
  ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
    geom_bar(stat="identity")+
    coord_flip()
  

  
 
PID_c1_c2_dif_rank%>%
  filter(abs(PID_c1_c2_dif_rank$dif)>0.20)%>%
  ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()

#!!! until now there was no testing for significance--> these pw are differentially expressed but we dont now yet if significant--> see below
```

```{r calculations (wilcoxon, FC)}
#working with FC and not with difference (minus)
PID_c1_c2_FC = data.matrix(PID_c1_mean/PID_c2_mean)
colnames(PID_c1_c2_FC) = "FC"
PID_c1_c2_FC[is.nan(PID_c1_c2_FC)]=0

#work with wilcoxon test as some of the pw have an enrichment score of zero for all patients, thus no normality, as shown below
PID_c1_min = apply(PID_c1, 1, min)
PID_c1_max = apply(PID_c1, 1, max) 
PID_c1_constant = c(names(which(PID_c1_min==PID_c1_max)))
length(PID_c1_constant) #there are 271 pw with constant NES, hence we use wilcoxon test 


#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
PID_c1_m = as.matrix(PID_c1) #matrix needed for wilcoxon
PID_c2_m = as.matrix(PID_c2)
PID_wilcox_pv  = data.matrix(sapply ( 1:nrow(PID_c1_m),function (x) {
  wilcox.test(PID_c1_m[x,],PID_c2_m[x,],paired=FALSE)
}$p.value))
rownames(PID_wilcox_pv)=rownames(PID_c1)
colnames(PID_wilcox_pv)="pvalue"

#Bonferroni-Korrektur
alpha_PID=0.05/(nrow(PID_wilcox_pv))
#how many pathways have sign different NES??
length(which(PID_wilcox_pv<alpha_PID))


PID_wilcox_pv[is.nan(PID_wilcox_pv)] = 1
```

```{r Volcano Plot}
#data preparation for Volcano Plot

PID_wilcox_pv_log =-log10(PID_wilcox_pv)
colnames(PID_wilcox_pv_log) = "neg_log10_pv"
PID_wilcox_pv_log [PID_wilcox_pv_log  == Inf] <- 0

#combine diff and pv matrix
PID_pv_dif =as.data.frame(cbind(PID_c1_c2_dif,PID_wilcox_pv_log))
colnames(PID_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv_PID = -log10(alpha_PID) 
PID_pv_dif_sig = PID_pv_dif[which(PID_pv_dif$neg_log10_pv>cutoffpv_PID),]
min(PID_pv_dif_sig$neg_log10_pv)
#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_pv_dif_sigup = PID_pv_dif_sig[which(PID_pv_dif_sig$diff>0),]

#volcano plot, there are no sign downregulated pw
#plotting
ggplot(PID_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= PID_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = PID_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("differences in NES between two PID clusters")+
  geom_text_repel(data = PID_pv_dif_sig, aes(diff, neg_log10_pv), label = row.names(PID_pv_dif_sig), size = 2, show.legend = FALSE)+
  xlab ("mean(c1)-mean(c2)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))


#which Pathways are sign different??
PID_dif_sig = data.frame(PID_pv_dif_sig$diff)
PID_dif_sig_names= c(rownames(PID_pv_dif_sig))
PID_dif_sig = cbind( PID_dif_sig_names, PID_dif_sig)
colnames(PID_dif_sig) = c("Pathway", "diff")

ggplot(PID_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PID pw with signif different NES in 2 KIRC clusters")+
  theme(plot.title = element_text(size=10))

```


```{r top ten diff pw }
#top ten pathways
abs_PID_dif_sig<- PID_dif_sig %>% 
  select_if(is.numeric) %>%
  abs()#absolute values

abs_PID_dif_sig = cbind(PID_dif_sig_names, abs_PID_dif_sig)
colnames( abs_PID_dif_sig) = c("Pathway", "abs.diff")#matrix with absolute difference in NES and pw names

abs_PID_dif_sig_rank = abs_PID_dif_sig[order(abs_PID_dif_sig$abs.diff, decreasing = T),] #ranked matrix

names_abs_PID_dif_sig_rank = c(abs_PID_dif_sig_rank[1:10,1])#names of top ten pw

top_PID_dif_sig = PID_dif_sig[which(PID_dif_sig[,1] %in% names_abs_PID_dif_sig_rank),]# df with top ten dif (significant) pw
  
ggplot(top_PID_dif_sig, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("top ten PID pw with signif different NES in cluster 1 vs 2")+
  theme(plot.title = element_text(size=6))

```



```{r}
#Are the pathways in both clusters upregulated compared to normal tissue and in one of the clusters even more? or are the pw in one cluster up and in one downregulated compared to normal tissue?? -->whats the absolute NES in the top ten pw for both clusters?

PID_top_c1 = PID_c1[which(rownames(PID_c1) %in% names_abs_PID_dif_sig_rank),]
PID_top_c2 = PID_c2[which(rownames(PID_c2) %in% names_abs_PID_dif_sig_rank),]

PID_top_c1_mean = data.frame(apply(PID_top_c1, 1, mean))
PID_top_c2_mean = data.frame(apply(PID_top_c2, 1, mean))
colnames(PID_top_c1_mean) = "cluster 1"
colnames(PID_top_c2_mean) = "cluster 2"
PID_top_c1_c2_mean = as.matrix(cbind(PID_top_c1_mean, PID_top_c2_mean))


PID_top_c1_c2_mean_melted = (melt(PID_top_c1_c2_mean))
colnames(PID_top_c1_c2_mean_melted) = c("Pathway", "cluster", "NES")
ggplot(PID_top_c1_c2_mean_melted, aes( fill = Pathway, y=NES, x=cluster)) + 
    geom_bar(position="dodge", stat="identity")
```