---
title: "Metabolic genesets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, include=FALSE}
library(msigdbr)
library(tidyverse)
library(fgsea)
library(circlize)
library(ComplexHeatmap)
```


```{r load data, include=FALSE}
genesets = readRDS("../data/hallmarks_genesets.rds")
KIRC_tumor_cl = readRDS("/Users/timwenzel/Desktop/GitHub/2022-topic-02-team-02/data/tcga_KIRC_tumor_cl.rds")
KIRC_norm_cl = readRDS("/Users/timwenzel/Desktop/GitHub/2022-topic-02-team-02/data/tcga_KIRC_norm_cl.rds")
KIRC_GSEA_activity = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity.rds")
KIRC_GSEA_activity_PID = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity_PID.rds")
KIRC_GSEA_activity_KEGG = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity_KEGG.rds")
KIRC_GSEA_activity_hallmark = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity_hallmark.rds")
```

```{r genesets}
## hallmark genesets ## 
#load metabolic genesets
hallmarks = msigdbr(species = "Homo sapiens", category = "H")
#create a df with metabolic pathways and genes as columns 
hallmarks_gsname = hallmarks$gs_name
hallmarks_ensembl = hallmarks$ensembl_gene
hallmarks = as.data.frame(cbind(hallmarks_gsname, hallmarks_ensembl))

#create a df with names of pathways
pathway_names_H = c(unique(hallmarks$hallmarks_gsname))
#create a list in which the pathways will be stored (outout has to be a list)
metabolic_genesets_H = list(list())
#fill the list with pathways and genes
for (x in 1:length(pathway_names_H)){
  metabolic_genesets_H[[x]] = pathway_names_H[x]
  z = c((hallmarks[which(hallmarks$hallmarks_gsname == pathway_names_H[x]),2]))
  for (k in 1:length(z)){
  metabolic_genesets_H[[x]][[k]] = z[k]
  }}
names(metabolic_genesets_H) = pathway_names_H


## KEGG genesets ##
KEGG = msigdbr(species = "Homo sapiens", category = "C2", subcategory  = "CP:KEGG")

KEGG_gsname = KEGG$gs_name
KEGG_ensembl = KEGG$ensembl_gene
KEGG = as.data.frame(cbind(KEGG_gsname, KEGG_ensembl))

pathway_names_KEGG = c(unique(KEGG$KEGG_gsname))
#create a list in which the pathways will be stored (outout has to be a list)
metabolic_genesets_KEGG = list(list())
#fill the list with pathways and genes
for (x in 1:length(pathway_names_KEGG)){
  metabolic_genesets_KEGG[[x]] = pathway_names_KEGG[x]
  z = c((KEGG[which(KEGG$KEGG_gsname == pathway_names_KEGG[x]),2]))
  for (k in 1:length(z)){
  metabolic_genesets_KEGG[[x]][[k]] = z[k]
  }}
names(metabolic_genesets_KEGG) = pathway_names_KEGG

## PID pathways ##
PID_pathways = msigdbr(species = "Homo sapiens", category = "C2", subcategory  = "CP:PID")

#create a df with metabolic pathways and genes as columns 
PID_gsname = PID_pathways$gs_name
PID_ensembl = PID_pathways$ensembl_gene
PID_pathways = as.data.frame(cbind(PID_gsname, PID_ensembl))

#create a vector with names of pathways
pathway_names_PID = c(unique(PID_pathways$PID_gsname))
#create a list in which the pathways will be stored (outout has to be a list)
metabolic_genesets_PID = list(list())
#fill the list with pathways and genes
for (x in 1:length(pathway_names_PID)){
  metabolic_genesets_PID[[x]] = pathway_names_PID[x]
  z = c((PID_pathways[which(PID_pathways$PID_gsname == pathway_names_PID[x]),2]))
  for (k in 1:length(z)){
  metabolic_genesets_PID[[x]][[k]] = z[k]
  }}
names(metabolic_genesets_PID) = pathway_names_PID
```


```{r log FC tumor vs norm}
#log2FC for every patient, only protein coding without constant genes
KIRC_FC_patients = data.frame(tcga_KIRC_tumor_cl - tcga_KIRC_norm_cl)
KIRC_GSEA_prep = 
rownames_to_column(KIRC_FC_patients, var = "ensembl_id")
distinct(KIRC_GSEA_prep)
```


```{r run GSEA}
##run GSEA for hallmark pathways and save the output as list over all patients
KIRC_GSEA_results_H = list()
for (i in 2:(ncol(KIRC_GSEA_prep))){
  x = c(KIRC_GSEA_prep[,i])
  names(x) = KIRC_GSEA_prep$ensembl_id
  x = x[rank(x, ties.method = "first")]
  
  KIRC_GSEA_results_H[[i]] = fgsea(pathways = metabolic_genesets_H,
                             stats =  x,
                             scoreType = "std",
                             nPermSimple = 10000)
}
## repeat for KEGG pathways 
KIRC_GSEA_results_KEGG = list()
(for (i in 2:(ncol(KIRC_GSEA_prep))){
  x = c(KIRC_GSEA_prep[,i])
  names(x) = KIRC_GSEA_prep$ensembl_id
  x = x[rank(x, ties.method = "first")]
  KIRC_GSEA_results_KEGG[[i]] = fgsea(pathways = metabolic_genesets_KEGG,
                             stats =  x,
                             scoreType = "std",
                             nPermSimple = 10000)
})

#repeat for PID pathways
KIRC_GSEA_results_PID = list()
(for (i in 2:(ncol(KIRC_GSEA_prep))){
  x = c(KIRC_GSEA_prep[,i])
  names(x) = KIRC_GSEA_prep$ensembl_id
  x = x[rank(x, ties.method = "first")]
  KIRC_GSEA_results_PID[[i]] = fgsea(pathways = metabolic_genesets_PID,
                             stats =  x,
                             scoreType = "std",
                             nPermSimple = 10000)
})
#Warning: There were 2 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000)

```


```{r create pathway activity matrix}
## final acitvity matrix, H = no pvalue filtering, H2 = pvalue filtering
KIRC_GSEA_H_noNA = list()
for (v in 2:length(KIRC_GSEA_results_H)){
  KIRC_GSEA_H_noNA[[v]] = KIRC_GSEA_results_H[[v]]$padj
  KIRC_GSEA_H_noNA[[v]][is.na(KIRC_GSEA_H_noNA[[v]])] = 1
}

KIRC_GSEA_NES_H2 = list()
for (v in 2:length(KIRC_GSEA_results_H)){
  KIRC_GSEA_NES_H2[[v]] = KIRC_GSEA_results_H[[v]]$NES
}
  
for (v in 2:length(KIRC_GSEA_results_H)){
  for (z in 1:length(KIRC_GSEA_results_H[[2]]$padj)){
  if (KIRC_GSEA_H_noNA[[v]][z] <= 0.05) {
  KIRC_GSEA_NES_H2[[v]][z]= KIRC_GSEA_results_H[[v]]$NES[z] }
   else {KIRC_GSEA_NES_H2[[v]][z] = 0}
  }}


KIRC_GSEA_NES_H2 = KIRC_GSEA_NES_H2[-1]
KIRC_GSEA_NES_H2 = as.data.frame(KIRC_GSEA_NES_H2) #auffällig: NA für manche NES, ES vorhanden, aber kein entsprechender p-value? problem solved
rownames(KIRC_GSEA_NES_H2) = pathway_names_H
colnames(KIRC_GSEA_NES_H2) = colnames(KIRC_tumor_cl)
## pathway activity matrix with NES values


KIRC_GSEA_NES_H = list()
for (v in 2:length(KIRC_GSEA_results_H)){
  KIRC_GSEA_NES_H[[v]] = KIRC_GSEA_results_H[[v]]$NES
}

KIRC_GSEA_NES_H = KIRC_GSEA_NES_H[-1]
KIRC_GSEA_NES_H = as.data.frame(KIRC_GSEA_NES_H) #auffällig: NA für manche NES, ES vorhanden, aber kein entsprechender p-value? 
rownames(KIRC_GSEA_NES_H) = pathway_names_H
colnames(KIRC_GSEA_NES_H) = colnames(KIRC_tumor_cl)
 ## pathway activity matrix with NES values

##create matrix with PADJ, not used for further analysis tho
KIRC_GSEA_PADJ_H = list()
for (v in 2:length(KIRC_GSEA_results_H)){
  KIRC_GSEA_PADJ_H[[v]] = KIRC_GSEA_results_H[[v]]$padj
}
KIRC_GSEA_PADJ_H = KIRC_GSEA_PADJ_H[-1]
KIRC_GSEA_PADJ_H = as.data.frame(KIRC_GSEA_PADJ_H)
rownames(KIRC_GSEA_PADJ_H) = pathway_names_H
colnames(KIRC_GSEA_PADJ_H) = colnames(KIRC_tumor_cl)#  matrix with padj values

##repeat for KEGG pathways

KIRC_GSEA_KEGG_noNA = list()
for (v in 2:length(KIRC_GSEA_results_KEGG)){
  KIRC_GSEA_KEGG_noNA[[v]] = KIRC_GSEA_results_KEGG[[v]]$padj
  KIRC_GSEA_KEGG_noNA[[v]][is.na(KIRC_GSEA_KEGG_noNA[[v]])] = 1
}

KIRC_GSEA_NES_KEGG = list()
for (v in 2:length(KIRC_GSEA_results_KEGG)){
  KIRC_GSEA_NES_KEGG[[v]] = KIRC_GSEA_results_KEGG[[v]]$NES
}
  
for (v in 2:length(KIRC_GSEA_results_KEGG)){
  for (z in 1:length(KIRC_GSEA_results_KEGG[[2]]$padj)){
  if (KIRC_GSEA_KEGG_noNA[[v]][z] <= 0.05) {
  KIRC_GSEA_NES_KEGG[[v]][z]= KIRC_GSEA_results_KEGG[[v]]$NES[z] }
   else {KIRC_GSEA_NES_KEGG[[v]][z] = 0}
  }}

KIRC_GSEA_NES_KEGG = KIRC_GSEA_NES_KEGG[-1]
KIRC_GSEA_NES_KEGG = as.data.frame(KIRC_GSEA_NES_KEGG) #auffällig: NA für manche NES, ES vorhanden, aber kein entsprechender p-value? 
rownames(KIRC_GSEA_NES_KEGG) = pathway_names_KEGG
colnames(KIRC_GSEA_NES_KEGG) = colnames(KIRC_tumor_cl)# pathway activity matrix with NES values

##repeat for PID pathways

KIRC_GSEA_PID_noNA = list()
for (v in 2:length(KIRC_GSEA_results_PID)){
  KIRC_GSEA_PID_noNA[[v]] = KIRC_GSEA_results_PID[[v]]$padj
  KIRC_GSEA_PID_noNA[[v]][is.na(KIRC_GSEA_PID_noNA[[v]])] = 1
}

KIRC_GSEA_NES_PID = list()
for (v in 2:length(KIRC_GSEA_results_PID)){
  KIRC_GSEA_NES_PID[[v]] = KIRC_GSEA_results_PID[[v]]$NES
}
  
for (v in 2:length(KIRC_GSEA_results_PID)){
  for (z in 1:length(KIRC_GSEA_results_PID[[2]]$padj)){
  if (KIRC_GSEA_PID_noNA[[v]][z] <= 0.05) {
  KIRC_GSEA_NES_PID[[v]][z]= KIRC_GSEA_results_PID[[v]]$NES[z] }
   else {KIRC_GSEA_NES_PID[[v]][z] = 0}
  }}

KIRC_GSEA_NES_PID = KIRC_GSEA_NES_PID[-1]
KIRC_GSEA_NES_PID = as.data.frame(KIRC_GSEA_NES_PID) #auffällig: NA für manche NES, ES vorhanden, aber kein entsprechender p-value? 
rownames(KIRC_GSEA_NES_PID) = pathway_names_PID
colnames(KIRC_GSEA_NES_PID) = colnames(KIRC_tumor_cl)# pathway activity matrix with NES values



## bind als NES dataframes to create one acitivty matrix with genesets H,KEGG and PID (432 pathways total)
KIRC_GSEA_activity = rbind(KIRC_GSEA_NES_H2,KIRC_GSEA_NES_KEGG,KIRC_GSEA_NES_PID)
KIRC_GSEA_pathways = c(pathway_names_H,pathway_names_KEGG,pathway_names_PID)

```


```{r barplot of mean and median for each pathway}
#irrelevant pathways, which are enriched in atleast 4 patients
irrelevant = c("HALLMARK_ALLOGRAFT_REJECTION","KEGG_GRAFT_VERSUS_HOST_DISEASE","KEGG_ALLOGRAFT_REJECTION",
"KEGG_LEISHMANIA_INFECTION")
## plot mean activity
KIRC_GSEA_activity_mean = data.frame(apply(KIRC_GSEA_activity, 1 , mean))
rownames(KIRC_GSEA_activity_mean) = rownames(KIRC_GSEA_activity)
rownamos = rownames(KIRC_GSEA_activity_mean)
KIRC_GSEA_activity_mean_prep = cbind(rownamos,KIRC_GSEA_activity_mean)
colnames(KIRC_GSEA_activity_mean_prep) = c("pathway","NES")
data.frame(KIRC_GSEA_activity_mean_prep)
KIRC_GSEA_activity_mean_prep = KIRC_GSEA_activity_mean_prep[!rownames(KIRC_GSEA_activity_mean_prep)%in%irrelevant,]

KIRC_GSEA_activity_mean_prep %>%
  filter(NES != 0) %>%
   mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col ()+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA mean expression != 0")

KIRC_GSEA_activity_mean_prep %>%
  filter(abs(NES) > 0.1) %>%
   mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col ()+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA mean expression cutoff 0.1")

##repeat for median
KIRC_GSEA_activity_median = data.frame(apply(KIRC_GSEA_activity, 1 , median))
rownames(KIRC_GSEA_activity_median) = rownames(KIRC_GSEA_activity)
rownamos = rownames(KIRC_GSEA_activity_median)
KIRC_GSEA_activity_median_prep = cbind(rownamos,KIRC_GSEA_activity_median)
colnames(KIRC_GSEA_activity_median_prep) = c("pathway","NES")
data.frame(KIRC_GSEA_activity_median_prep)
KIRC_GSEA_activity_median_prep = KIRC_GSEA_activity_median_prep[!rownames(KIRC_GSEA_activity_median_prep)%in%irrelevant,]


KIRC_GSEA_activity_median_prep %>%
  filter(abs(NES) != 0) %>%
   mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col ()+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA median expression")
```


```{r barplot test patient}
## plot test patient

Test_patient = data.frame(KIRC_GSEA_activity[,1])
rownames(Test_patient) = rownames(KIRC_GSEA_activity)
rownamos = rownames(Test_patient)
Testp1 = cbind(rownamos,Test_patient)
colnames(Testp1) = c("pathway","NES")


#plotting results for example patient
Testp1 %>%
  filter(NES != 0) %>%
   mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col ()+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA test patient")
 
```


```{r compute enrichment frequency}
## compute the sum of enriched pathways 
KIRC_GSEA_sum = c()
for (i in 1:nrow(KIRC_GSEA_activity)) {
  KIRC_GSEA_sum[i] = length(which(KIRC_GSEA_activity[i,] > 0))
}
KIRC_GSEA_activity_sum = as.data.frame(KIRC_GSEA_sum) 
rownames(KIRC_GSEA_activity_sum) = rownames(KIRC_GSEA_activity)
colnames(KIRC_GSEA_activity_sum) = "Enrichment rate"
KIRC_GSEA_activity_sum1 = cbind(rownamos, KIRC_GSEA_activity_sum)
```


```{r plot sum results}
##plot sum results
KIRC_GSEA_activity_sum %>%
  filter(`Enrichment rate` > 0) %>%
  ggplot(aes(x = `Enrichment rate`)) +
  geom_histogram(bins = length(which(KIRC_GSEA_activity_sum$`Enrichment rate` > 0)),           binwidth = 0.5,
    color="darkblue", fill="lightblue",
    )+
  labs ( y="Pathway Frequency", x="Enrichment Frequency")

```
```{r filter top 10 sum}
KIRC_GSEA_activity_sum_order = KIRC_GSEA_activity_sum1$`Enrichment rate`[order(KIRC_GSEA_activity_sum1$`Enrichment rate`, decreasing = TRUE)]

rownamos_ordered = KIRC_GSEA_activity_sum1$rownamos[order(KIRC_GSEA_activity_sum1$`Enrichment rate`, decreasing = TRUE)]

activity_sum_rank = cbind(rownamos_ordered,KIRC_GSEA_activity_sum_order)
colnames(activity_sum_rank) = c("Pathway","EnrichmentFrequency")
which_larger_0 = which(activity_sum_rank[,2]> 0)
sum_larger_0 = data.frame(activity_sum_rank[which_larger_0,])

```

```{r plot top 10 pathways}
KIRC_GSEA_activity_sum_top10 = KIRC_GSEA_activity_mean_prep[sum_larger_0$Pathway[1:10],]


  KIRC_GSEA_activity_sum_top10 %>%
  mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col (fill = "lightblue")+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA mean expression top 10 sum")
```

```{r filter top 10 mean}
##compute top 10 mean (absolute values)
KIRC_GSEA_activity_mean_order = KIRC_GSEA_activity_mean_prep$NES[order(abs(KIRC_GSEA_activity_mean_prep$NES), decreasing = TRUE)]

pathways_ordered = KIRC_GSEA_activity_mean_prep$pathway[order(abs(KIRC_GSEA_activity_mean_prep$NES), decreasing = TRUE)]

activity_mean_rank = cbind(pathways_ordered,KIRC_GSEA_activity_mean_order)
colnames(activity_mean_rank) = c("Pathway","NES")
which_mean_unqeual_0 = which(activity_mean_rank[,2]!= 0)
mean_unequal_0 = data.frame(activity_mean_rank[which_mean_larger_0,])
```


```{r plot top 10 mean}
KIRC_GSEA_activity_mean_top10 = KIRC_GSEA_activity_mean_prep[activity_mean_rank[1:10],]


KIRC_GSEA_activity_mean_top10%>%
  mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col ()+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA mean expression top 10 mean")

```

```{r Filtering of genesets according to relevance}
sum_larger_0_rel = sum_larger_0[!rownames(sum_larger_0)%in%irrelevant,]
which_larger_4 = which(as.numeric(sum_larger_0_rel$Enrichment.Frequency) > 4)
sum_larger_4_rel = data.frame(sum_larger_0_rel[which_larger_4,])

sum_larger_4_rel %>%
  ggplot(aes(x = as.numeric(Enrichment.Frequency))) +
  geom_histogram( binwidth = 0.5,
    color="darkblue", fill="lightblue",
    )+
  labs ( y="Pathway Frequency", x="Enrichment Frequency")


KIRC_GSEA_activity_sum_top10_rel = KIRC_GSEA_activity_mean_prep[sum_larger_0_rel$Pathway[1:10],]

KIRC_GSEA_activity_sum_top10_rel%>%
  mutate(met.pathways = gsub ("metabolic pathways","",pathway),
  pathway = gsub("_"," ",pathway)) %>%
  
  ggplot(aes(x=reorder(pathway,NES), y=NES)) +
  geom_col ()+
  theme_classic()+
  lims(y=c(-3.2,3.2))+
  coord_flip()+
  labs (y = "Normalized enrichment score (NES)",
        x = "Gene set",
        title = "GSEA mean expression top 10 sum relevant")

```

```{r heatmap}
heatmap.2(as.matrix(KIRC_GSEA_NES_KEGG),dendrogram = "column", hclustfun = hclust, trace = "none", margins = c(10,10))

heatmap.2(as.matrix(KIRC_GSEA_NES_PID),dendrogram = "column", hclustfun = hclust, trace = "none")

```
```{r complex heatmap}
col_fun = circlize::colorRamp2(c(-3,0,3), c("blue","black", "red"))
as.matrix(KIRC_GSEA_activity)
Heatmap(KIRC_GSEA_activity, name = "mat", column_names_gp = gpar(fontsize = 5), row_names_gp = gpar(fontsize = 1.5), column_split = 2, row_split = 3,row_gap = unit(c(1,2), "mm"),
 column_gap = unit(c(1,2), "mm"), col = col_fun)

PID_filtered = c(rownames(KIRC_PID_cl))
KIRC_GSEA_activity_PID = KIRC_GSEA_activity_PID[which(rownames(KIRC_GSEA_activity_PID) %in% PID_filtered),]
Heatmap(KIRC_GSEA_activity_PID, name = "mat", column_names_gp = gpar(fontsize = 5), row_names_gp = gpar(fontsize = 5),column_split = 2,col = col_fun)

tcga_KIRC_norm_min = apply(KIRC_GSEA_activity_KEGG, 1, min)
tcga_KIRC_norm_max= apply(KIRC_GSEA_activity_KEGG, 1, max) #for normal cell data set
tcga_KIRC_tumor_constant = c(names(which(tcga_KIRC_norm_max==tcga_KIRC_norm_min)))
KIRC_GSEA_activity_KEGG1 = KIRC_GSEA_activity_KEGG[-which(rownames(KIRC_GSEA_activity_KEGG) %in% tcga_KIRC_tumor_constant),]
Heatmap(KIRC_GSEA_activity_KEGG1, name = "mat", column_names_gp = gpar(fontsize = 5), row_names_gp = gpar(fontsize = 5),col = col_fun, column_km = 3,column_gap = unit(c(1,2), "mm"))

Heatmap(KIRC_GSEA_activity_hallmark, name = "mat", column_names_gp = gpar(fontsize = 5), row_names_gp = gpar(fontsize = 6),col = col_fun, column_km = 2,
 column_gap = unit(c(1,2), "mm"))


```


