---
title: "PID_TCGA_filtered"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
tumorlist_z <- readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/tumorlist_z.RDS")
KIRC_PID_cl <- readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/KIRC_PID_cl.RDS")
```

```{r}
library(msigdbr)
library(tidyverse)
library(fgsea)
```


```{r}
PID_filtered = c(rownames(KIRC_PID_cl))
whichi = which(names(metabolic_genesets_PID) %in% PID_filtered)
metabolic_genesets_PID = metabolic_genesets_PID[c(whichi)]
```

```{r}
PVALUES_OVERALL_PID = list()
NES_OVERALL_PID = list()
GSEA_OVERALL_PID <- vector(mode = 'list', length = 33)

PID_names = names(metabolic_genesets_PID)

for (j in 1:33) {
  for (i in 1:(ncol(tumorlist_z[[j]]))){
    m = c(tumorlist_z[[j]][,i])
    names(m) = rownames(tumorlist_z[[j]])
    m = m[order(m), drop = FALSE]
    GSEA_OVERALL_PID[[j]][[i]] = fgsea(pathways = metabolic_genesets_PID,
                               stats = m,
                               scoreType = "std",
                               nproc = 6)
  }
  print("GSEA done")
  names(GSEA_OVERALL_PID[[j]]) = colnames(tumorlist_z[[j]])
  PVALUES_OVERALL_PID[[j]] = data.frame(row.names = PID_names)
  for (h in 1:ncol(tumorlist_z[[j]])){
    a = GSEA_OVERALL_PID[[j]][[h]][,3]
    PVALUES_OVERALL_PID[[j]][1:length(metabolic_genesets_PID),h] = a
  }
  PVALUES_OVERALL_PID[[j]][is.na(PVALUES_OVERALL_PID[[j]])] = 1
  colnames(PVALUES_OVERALL_PID[[j]]) = colnames(tumorlist_z[[j]])
  NES_OVERALL_PID[[j]] = data.frame(row.names = PID_names)
  for (k in 1:ncol(tumorlist_z[[j]])){
    t = GSEA_OVERALL_PID[[j]][[k]][,6]
    NES_OVERALL_PID[[j]][1:length(metabolic_genesets_PID),k] = t
  }
  colnames(NES_OVERALL_PID[[j]]) = colnames(tumorlist_z[[j]])
  indexes = which(PVALUES_OVERALL_PID[[j]] >= 0.05, arr.ind=TRUE)
  rows = as.vector(indexes[,1])
  cols = as.vector(indexes[,2])
  for (l in 1:length(rows)) {
    NES_OVERALL_PID[[j]][rows[l], cols[l]] = 0
    print(l)
  }
  print("once again")
}
names(GSEA_OVERALL_PID) = all_tumortypes_names
names(PVALUES_OVERALL_PID) = all_tumortypes_names
names(NES_OVERALL_PID) = all_tumortypes_names

NES_mean_list = list()
for (i in 1:33){
  NES_mean_list[[i]] = data.frame(apply(NES_OVERALL_PID[[i]], 1 , mean))
}
NES_mean_PID = data.frame(row.names = PID_names)
for (j in 1:33){
  NES_mean_PID[,j] = NES_mean_list[[j]]
}
colnames(NES_mean_PID) = all_tumortypes_names
###

NES_matrix_PID = as.matrix(NES_mean_PID)
heatmap.2(NES_matrix_PID, dendrogram = "column", hclustfun = hclust, trace = "none", margins = c(11,11))

#create dendrogram 
PID_dendro_matrix = t(NES_matrix_PID)
PID_dendro = as.dendrogram(hclust(d = dist(x = PID_dendro_matrix)))
dendro_PID =  ggdendrogram(data = PID_dendro, rotate = TRUE)
print(dendro_PID)
```

