---
title: "hir clustering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

```{r data}
TCGA_pw_MMR = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/NES_OVERALL_MMR.RDS")
TCGA_pw_PID =  readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/NES_OVERALL_PID_cl.RDS")
cancer_abc = names(TCGA_pw_MMR) 
pid_names = rownames(TCGA_pw_PID[[1]])
```

```{r packages}
library(ComplexHeatmap)
library(grid)
library(ggplot2)
library(ggdendro)
library(dplyr)
library(reshape2)
library(ggpubr)
library(gridExtra)
```

```{r}
#compute dist matrix 

dist_list = list()
for (i in 1:length(TCGA_pw_PID)){
  x = TCGA_pw_PID[[i]]
  dist_list[[i]] = dist(t(x))
}

hclust_list = list()
for (i in 1:length(TCGA_pw_PID)){
  y = dist_list[[i]]
  hclust_list[[i]] = hclust(y, method = "ward.D2")
}
ggdendrogram(hclust_list[[12]], method = "ward.D2")

cut_list = list()
for (i in 1:length(TCGA_pw_PID)){
  v = hclust_list[[i]]
  cut_list[[i]] = (cutree(v, k = 3))
}

cutcut_list = list()
for (i in 1:length(TCGA_pw_PID)){
  cutcut_list[[i]] = as.numeric(cut_list[[i]])
}

cluster1_list =  list()
for (i in 1:length(TCGA_pw_PID)){
b = cut_list[[i]]
a = cutcut_list[[i]]
cluster1_list[[i]] = names(b[which(a == 1)])
}

cluster2_list =  list()
for (i in 1:length(TCGA_pw_PID)){
b = cut_list[[i]]
a = cutcut_list[[i]]
cluster2_list[[i]] = names(b[which(a == 2)])
}

cluster3_list =  list()
for (i in 1:length(TCGA_pw_PID)){
b = cut_list[[i]]
a = cutcut_list[[i]]
cluster3_list[[i]] = names(b[which(a == 3)])
}

c1_patients = list()
for (i in 1:length(TCGA_pw_PID)){
n = TCGA_pw_PID[[i]]
c1_patients[[i]] = n[,which(colnames(n)%in%cluster1_list[[i]])]
}

c2_patients = list()
for (i in 1:length(TCGA_pw_PID)){
n = TCGA_pw_PID[[i]]
c2_patients[[i]] = n[,which(colnames(n)%in%cluster2_list[[i]])]
}

c3_patients = list()
for (i in 1:length(TCGA_pw_PID)){
n = TCGA_pw_PID[[i]]
c3_patients[[i]] = n[,which(colnames(n)%in%cluster3_list[[i]])]
}
```

```{r h test over all}
##H-test 
H1_cluster = list()
for (i in 1:length(TCGA_pw_PID)){
d = c1_patients[[i]]
H1_cluster[[i]] = c(rep(c(1),times = ncol(d)))
}


H2_cluster = list()
for (i in 1:length(TCGA_pw_PID)){
f = c2_patients[[i]]
H2_cluster[[i]] = c(rep(c(2),times = ncol(f)))
}

H3_cluster = list()
for (i in 1:length(TCGA_pw_PID)){
m = c3_patients[[i]]
H3_cluster[[i]] = c(rep(c(3),times = ncol(m)))
}

H123 = list()
for (i in 1:length(TCGA_pw_PID)){
g = H1_cluster[[i]]
j = H2_cluster[[i]]
k = H3_cluster[[i]]
H123[[i]] = c(g,j,k)
}

H_prep = list()
for (i in 1:length(TCGA_pw_PID)){
l = c1_patients[[i]]
p = c2_patients[[i]]
u = c3_patients[[i]]
H_prep[[i]] = cbind(l,p,u)
}

pid_names_cluster = c(pid_names,"Cluster")
H_tot = list()
for (i in 1:length(TCGA_pw_PID)){
t = H_prep[[i]]
h = H123[[i]]
H_tot[[i]] = data.frame(rbind(t,h))
row.names(H_tot[[i]]) = pid_names_cluster
}


ks_pvlist = list()
ks = c()
for (i in 1:length(TCGA_pw_PID)){
  for(j in 1:nrow(TCGA_pw_PID[[12]])){
    t = H_tot[[i]]
    v = as.numeric(t[j,])
    q = as.numeric(t[89,])
    ks[j] = kruskal.test(v,q)$p.value
    ks_pvlist[[i]] = ks
  }
}
View(ks_pvlist)

for (i in 1:length(TCGA_pw_PID)){
  ks_pvlist[[i]] = as.data.frame(ks_pvlist[[i]])
  rownames(ks_pvlist[[i]]) = pid_names
  colnames(ks_pvlist[[i]]) = c("pvalue")
}

cutoff = 0.05 / length(pid_names)

for (i in 1:length(TCGA_pw_PID)){
  ks_pvlist[[i]]$pvalue[which(is.nan(ks_pvlist[[i]]$pvalue))] = 1
}
names(ks_pvlist) = cancer_abc
```



```{r pvalue cutoff and reordering}
pv_log = list()
for (i in 1:length(ks_pvlist)){
  h = ks_pvlist[[i]]$pvalue
  pv_log[[i]] = data.frame( -log10(h))
}
for (i in 1:length(TCGA_pw_PID)){
  rownames(pv_log[[i]]) = pid_names
  colnames(pv_log[[i]]) = c("neg_log10_pv")
}
for (i in 1:length(TCGA_pw_PID)){
  pv_log[[i]][pv_log[[i]] == Inf] = 0
}
logcut = -log10(cutoff)

ks_pv_log = list()
for (i in 1:length(TCGA_pw_PID)){
  ks_pv_log[[i]] = cbind(pv_log[[i]],pid_names)
  colnames(ks_pv_log[[i]]) = c("neg_log_pv", "pathways")
}
names(ks_pv_log) = cancer_abc

ks_sig= list()
for (i in 1:length(TCGA_pw_PID)){
  g = ks_pv_log[[i]]
  ks_sig[[i]] = g[which(g$neg_log_pv>logcut),]
}

for (i in 1:length(TCGA_pw_PID)){
  g = ks_sig[[i]]
  ks_sig[[i]] = g[order(g$neg_log_pv,decreasing = TRUE),]
}
names(ks_sig) = cancer_abc
View(ks_sig$KIRC)
sig_kirc_20 = rownames(ks_sig$KIRC[1:20,])
sig_kirc = ks_sig$KIRC[1:20,]

```


```{r plot prep}

a = Heatmap(c1_patients[[12]])
b = Heatmap(c2_patients[[12]])
c = Heatmap(c3_patients[[12]])


sig_patient1= c1_patients[[12]][which(rownames(c1_patients[[12]])%in%sig_kirc_20),]
sig_patient1_df = cbind(rownames(sig_patient1),sig_patient1)
sig_patient1_order = data.matrix(sig_patient1[match(sig_kirc_20,sig_patient1_df$`rownames(sig_patient1)`),])

sig_patient2= c2_patients[[12]][which(rownames(c2_patients[[12]])%in%sig_kirc_20),]
sig_patient2_df = cbind(rownames(sig_patient2),sig_patient2)
sig_patient2_order = data.matrix(sig_patient2[match(sig_kirc_20,sig_patient2_df$`rownames(sig_patient2)`),])


sig_patient3= c3_patients[[12]][which(rownames(c3_patients[[12]])%in%sig_kirc_20),]
sig_patient3_df = cbind(rownames(sig_patient3),sig_patient3)
sig_patient3_order = data.matrix(sig_patient3[match(sig_kirc_20,sig_patient3_df$`rownames(sig_patient3)`),])


```


```{r plot}

common_min = min(c(sig_patient1_order,sig_patient2_order,sig_patient3_order))
common_max = max(c(sig_patient1_order,sig_patient2_order,sig_patient3_order))
col_fun = circlize::colorRamp2(c(common_min,0, common_max), c("blue","black", "red"))

Heatmap(sig_patient1_order, col = col_fun,show_heatmap_legend = F, column_title = "Cluster 1",cluster_rows = F, cluster_columns = F, column_names_gp = grid::gpar(fontsize = 0))+ Heatmap(sig_patient2_order, col = col_fun,heatmap_legend_param = list(title= "NES"),column_title = "Cluster 2", cluster_rows = F,cluster_columns = F,column_names_gp = grid::gpar(fontsize = 0)) +Heatmap(sig_patient3_order, col = col_fun, show_heatmap_legend = F,column_title = "Cluster 3", cluster_rows = F,cluster_columns = F,column_names_gp = grid::gpar(fontsize = 0))




Heatmap(am, col = col_fun,cluster_rows = FALSE, column_names_gp = gpar(fontsize=2),width = ncol(am)*unit(0.45,"mm"),height = nrow(am)*unit(2,"mm"),column_dend_height = unit(15,"mm")) + Heatmap(bm, col = col_fun,cluster_rows = FALSE, column_names_gp = gpar(fontsize=2),width = ncol(am)*unit(0.45,"mm"),height = nrow(am)*unit(2,"mm"),column_dend_height = unit(15,"mm")) +Heatmap(cm, col = col_fun,cluster_rows = FALSE, column_names_gp = gpar(fontsize=2),width = ncol(am)*unit(0.45,"mm"),height = nrow(am)*unit(2,"mm"),column_dend_height = unit(15,"mm"))


```



```{r identify cluster for all 33 tumortypes}
sig_kirc_20 = rownames(ks_sig$KIRC[1:25,])
sig_kirc = ks_sig$KIRC[1:25,]


sig_patient1= c1_patients[[12]][which(rownames(c1_patients[[12]])%in%sig_kirc_20),]
sig_patient1_df = cbind(rownames(sig_patient1),sig_patient1)
sig_patient1_order = data.matrix(sig_patient1[match(sig_kirc_20,sig_patient1_df$`rownames(sig_patient1)`),])


sig_patient2= c2_patients[[12]][which(rownames(c2_patients[[12]])%in%sig_kirc_20),]
sig_patient2_df = cbind(rownames(sig_patient2),sig_patient2)
sig_patient2_order = data.matrix(sig_patient2[match(sig_kirc_20,sig_patient2_df$`rownames(sig_patient2)`),])


sig_patient3= c3_patients[[12]][which(rownames(c3_patients[[12]])%in%sig_kirc_20),]
sig_patient3_df = cbind(rownames(sig_patient3),sig_patient3)
sig_patient3_order = data.matrix(sig_patient3[match(sig_kirc_20,sig_patient3_df$`rownames(sig_patient3)`),])



Heatmap(sig_patient1_order, col = col_fun,show_heatmap_legend = F, column_title = "Cluster 1",cluster_rows = F, cluster_columns = F, column_names_gp = grid::gpar(fontsize = 0))+ Heatmap(sig_patient2_order, col = col_fun,heatmap_legend_param = list(title= "NES"),column_title = "Cluster 2", cluster_rows = F,cluster_columns = F,column_names_gp = grid::gpar(fontsize = 0)) +Heatmap(sig_patient3_order, col = col_fun, show_heatmap_legend = F,column_title = "Cluster 3", cluster_rows = F,cluster_columns = F,column_names_gp = grid::gpar(fontsize = 0))



```

```{r peng plot}
cancer_type = list()
for (i in 1:length(TCGA_pw_PID)){
  cancer_type[[i]] = c(rep(c(cancer_abc[i]),3))
}
cancer_type = do.call("cbind", cancer_type)
View(cancer_type)
y = melt(cancer_type)
cancer_type_bind = y[,3]


Immune_type = list()
for (i in 1:length(TCGA_pw_PID)){
  Immune_type[[i]] = c("High","Neutral","Low")
}
Immune_type = do.call("cbind", Immune_type)
View(Immune_type)
x = melt(Immune_type)
Immune_type_bind = x[,3]

Immune_value = list(c(0,0,0),
                    c(ncol(c3_patients[[2]]),ncol(c2_patients[[2]]),ncol(c1_patients[[2]])),
                    c(ncol(c2_patients[[3]]),ncol(c3_patients[[3]]),ncol(c1_patients[[3]])),
                    c(ncol(c3_patients[[4]]),ncol(c1_patients[[4]]),ncol(c2_patients[[4]])),
                    c(ncol(c3_patients[[5]]),ncol(c1_patients[[5]]),ncol(c2_patients[[5]])),
                    c(ncol(c2_patients[[6]]),ncol(c3_patients[[6]]),ncol(c1_patients[[6]])),
                    c(0,0,0),
                    c(ncol(c3_patients[[8]]),ncol(c2_patients[[8]]),ncol(c1_patients[[8]])),
                    c(0,0,0),
                    c(ncol(c3_patients[[10]]),ncol(c2_patients[[10]]),ncol(c1_patients[[10]])),
                    c(0,0,0),
                    c(ncol(c1_patients[[12]]),ncol(c3_patients[[12]]),ncol(c2_patients[[12]])),
                    c(ncol(c3_patients[[13]]),ncol(c2_patients[[13]]),ncol(c1_patients[[13]])),
                    c(ncol(c3_patients[[14]]),ncol(c1_patients[[14]]),ncol(c2_patients[[14]])),
                    c(0,0,0),
                    c(0,0,0),
                    c(ncol(c1_patients[[17]]),ncol(c2_patients[[17]]),ncol(c3_patients[[17]])),
                    c(ncol(c3_patients[[18]]),ncol(c2_patients[[18]]),ncol(c1_patients[[18]])),
                    c(0,0,0),
                    c(ncol(c3_patients[[20]]),ncol(c2_patients[[20]]),ncol(c1_patients[[20]])),
                    c(ncol(c2_patients[[21]]),ncol(c1_patients[[21]]),ncol(c3_patients[[21]])),
                    c(0,0,0),
                    c(ncol(c2_patients[[23]]),ncol(c3_patients[[23]]),ncol(c1_patients[[23]])),
                    c(ncol(c3_patients[[24]]),ncol(c2_patients[[24]]),ncol(c1_patients[[24]])),
                    c(ncol(c1_patients[[25]]),ncol(c3_patients[[25]]),ncol(c2_patients[[25]])),
                    c(ncol(c2_patients[[26]]),ncol(c3_patients[[26]]),ncol(c1_patients[[26]])),  
                    c(0,0,0),
                    c(ncol(c3_patients[[28]]),ncol(c1_patients[[28]]),ncol(c2_patients[[28]])),
                    c(ncol(c2_patients[[29]]),ncol(c3_patients[[29]]),ncol(c1_patients[[29]])),
                    c(ncol(c3_patients[[30]]),ncol(c1_patients[[30]]),ncol(c2_patients[[30]])),
                    c(ncol(c3_patients[[31]]),ncol(c2_patients[[31]]),ncol(c1_patients[[31]])),
                    c(ncol(c3_patients[[32]]),ncol(c2_patients[[32]]),ncol(c1_patients[[32]])),
                    c(ncol(c3_patients[[33]]),ncol(c2_patients[[33]]),ncol(c1_patients[[33]])))
                    
             
Immune_value = do.call("cbind", Immune_value)
z = melt(Immune_value)
Immune_value_bind = as.numeric(z[,3])
class(Immune_value_bind)  

Immune_ready = data.frame(cancer_type_bind,Immune_value_bind,Immune_type_bind)
colnames(Immune_ready) = c("Cancertype","Ratio","Immunetype")


peng_plot = ggplot(Immune_ready, aes(fill = Immunetype, y = Ratio, x = Cancertype))+
  geom_bar(position="fill", stat="identity", aes(group = Cancertype)) + 
  scale_fill_manual(values = c("red","white","blue")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
labs(x = "Cancer type")


peng_plot

Neutral = Immune_ready[which(Immune_ready$Immunetype == "Neutral"),]
Neutral_sum = sum(Neutral$Ratio)
Infiltrated = Immune_ready[which(Immune_ready$Immunetype == "High"),]
Infiltrated_sum = sum(Infiltrated$Ratio)
Suppresive = Immune_ready[which(Immune_ready$Immunetype == "Low"),]
Suppresive_sum = sum(Suppresive$Ratio)

pie_prep = data.frame(c(Neutral_sum,Infiltrated_sum,Suppresive_sum),c("Neutral","High","Low"))
colnames(pie_prep) = c("Ratio","Immunetype")

ggplot(pie_prep, aes(x="", y=Ratio, fill=Immunetype)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
  scale_fill_manual(values = c("red","#D3D3D3","blue")) + 
   theme_void()


data = pie_prep

data <- data %>% 
  arrange(desc(Immunetype)) %>%
  mutate(prop = Ratio / sum(data$Ratio) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )

# Basic piechart
pie = ggplot(data, aes(x="", y=prop, fill=Immunetype)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position="none") +
  
  geom_text(aes(y = ypos, label = Immunetype), color = "white", size=6) +
  scale_fill_manual(values = c("red","#D3D3D3","blue")) 

pie_ratio = c(pie_prep$Ratio)
pie(pie_ratio, labels = c("Neutral","Infiltrated","Not infiltrated"),col = c("#D3D3D3","red","blue"), border = "white", cex = 1.3)

print(peng_plot)
peng_plot
peng = list(pie, peng_plot)
ggarrange(plotlist = peng, widths = c(2,8))


Immune_prep = list()
for (i in 1:length(TCGA_pw_PID)){
  Immune_prep[[i]] = cbind(cancer_type[[i]],Immune_value[[i]],Immune_type[[i]])
  colnames(Immune_prep[[i]]) = c("Cancertype","Frequency","Immunetype")
}
```

