
---
title: "hir clustering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

```{r data}
TCGA_pw_PID =  readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/NES_OVERALL_PID_cl.RDS")
names(TCGA_pw_PID) = cancer_abc
```


```{r data}
names(TCGA_pw_PID) = cancer_abc
for (i in 1:length(TCGA_pw_PID)){
  TG[[i]] = TCGA_pw_PID[[i]][which(rownames(TCGA_pw_PID[[i]])%in%immune),]
}
names(TG) = cancer_abc
TCGA_pw_PID = TG
View(TCGA_pw_PID)
pid_names = rownames(TCGA_pw_PID$ACC)
```

```{r packages}
library(ComplexHeatmap)
```

```{r}
#compute dist matrix 

dist_list = list()
for (i in 1:length(TCGA_pw_PID)){
  x = TCGA_pw_PID[[i]]
  dist_list[[i]] = dist(t(x))
}

hclust_list = list()
for (i in 1:length(TCGA_pw_PID)){
  y = dist_list[[i]]
  hclust_list[[i]] = hclust(y, method = "ward.D2")
}
ggdendrogram(hclust_list[[12]], method = "ward.D2")

cut_list = list()
for (i in 1:length(TCGA_pw_PID)){
  v = hclust_list[[i]]
  cut_list[[i]] = (cutree(v, k = 3))
}

cutcut_list = list()
for (i in 1:length(TCGA_pw_PID)){
  cutcut_list[[i]] = as.numeric(cut_list[[i]])
}

cluster1_list =  list()
for (i in 1:length(TCGA_pw_PID)){
b = cut_list[[i]]
a = cutcut_list[[i]]
cluster1_list[[i]] = names(b[which(a == 1)])
}

cluster2_list =  list()
for (i in 1:length(TCGA_pw_PID)){
b = cut_list[[i]]
a = cutcut_list[[i]]
cluster2_list[[i]] = names(b[which(a == 2)])
}

cluster3_list =  list()
for (i in 1:length(TCGA_pw_PID)){
b = cut_list[[i]]
a = cutcut_list[[i]]
cluster3_list[[i]] = names(b[which(a == 3)])
}

c1_patients = list()
for (i in 1:length(TCGA_pw_PID)){
n = TCGA_pw_PID[[i]]
c1_patients[[i]] = n[,which(colnames(n)%in%cluster1_list[[i]])]
}
kirki = c1_patients[[12]]
intersect(colnames(kirki),colnames(c1_patients_konly))


c2_patients = list()
for (i in 1:length(TCGA_pw_PID)){
n = TCGA_pw_PID[[i]]
c2_patients[[i]] = n[,which(colnames(n)%in%cluster2_list[[i]])]
}

c3_patients = list()
for (i in 1:length(TCGA_pw_PID)){
n = TCGA_pw_PID[[i]]
c3_patients[[i]] = n[,which(colnames(n)%in%cluster3_list[[i]])]
}
```

```{r h test over all}
##H-test 
H1_cluster = list()
for (i in 1:length(TCGA_pw_PID)){
d = c1_patients[[i]]
H1_cluster[[i]] = c(rep(c(1),times = ncol(d)))
}


H2_cluster = list()
for (i in 1:length(TCGA_pw_PID)){
f = c2_patients[[i]]
H2_cluster[[i]] = c(rep(c(2),times = ncol(f)))
}

H3_cluster = list()
for (i in 1:length(TCGA_pw_PID)){
m = c3_patients[[i]]
H3_cluster[[i]] = c(rep(c(3),times = ncol(m)))
}

H123 = list()
for (i in 1:length(TCGA_pw_PID)){
g = H1_cluster[[i]]
j = H2_cluster[[i]]
k = H3_cluster[[i]]
H123[[i]] = c(g,j,k)
}

H_prep = list()
for (i in 1:length(TCGA_pw_PID)){
l = c1_patients[[i]]
p = c2_patients[[i]]
u = c3_patients[[i]]
H_prep[[i]] = cbind(l,p,u)
}

H_tot = list()
for (i in 1:length(TCGA_pw_PID)){
t = H_prep[[i]]
h = H123[[i]]
H_tot[[i]] = data.frame(rbind(t,h))
}

ks_pvlist = list()
ks = c()
for (i in 1:length(TCGA_pw_PID)){
  for(j in 1:nrow(TCGA_pw_PID[[12]])){
    t = H_tot[[i]]
    v = as.numeric(t[j,])
    q = as.numeric(t[39,])
    ks[j] = kruskal.test(v,q)$p.value
    ks_pvlist[[i]] = ks
  }
}
View(ks_pvlist)

for (i in 1:length(TCGA_pw_PID)){
  ks_pvlist[[i]] = as.data.frame(ks_pvlist[[i]])
  rownames(ks_pvlist[[i]]) = pid_names
  colnames(ks_pvlist[[i]]) = c("pvalue")
}

cutoff = 0.05 / length(pid_names)

for (i in 1:length(TCGA_pw_PID)){
  ks_pvlist[[i]]$pvalue[which(is.nan(ks_pvlist[[i]]$pvalue))] = 1
}
names(ks_pvlist) = cancer_abc
```



```{r pvalue cutoff and reordering}
pv_log = list()
for (i in 1:length(ks_pvlist)){
  h = ks_pvlist[[i]]$pvalue
  pv_log[[i]] = data.frame( -log10(h))
}
for (i in 1:length(TCGA_pw_PID)){
  rownames(pv_log[[i]]) = pid_names
  colnames(pv_log[[i]]) = c("neg_log10_pv")
}
for (i in 1:length(TCGA_pw_PID)){
  pv_log[[i]][pv_log[[i]] == Inf] = 0
}
logcut = -log10(cutoff)

ks_pv_log = list()
for (i in 1:length(TCGA_pw_PID)){
  ks_pv_log[[i]] = cbind(pv_log[[i]],pid_names)
  colnames(ks_pv_log[[i]]) = c("neg_log_pv", "pathways")
}
names(ks_pv_log) = cancer_abc

ks_sig= list()
for (i in 1:length(TCGA_pw_PID)){
  g = ks_pv_log[[i]]
  ks_sig[[i]] = g[which(g$neg_log_pv>logcut),]
}

for (i in 1:length(TCGA_pw_PID)){
  g = ks_sig[[i]]
  ks_sig[[i]] = g[order(g$neg_log_pv,decreasing = TRUE),]
}
names(ks_sig) = cancer_abc
View(ks_sig$KIRC)
sig_kirc_20 = rownames(ks_sig$KIRC[1:20,])
sig_kirc = ks_sig$KIRC[1:20,]

```


```{r}
sig_kirc_20 = rownames(ks_sig$KIRC[1:20,])
sig_kirc = ks_sig$KIRC[1:20,]


sig_patient1= c1_patients[[12]][which(rownames(c1_patients[[12]])%in%sig_kirc_20),]
sig_patient1_df = cbind(rownames(sig_patient1),sig_patient1)
sig_patient1_order = data.matrix(sig_patient1[match(sig_kirc_20,sig_patient1_df$`rownames(sig_patient1)`),])


sig_patient2= c2_patients[[12]][which(rownames(c2_patients[[12]])%in%sig_kirc_20),]
sig_patient2_df = cbind(rownames(sig_patient2),sig_patient2)
sig_patient2_order = data.matrix(sig_patient2[match(sig_kirc_20,sig_patient2_df$`rownames(sig_patient2)`),])


sig_patient3= c3_patients[[1]][which(rownames(c3_patients[[1]])%in%sig_kirc_20),]
sig_patient3_df = cbind(rownames(sig_patient3),sig_patient3)
sig_patient3_order = data.matrix(sig_patient3[match(sig_kirc_20,sig_patient3_df$`rownames(sig_patient3)`),])



Heatmap(sig_patient1_order, col = col_fun,show_heatmap_legend = F, column_title = "Cluster 1",cluster_rows = F, cluster_columns = F, column_names_gp = grid::gpar(fontsize = 0))+ Heatmap(sig_patient2_order, col = col_fun,heatmap_legend_param = list(title= "NES"),column_title = "Cluster 2", cluster_rows = F,cluster_columns = F,column_names_gp = grid::gpar(fontsize = 0)) +Heatmap(sig_patient3_order, col = col_fun, show_heatmap_legend = F,column_title = "Cluster 3", cluster_rows = F,cluster_columns = F,column_names_gp = grid::gpar(fontsize = 0))

```


```{r}
a = Heatmap(c1_patients[[1]])
b = Heatmap(c2_patients[[1]])
c = Heatmap(c3_patients[[1]])

hlist = a+b+c
draw(hlist)
a
b
c
Heatmap(k, cluster_rows = FALSE, column_names_gp = gpar(fontsize=2),width = ncol(k)*unit(0.45,"mm"),height = nrow(k)*unit(2,"mm"),column_dend_height = unit(15,"mm"),column_km = 3)

Heatmap(k,column_split = 3)

dend = as.dendrogram(hclust(dist(k), method = "ward.D2"))
Heatmap(k,cluster_rows = dend, column_split = 3)



```


```{r}
kirc_sig =  k[which(rownames(k)%in%rownames(ks_sig)),]
View(kirc_sig)

Heatmap(k, cluster_rows = FALSE, column_names_gp = gpar(fontsize=2),width = ncol(k)*unit(0.45,"mm"),height = nrow(k)*unit(2,"mm"),column_dend_height = unit(15,"mm"),column_split  = 3)

c1_patients1 = kirc_sig[,which(colnames(kirc_sig)%in%c1)]
c2_patients1 = kirc_sig[,which(colnames(kirc_sig)%in%c2)]
c3_patients1 = kirc_sig[,which(colnames(kirc_sig)%in%c3)]

f = Heatmap(as.matrix(c1_patients1))
g = Heatmap(as.matrix(c2_patients1))
h = Heatmap(as.matrix(c3_patients1))

f
g
h


klist = f+g+h
draw(klist)

```