---
title: "Venn_Diagram_Anna"
author: "Anna von Bachmann"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

```{r}
#load data
tcga_exp_cleaned <- readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_exp_cleaned.RDS")
KIRC_PID_cl <- readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_PID_cl.RDS")
```

```{r}
library(msigdbr)
## load KEGG genesets ##
KEGG = msigdbr(species = "Homo sapiens", category = "C2", subcategory  = "CP:KEGG")

KEGG_gsname = KEGG$gs_name
KEGG_ensembl = KEGG$ensembl_gene
KEGG = as.data.frame(cbind(KEGG_gsname, KEGG_ensembl))

pathway_names_KEGG = c(unique(KEGG$KEGG_gsname))
#create a list in which the pathways will be stored (outout has to be a list)
metabolic_genesets_KEGG = list(list())
#fill the list with pathways and genes
for (x in 1:length(pathway_names_KEGG)){
  metabolic_genesets_KEGG[[x]] = pathway_names_KEGG[x]
  z = c((KEGG[which(KEGG$KEGG_gsname == pathway_names_KEGG[x]),2]))
  for (k in 1:length(z)){
  metabolic_genesets_KEGG[[x]][[k]] = z[k]
  }}
names(metabolic_genesets_KEGG) = pathway_names_KEGG
```

```{r}
##load PID genset##
PID_genesets <- readRDS("~/GitHub/2022-topic-02-team-02/data/PID_genesets.RDS")
#work with PID_cl and tcga_Cl
#Clean PID data
PID_filtered = c(rownames(KIRC_PID_cl)) #KIRC_PID_cl is data frame without PW with constant NES-->constant NES over all patients is not interesting for clustering
whichi = which(names(PID_genesets) %in% PID_filtered)
metabolic_genesets_PID_cl = PID_genesets[c(whichi)] #cleaned PID PW
length(metabolic_genesets_PID_cl)#should be 88
```

```{r}
#hallmarks gene set
hallmarks = msigdbr(species = "Homo sapiens", category = "H")
hallmarks_gsname = hallmarks$gs_name
hallmarks_ensembl = hallmarks$ensembl_gene
hallmarks = as.data.frame(cbind(hallmarks_gsname, hallmarks_ensembl))
#create a df with names of pathways
hallmarks_pathway_names = c(unique(hallmarks$hallmarks_gsname))
#create a list in which the pathways will be stored (outout has to be a list)
hallmark_genesets = list(list())#
#fill the list with pathways and genes
for (x in 1:length(hallmarks_pathway_names)){
  hallmark_genesets[[x]] = hallmarks_pathway_names[x]
  z = c((hallmarks[which(hallmarks$hallmarks_gsname == hallmarks_pathway_names[x]),2]))
  for (k in 1:length(z)){
  hallmark_genesets[[x]][[k]] = z[k]
  }}
names(hallmark_genesets) = hallmarks_pathway_names
```

#for the genesets we worked with (clenaed data)

```{r}

PID_cl_genes=unlist(metabolic_genesets_PID_cl)
PID_cl_genes=unique(PID_cl_genes)

KEGG_genes=unlist(metabolic_genesets_KEGG)
KEGG_genes=unique(KEGG_genes)

hallmarks_genes=unlist(hallmark_genesets)
hallmarks_genes=unique(hallmarks_genes)

tcga_cl_genes = rownames(tcga_exp_cleaned)

```

```{r}
#install package if not done yet
#if (!require(devtools)) install.packages("devetools")
#devtools::install_github("yanlinlin82/ggvenn")
library(ggvenn)
```

```{r}
#create a list with the genesets that will be compared
genesets_cl = list(KEGG_genes, PID_cl_genes, tcga_cl_genes, hallmarks_genes)
names(genesets_cl) = c("KEGG", "PID_cl", "tcga_cl", "hallmarks")
ggvenn(
  genesets_cl, 
  fill_color = c("orange", "lightblue", "lightgrey", "lightgreen"),
  stroke_size = 0.5, set_name_size = 4
  )

genesets_cl_KEGG_PID_tcga = list(KEGG_genes, PID_cl_genes, tcga_cl_genes)#only KEGG, PID, tcga
names(genesets_cl_KEGG_PID_tcga) = c("KEGG", "PID_cl", "tcga_cl")
ggvenn(
  genesets_cl_KEGG_PID_tcga, 
  fill_color = c("orange", "lightblue", "lightgrey", "lightgreen"),
  stroke_size = 0.5, set_name_size = 4
  )


genesets_cl_PID_tcga =list(PID_cl_genes, tcga_cl_genes)
names(genesets_cl_PID_tcga)=c("PID_cl", "tcga_cl")#only PID, tcga
ggvenn(
  genesets_cl_PID_tcga,
  fill_color = c("lightblue", "lightgrey"),
  stroke_size = 0.5, set_name_size = 4
  )

genesets_cl_KEGG_PID = list(KEGG_genes, PID_cl_genes)#only KEGG, PID
names(genesets_cl_KEGG_PID) = c("KEGG", "PID_cl")
ggvenn(
  genesets_cl_KEGG_PID, 
  fill_color = c("orange", "lightblue", "lightgrey", "lightgreen"),
  stroke_size = 0.5, set_name_size = 4
  )
```
#for the uncleaned data
