---
title: "Gene sets"
author: "Maja Glotz"
date: "5/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(msigdbr)
library(biomaRt)
library(GeneOverlap)
library(ggplot2)
```

```{r}
#load data
genesets = readRDS("../data/hallmarks_genesets.rds")
PENG_pathways = readRDS("../data/PENG_pathways.rds")
```

```{r check jaccard index for PID}
#create GeneOverlap matrix for PID pathways:
go_PID_matrix_new = newGOM(metabolic_genesets_PID_cl, metabolic_genesets_PID_cl)
go_PID_jaccard_new = getMatrix(go_PID_matrix_new, "Jaccard")
diag(go_PID_jaccard_new) = 0
heatmap(go_PID_jaccard_new, Rowv = NA, Colv = NA, margins = c(8,8))
Heatmap(go_PID_jaccard_new, name = "mat", cluster_rows = FALSE, cluster_columns = FALSE, column_names_gp = gpar(fontsize = 5), row_names_gp = gpar(fontsize = 5))
```

```{r check jaccard index for KEGG pathways}
go_KEGG_matrix = newGOM(metabolic_genesets_KEGG, metabolic_genesets_KEGG)
go_KEGG_jaccard = getMatrix(go_KEGG_matrix, "Jaccard")
diag(go_KEGG_jaccard) = 0
go_KEGG_jaccard = na.omit(go_KEGG_jaccard)
heatmap(go_KEGG_jaccard, Rowv = NA, Colv = NA, margins = c(14,14))
heatmap.2(go_KEGG_jaccard, dendrogram = "none", trace = "none", margins = c(11,11))
go_KEGG_jaccard = na.omit(go_KEGG_jaccard)
```

```{r Jaccard index for ALL used pathways}
#hallmarks, KEGG, PID, MMR, PENG
all_genesets = c(metabolic_genesets_H, metabolic_genesets_KEGG, metabolic_genesets_PID_cl, MMR, PENG_pathways)
#compute jaccard index
go_matrix_alle = newGOM(all_genesets, all_genesets)
go_jaccard_alle = getMatrix(go_matrix_alle, "Jaccard")
diag(go_jaccard_alle) = 0
heatmap(go_jaccard_alle, Rowv = NA, Colv = NA)

Heatmap(go_jaccard_alle, name = "mat", cluster_rows = FALSE, cluster_columns = FALSE, column_names_gp = gpar(fontsize = 2), row_names_gp = gpar(fontsize = 2))
```

