---
title: "Vioplot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

```{r}
#remove last 3 characters, run ONLY once!

#tcga_exp_protein_coding_new = c(substr(colnames(tcga_exp_protein_coding),1, #nchar(colnames(tcga_exp_protein_coding))-3))
#colnames(tcga_exp_protein_coding) = tcga_exp_protein_coding_new

#dim(tcga_exp_protein_coding)
#summary(tcga_exp_protein_coding)

tcga_prc_var = apply(tcga_exp_protein_coding, 1, var)
```


```{r}
#create violin plot of uncleaned data
tcga_prc_var_df = data.frame(tcga_prc_var)
#class(tcga_prc_var_df)

tcga_prc_var_p50 = quantile(tcga_prc_var, 0.5) # use as threshold =2.13 --> cuts out half of the genes (19566 --> 9783)

violin = ggplot(tcga_prc_var_df, aes(tcga_prc_var,y=1))+
  geom_violin() + ylab ("") + xlab ("variance") +
  geom_vline(xintercept = tcga_prc_var_p50, color = "blue") +
  annotate("text", x = 10, y=1.4, label = "p50-quantile", color = "blue")

#create violin plot of data w/o low variance genes
tcga_exp_prc_clean = tcga_exp_protein_coding[-which(tcga_prc_var<= tcga_prc_var_p50),] #--> 9783 genes

tcga_exp_prc_clean_var = apply(tcga_exp_prc_clean, 1, var)
tcga_exp_prc_clean_var_df = data.frame(tcga_exp_prc_clean_var)

violin_clean = ggplot(tcga_exp_prc_clean_var_df, aes(tcga_exp_prc_clean_var,y=1))+
  geom_violin() + ylab ("") + xlab ("variance") +
  geom_vline(xintercept = tcga_prc_var_p50, color = "blue") +
  annotate("text", x = 10, y=1.4, label = "p50-quantile", color = "blue")
violin_clean
```


```{r}
#plot data before and after cleaning (only var<q50) next to each other
library(reshape2)
melting = cbind(tcga_prc_var_df, tcga_exp_prc_clean_var_df)
#rename columns to get the right annotation
colnames(melting) = c("Gene expression", "Gene expression after cleaning")

melting2 =melt(melting)

update_geom_defaults("point",list(size=0.00003))

violin_combined = ggplot(melting2, aes(x = variable,y=value))+
  geom_violin() + ylab ("variance") + xlab ("") + 
  geom_hline(yintercept = tcga_prc_var_p50, color = "blue") +
  annotate("text", x = 2.4, y=4.4, label = "p50-quantile", color = "blue") + #add p50-quantile 
  geom_boxplot(width=0.05, color = "black") + geom_point() +
  ggtitle("Variance Distribution") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_summary(fun=median, geom="point", size=2, color="orange")  #add median
  #stat_summary(fun.data=mean_sdl, mult=1, geom="pointrange", color="red")
  
violin_combined
```







