---
title: "Biomart"
author: "Maja Glotz"
date: "5/10/2022"
output: html_document
---

```{r}
library(biomaRt)
```

```{r}
directory = "/Users/majaglotz/Uni/Data Analysis/Datensätze/genes.rds"
  
genes <- readRDS(directory)

#-----------------------------------------------------------#
# Split ENSG identifier from Gene Symbol
#-----------------------------------------------------------#

gene_identifier <- strsplit(genes, split = "|", fixed = TRUE)

genes_ens<- sapply(gene_identifier, FUN = function(gene_identifier){
  ens = gene_identifier[1]
  return(ens)
})

genes_symbol<- sapply(gene_identifier, FUN = function(gene_identifier){
  ens = gene_identifier[2]
  return(ens)
})

# remove version number

genes_ens_vn <- strsplit(genes_ens, split = ".", fixed = TRUE)
genes_ensembl <- sapply(genes_ens_vn, FUN = function(genes_ens_vn){
  ens = genes_ens_vn[1]
  return(ens)
})

#-----------------------------------------------------------#
# Biomart Action
#-----------------------------------------------------------#

mart = useEnsembl(dataset = "hsapiens_gene_ensembl", biomart='ensembl')

list_biotype = getBM(attributes = c("ensembl_gene_id", "gene_biotype"), filters = "ensembl_gene_id", 
                                    values = genes_ensembl, mart = mart, useCache = FALSE)



```

