---
title: "KIRC_Pathway_activity_PCA_Anna"
author: "Anna von Bachmann"
date: '2022-06-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Load data}
#Load data
tcga_tumor_norm = readRDS("~/GitHub/2022-topic-02-team-02/data/tcga_tumor_normal_datascience_proj_2022.RDS")
KIRC_annot = data.frame(tcga_tumor_norm[["KIRC"]][["clinical"]]) #annotation

KIRC_pa =  readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity.rds")

#depending on which pathways you want to analyze, assign the variable accordingly
#KIRC_GSEA_activity_PID <- readRDS("~/GitHub/2022-topic-02-team-02/data/KIRC_GSEA_activity_PID.rds")
KIRC_pa = KIRC_GSEA_activity_PID
#KIRC_pa = KIRC_GSEA_activity_hallmark
#KIRC_pa = KIRC_GSEA_activity_KEGG
```


```{r PCA}
#run pca 
KIRC_pa_pca = prcomp(t(KIRC_pa))#center = F, scale. = F???
length(KIRC_pa_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_pa_pca_x = data.frame(KIRC_pa_pca[["x"]])

#get the eigenvalues for each PC (eigenvalues measure the amount of variation retained by each PC)
library("factoextra")
KIRC_pa_pca_eigval = get_eigenvalue(KIRC_pa_pca)
rownames(KIRC_pa_pca_eigval) = colnames (KIRC_pa_pca_x)
barplot(KIRC_pa_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")
```


```{r PCA plot}
#plot the data (patients in coordinate system with PC1, PC2/PC3 as axes)

ggplot(KIRC_pa_pca_x, aes(PC1, PC2))+  #plot PC1 and PC2
  geom_point( size =2)

ggplot(KIRC_pa_pca_x, aes(PC1, PC3))+   #plot in PC1  and PC3
  geom_point( size =2)
  

#plot the data (patients) in the first principal components regarding gender
KIRC_gender = ifelse(KIRC_annot$gender == "FEMALE", "red", "blue")#gender-vector
sum(KIRC_annot$gender=="FEMALE")

ggplot(KIRC_pa_pca_x, aes(PC1, PC2))+  #plot PC1 and pC2
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")

ggplot(KIRC_pa_pca_x, aes(PC1, PC3))+
  geom_point( size =2, color = KIRC_gender)+
   ggtitle("PCA with regard to gender ")
```
```{r UMAP}
#UMAP for better clusterin/visualization, running on PCA result
library(uwot)
KIRC_pa_UMAP= uwot::umap(KIRC_pa_pca_x)
KIRC_pa_UMAP = data.frame(KIRC_pa_UMAP)
#plot
ggplot (data = KIRC_pa_UMAP, 
                    aes(x = X1, y = X2))+
  geom_point(size = 2)

#plot with colors for gender

KIRC_tumorstatus = KIRC_annot$tumor_status
KIRC_gender_Umap = KIRC_annot$gender  #vector for coloring 
KIRC_pa_UMAP = data.frame(KIRC_pa_UMAP)

ggplot (data =KIRC_pa_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_tumorstatus))+
  geom_point(size = 1)

ggplot (data =KIRC_pa_UMAP, 
                    aes(x = X1, y = X2 , color = KIRC_gender_Umap))+
  geom_point(size = 1)
```


```{r Kmeans }
library(cluster)
#perform kmeans with 2:5 centers on UMAP results
KIRC_UMAP_kmeans = sapply(2:5, function(k){
  kmeans(x = KIRC_pa_UMAP , centers = k, nstart = 50 )})



#find the optimal number of clusters

#extract tot.withinss --> for silhouette plot (elbow method)
KIRC_UMAP_kmeans_tw = sapply(1:5, function(k){
  kmeans(x = KIRC_pa_UMAP , centers = k, nstart = 50 )$tot.withinss})

#elbow plot
plot(KIRC_UMAP_kmeans_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#extract cluster values for silhouette plot
KIRC_UMAP_kmeans_c = sapply(2:7, function(k){
  kmeans(x = KIRC_pa_UMAP , centers = k, nstart = 50 )$cluster})

#silhouette plot
sapply(1:6, function(x){
  plot(silhouette(KIRC_UMAP_kmeans_c[,x], dist(KIRC_pa_UMAP)), main ="Silhouette plot")})


#find the optimal number clusters, silhouette plot (average silhouette width)
fviz_nbclust(KIRC_pa_UMAP, kmeans, method='silhouette')
```
```{r Kmeans Plot}
# visualize the clusters in plot
library(ggpubr)
library(factoextra)
#for 2 centers
km.2 = kmeans(KIRC_pa_UMAP, centers = 2, nstart = 200)
fviz_cluster(km.2, KIRC_pa_UMAP,
             palette = c("orange", "blue"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 3 centers
km.3 = kmeans(KIRC_pa_UMAP, centers = 3, nstart = 50)
fviz_cluster(km.3, KIRC_pa_UMAP,
             palette = c("orange", "blue", "forestgreen"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

# for 4 centers
km.4 = kmeans(KIRC_pa_UMAP, centers = 4, nstart = 50)
fviz_cluster(km.4, KIRC_pa_UMAP,
             palette = c("orange", "blue", "forestgreen", "black"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

```


```{r}
#for PID pathways: optimal number ckusters = 2
PID_km2 =kmeans(KIRC_pa_UMAP, 2 ,nstart = 50)
PID_km = PID_km2$cluster
PID_c1_names = names(PID_km[which(PID_km == 1)]) #patient names of cluster1
PID_c2_names = names(PID_km[which(PID_km == 2)]) # patient names of cluster2
fviz_cluster(PID_km2, KIRC_pa_UMAP,
             palette = c("orange", "blue"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )


PID_c1 = KIRC_pa[,colnames(KIRC_pa) %in% PID_c1_names] # df with patients of cluster1
PID_c2 = KIRC_pa[,!colnames(KIRC_pa) %in% PID_c1_names] #df with patients cluster 2
PID_c1_mean = data.frame(apply(PID_c1, 1,mean)) #pw activity mean for patients of cluster 1
PID_c2_mean = data.frame (apply (PID_c2, 1, mean)) #fpr cluster 2
PID_c1_c2 = cbind(PID_c2_mean, PID_c1_mean) #combine mean cluster 1 and cluster2 
PID_c1_c2_dif = PID_c1_mean - PID_c2_mean #compare the mean activity scores of pathways
#high scores means upregulated in cluster 1 

#rank the compared pw-matrix to see the most differently expressed pw
PID_c1_c2_dif_rank = data.frame(PID_c1_c2_dif$apply.PID_c1..1..mean.[order(PID_c1_c2_dif[,1],decreasing = TRUE)])
PID_rownames = c(rownames(PID_c1_c2_dif))
PID_rownames_rank = c(PID_rownames[order(PID_c1_c2_dif[,1],decreasing = TRUE)])

PID_c1_c2_dif_rank = as.data.frame(cbind(PID_rownames_rank, PID_c1_c2_dif_rank))
colnames(PID_c1_c2_dif_rank) = c("Pathway", "diff")

  
ggplot(PID_c1_c2_dif_rank, aes(x=reorder(Pathway,diff), y=diff)) +
  geom_bar(stat="identity")+
  coord_flip()
       
#PID_c1_c2_dif_rank %>%
#  filter(PID_c1_c2_dif_rank$diff!=0) %>%
#ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
 # geom_bar(stat="identity")+
  #coord_flip()
  

#PID_c1_c2_dif_rank%>%
 # filter(abs(PID_c1_c2_dif_rank$dif)>0.20)%>%
#ggplot( aes(x=reorder(Pathway,diff), y=diff)) +
#  geom_bar(stat="identity")+
#  coord_flip()
```

```{r}
#working with FC and not with difference (minus)
PID_c1_c2_FC = data.matrix(PID_c1_mean/PID_c2_mean)
colnames(PID_c1_c2_FC) = "FC"
PID_c1_c2_FC[is.nan(PID_c1_c2_FC)]=0
#PROBLEM: what to do with INF??? (because of e.g. 0.1/0)

#work with wilcoxon test as some of the pw have an enrichment score of zero for all patients, thus no normality, as shown below
PID_c1_min = apply(PID_c1, 1, min)
PID_c1_max = apply(PID_c1, 1, max) 
PID_c1_constant = c(names(which(PID_c1_min==PID_c1_max)))
length(PID_constant)#there are 271 pw with constant NES, hence we use wilcoxon test 


#perform wilcoxon test (unpaired) to see if there is a sign difference in NES between the clusters
PID_c1_m = as.matrix(PID_c1) #matrix needed for wilcoxon
PID_c2_m = as.matrix(PID_c2)
PID_wilcox_pv  = data.matrix(sapply ( 1:nrow(PID_c1_m),function (x) {
  wilcox.test(PID_c1_m[x,],PID_c2_m[x,],paired=FALSE)
}$p.value))
rownames(PID_wilcox_pv)=rownames(PID_c1)
colnames(PID_wilcox_pv)="pvalue"
#a lot of NaNs--> Maybe because of constant NES??

#Bonferroni-Korrektur
alpha=0.05/(nrow(PID_wilcox_pv))#0.000255102
#how many pathways have sign different NES??
length(which(PID_wilcox_pv<alpha))#118


PID_wilcox_pv[is.nan(PID_wilcox_pv)] = 1
```

```{r Volcano Plot}
#data preparation for Volcano Plot

#problem with FC as there are a lot of Inf(if e.g. 0.1/0)--> what to do with those??
#NaNs in FC can be converted to zero because 0/0=0
#thus not the FC value data is used but the difference (minus)
#calculate -log10 of p-value for plotting
PID_wilcox_pv_log =-log10(PID_wilcox_pv)
colnames(PID_wilcox_pv_log) = "neg_log10_pv"
PID_wilcox_pv_log [PID_wilcox_pv_log  == Inf] <- 0

#combine FC and pv matrix
PID_pv_dif =as.data.frame(cbind(PID_c1_c2_dif,PID_wilcox_pv_log))
colnames(PID_pv_dif) = c("diff","neg_log10_pv")



#extracting sign differently expressed genes (pvalue > cutoff), for coloring in volcano plot ---> will later be orange
cutoffpv = -log10(alpha)#=3.593286, cut off later in plot 
PID_pv_dif_sig = PID_pv_dif[which(PID_pv_dif$neg_log10_pv>cutoffpv),]
min(PID_pv_dif_sig$neg_log10_pv)
#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_pv_dif_sigup = PID_pv_dif_sig[which(PID_pv_dif_sig$diff>0),]

#volcano plot, there are no sign downregulated pw
library(ggplot2)
#plotting
ggplot(PID_pv_dif, aes(diff ,neg_log10_pv, color = "non-significant"))+
  geom_point( size =0.3)+
  geom_point(data= PID_pv_dif_sig, aes(diff , neg_log10_pv, color = "lower NES"), size=0.3, color = "orange")+
  geom_point(data = PID_pv_dif_sigup, aes(diff,neg_log10_pv, color = "higher NES"), size=0.3, color = "blue")+
  ggtitle("gene expression normal vs tumor tissue ")+
  xlab ("mean(c1)-mean(c2)")+
  ylab ("-log10(p-value)")+
  scale_color_manual(name="", breaks=c("lower NES", "non-significant", "higher NES"),
                     values=c("lower NES" = "orange", "non-significant" = "black", "higher NES" = "blue"))+
  guides(colour = guide_legend(override.aes = list(size=3)))

```





