---
title: "PCA_UMAP_pathway_activity"
author: "Linda Blaier"
date: '2022-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#PCA and UMAP over mean pathway activity matrix for PID 

#NES_mean_PID = readRDS("../data/NES_mean_PID.RDS")

PCA_NES_PID_mean = RunPCA(as.matrix(NES_mean_PID), npcs = 32)
UMAP_NES_PID_mean = uwot::umap(PCA_NES_PID_mean@cell.embeddings)
                               
UMAP_NES_PID_plot_mean = ggplot (data = data.frame(UMAP_NES_PID_mean), aes (x = X1, y = X2, color = cancer_names)) + 
  geom_point(size = 2)

UMAP_NES_PID_plot_mean

```
```{r}#
PCA_NES_PID = prcomp(t(NES_OVERALL_PID_alle))
PCA_NES_PID_x =PCA_NES_PID[["x"]] #PCA

PCA_NES_PID_plot = ggplot(data = as.data.frame(PCA_NES_PID_x), aes (x = PC1, y = PC3))+
  geom_point (size = 0.5)
PCA_NES_PID_plot

UMAP_NES_PID = uwot::umap(PCA_NES_PID_x) # -> komisches Muster

UMAP_NES_PID = data.frame(UMAP_NES_PID)
UMAP_NES_PID_plot = ggplot (data = (UMAP_NES_PID), aes (x = X1, y = X2)) + geom_point(size = 2)

UMAP_NES_PID_plot

UMAP_NES_PID_wo = uwot::umap(t(NES_OVERALL_PID_alle))
UMAP_NES_PID_plot_patterned = ggplot (data = data.frame(UMAP_NES_PID_wo), aes (x = X1, y = X2)) + 
  geom_point(size = 2)
UMAP_NES_PID_plot_patterned #-> komisches Muster
```


```{r}
NES_OVERALL_PID_alle <-  readRDS("~/GitHub/2022-topic-02-team-02/data/NES_OVERALL_PID_alle.RDS")

#nochmal richtig programmieren
RunPCA_NES_PID = RunPCA(as.matrix(NES_OVERALL_PID_alle))
UMAP_NES_PID_right = umap(RunPCA_NES_PID@cell.embeddings)
UMAP_NES_PID_right_l = UMAP_NES_PID_right[["layout"]]
UMAP_NES_PID_right_plot = ggplot (data = data.frame(UMAP_NES_PID_right_l), 
                                  aes (x = X1, y = X2)) +
  geom_point(size = 0.5)
UMAP_NES_PID_right_plot

UMAP_NES_PID_names = rownames (UMAP_NES_PID_right_l)
UMAP_NES_PID_names_split = strsplit(UMAP_NES_PID_names, split = ".", fixed = TRUE)

})
View(xy)
UMAP_PID_names_vector = xy

#-> Vektor mit Namen
UMAP_PID_names_vector = unlist(strsplit(UMAP_NES_PID_names, split = ".", fixed = TRUE))

UMAP_PID_cancer = UMAP_PID_names_vector[c(TRUE, FALSE)]

UMAP_PID_patients = UMAP_PID_names_vector[c(FALSE, TRUE)]

#create data frame with V1 and v2 of UMAP_NES_PID_right_l and UMAP_PID_cancer and UMAP_PID_patients

UMAP_PID_V1 = as.vector(UMAP_NES_PID_right_l[,1])
UMAP_PID_V2 = as.vector(UMAP_NES_PID_right_l[,2])
UMAP_PID = data.frame (UMAP_PID_cancer, UMAP_PID_patients, UMAP_PID_V1, UMAP_PID_V2)

UMAP_PID_plot = ggplot(data = data.frame(UMAP_PID), aes (x = UMAP_PID_V1, y = UMAP_PID_V2, color = UMAP_PID_cancer)) + 
  geom_point(size = 0.5)
UMAP_PID_plot

UMAP_NES_PID_right_plot = ggplot (data = data.frame(UMAP_NES_PID_right_l), 
                                  aes (x = X1, y = X2)) +
  geom_point(size = 0.5)


#einfärben: bis inklusive Punkt die Namen der Patienten (rows) entfernen und dann einfärben über Annotationen


```

```{r}
#find optimal cluster number
library(ggpubr)
library(factoextra)

km_UMAP_PID = kmeans(UMAP_NES_PID_right_l, centers= 2, nstart = 50)

fviz_cluster(km_UMAP_PID, data.frame(UMAP_NES_PID_right_l),
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

km_UMAP_PID_20 = kmeans (UMAP_NES_PID_right_l, centers = 20, nstart = 50)

#elbow plot
km_UMAP_PID_tw = sapply(1:20, function(k){
  kmeans(x = UMAP_NES_PID_right_l, centers = k, nstart = 50 )$tot.withinss})

UMAP_PID_elbow = plot(km_UMAP_PID_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#silhouette plot
km_UMAP_PID_20 = sapply(2:20, function(k){
  kmeans(x = UMAP_NES_PID_right_l , centers = k, nstart = 50 )$cluster})

#silhouette plot
sapply(1:10, function(x){
  plot(silhouette(km_UMAP_PID_20[,x], dist(data.frame(UMAP_NES_PID_right_l)), main ="Silhouette plot")}) #kp wieso das nicht klappt...
  
#find the optimal number clusters, silhouette plot (average silhouette width)
library(cluster)
fviz_nbclust(UMAP_NES_PID_right_l, kmeans, method='silhouette') #-> opt. cluster = 2
```

```{r}
#Untersuchen der Clusterzugehörigkeit der Tumortypen
#1. nur Betrachtung von 2 Clustern

km_UMAP_annot = data.frame (UMAP_PID_cancer, UMAP_PID_patients, (km_UMAP_PID_20[,1:19]))

km_UMAP_2 = data.frame(UMAP_PID_cancer, UMAP_PID_patients, km_UMAP_annot$X1)

```

