---
title: "PCA_pan_cancer"
author: "Linda Blaier"
date: '2022-05-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

```{r}
# run Biotypes.Rmd to load data needed for this markdown
# work with tcga_exp_prc_clean -> w/o low variable under p50
#dim (tcga_exp_prc_clean)
#tcga_exp_pca = prcomp (t(tcga_exp_prc_clean), center = F, scale. = F)
#pca_var = tcga_exp_pca$sdev^2
#proportion_pca_var = pca_var/sum(pca_var)
#names_prop_pca_var = 1:length(proportion_pca_var)
#barplot(proportion_pca_var[1:20])
#tcga_exp_pca$sdev
```

```{r load packages}
library(Seurat)
library(ggplot2)
library(tidyverse)
library(cluster)
```

```{r PCA and data exploration}
#tcga_exp_prc_clean is the "big data set", only protein coding genes and without low variance genes (p50-Quantile cut off)
PCA_exp = RunPCA(as.matrix(tcga_exp_prc_clean))
#create data frame with PCs and respective genes
PCA_exp_PCs = PCA_exp@cell.embeddings
#visualize PCs with respect to explained variance
PCA_exp_var = PCA_exp@stdev^2
PCA_exp_proportion_var = PCA_exp_var/sum(PCA_exp_var)
PC_exp = (PCA_exp_PCs[1:20])
PCs_20 = PCA_exp@cell.embeddings[1:20]

#plot PCA, PC1 vs PC2 KIRC = black --> outlier
pca_kirc = data.frame(PCA_exp[cancer_types == "KIRC",])
PCA_exp_scatter2 = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y = PC_2, color = cancer_types)) +
  geom_point(point = 0.5)+ 
  geom_point(data= pca_kirc , aes(x = PC_1, y = PC_2), color = "black")
print(PCA_exp_scatter2) 

#plot PCA, PC1 vs PC2, KIRC = black --> outlier
PCA_exp_scatter3 = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y = PC_3, color = cancer_types )) +
  geom_point(point = 0.5) + 
  geom_point(data= pca_kirc , aes(x = PC_1, y = PC_3), color = "black")
print(PCA_exp_scatter3) 

# plot scatter plot regarding gender -> no clustering detectable
exp_gender = ifelse(tcga_annot$gender
                        == "FEMALE", "orange", "blue")
PCA_exp_gender = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y= PC_2)) + 
  geom_point(size = 0.5, color = exp_gender) + 
  ggtitle ("PCA regarding gender")
PCA_exp_gender
```

```{r UMAP}

cancer_types = tcga_annot$cancer_type_abbreviation
data_kirc = which(cancer_types == "KIRC")

#calculate UMAP on PCA 
UMAP_exp= uwot::umap(PCA_exp@cell.embeddings)
colnames(UMAP_exp) = c("UMAP1", "UMAP2")
UMAP_exp_KIRC = data.frame(UMAP_exp[cancer_types == "KIRC",])
UMAP_plot = ggplot (data = as.data.frame(UMAP_exp), 
                    aes(x = UMAP1, y= UMAP2, color = cancer_types))+
  geom_point(size = 2) 
UMAP_plot

#plot KIRC in black
UMAP_exp= uwot::umap(PCA_exp@cell.embeddings)
UMAP_exp_KIRC = data.frame(UMAP_exp[cancer_types == "KIRC",])
UMAP_plot_black = ggplot (data = as.data.frame(UMAP_exp), 
                    aes(x = V1, y= V2, color = cancer_types))+
  geom_point(size = 2) +
  geom_point(data= UMAP_exp_KIRC , aes(x = X1, y = X2), color = "black")
UMAP_plot_black

#kirc in different color
UMAP_plot_1 = ggplot (data = as.data.frame(UMAP_exp), 
                    aes(x = V1, y= V2, color = cancer_types=="KIRC"))+
  geom_point(size = 2) 
UMAP_plot_1

#plot umap for each cancer type (umap over all cancer types split into 33 plots per cancer type)
cancer_names = unique(cancer_types)
UMAP_output = list ()
for (i in 1:length(cancer_names)) {
  cancer = c(which(cancer_types == cancer_names[i]))
  cancer_df = data.frame(UMAP_exp[cancer,])
  UMAP_output[[i]] = ggplot (data = cancer_df,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 2 , color = "blue")+ 
    ggtitle (cancer_names [[i]])
}

UMAP_output[[1]]
cancer = c(which(cancer_types == cancer_names[1]))
names(UMAP_output) = cancer_names

#plot of UMAP for KIRC
UMAP_output$KIRC

#plot Umaps for all 33 cancer types
sapply(1:33, function(i){
  plot(UMAP_output[[i]])
  })
```

```{r clustering}
#find optimal clusternumber
library(ggpubr)
library(factoextra)

kmeans(UMAP_exp, centers= 20, nstart = 50)##
# for 4 centers
km.4 = kmeans(UMAP_exp, centers= 20, nstart = 50)
km.4

fviz_cluster(km.4, data.frame(UMAP_exp),
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
UMAP_plot

#extract tot.withinss --> for silhouette plot (elbow method)
tcga_UMAP_kmeans_tw = sapply(1:20, function(k){
  kmeans(x = UMAP_exp , centers = k, nstart = 50 )$tot.withinss})

#elbow plot
umap_elbow = plot(tcga_UMAP_kmeans_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")
umap_elbow

fviz_nbclust(UMAP_exp, kmeans, method='silhouette')

#extract cluster values for silhouette plot
tcga_UMAP_kmeans_c = sapply(2:20, function(k){
  kmeans(x = UMAP_exp , centers = k, nstart = 50 )$cluster})

#silhouette plot
sapply(1:19, function(x){
  plot(silhouette(tcga_UMAP_kmeans_c[,x], dist(UMAP_exp)), main ="Silhouette plot")})
```

```{r}
tumorlist = readRDS("../data/tumorlist_z.RDS")

cancer_abc = sort(cancer_names)
names(PCA_tumorlist_ACC_BLCA) = cancer_abc[1:2] #funktioniert
```

```{r}
# RunPCA only works on Genesets with 50 or more patients -> but setting npcs (total number of PCs to compute and store) doesn't change anything
#only CHOL and DLBC have <50 columns/patients -> exclude from PCA 

# cancer_abc[1:4]
tumorlist_1_4 = tumorlist[1:4]
PCA_tumorlist_1_4 = lapply (1:4, function (i) {
  RunPCA(as.matrix(tumorlist[[i]]))
}) 

UMAP_tumorlist_1_4 = lapply (1:4, function (j) {
  uwot::umap(PCA_tumorlist_1_4[[j]]@cell.embeddings)
})

UMAP_output_1_4 = list ()
for (i in 1:4) {
  UMAP_df = data.frame(UMAP_tumorlist_1_4[[i]])
  UMAP_output_1_4[[i]] = ggplot (data = UMAP_df,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")+ 
    ggtitle (cancer_abc [[i]])
}

names(UMAP_output_1_4) = cancer_abc[1:4]

sapply(1:4, function(i){
  plot(UMAP_output_1_4[[i]])
  }) 

# cancer_abc[8:33]
tumorlist_8_33 = tumorlist[8:33]
PCA_tumorlist_8_33 = lapply (8:33, function (i) {
  RunPCA(as.matrix(tumorlist[[i]]))
}) 

UMAP_tumorlist_8_33 = lapply (1:26, function (j) {
  uwot::umap(PCA_tumorlist_8_33[[j]]@cell.embeddings)
})
cancer_abc_8_33 = cancer_abc[8:33]
UMAP_output_8_33 = list ()
for (i in 1:26) {
  UMAP_df = data.frame(UMAP_tumorlist_8_33[[i]])
  UMAP_output_8_33[[i]] = ggplot (data = UMAP_df,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")+ 
    ggtitle (cancer_abc_8_33 [[i]])
}
names(UMAP_output_8_33) = cancer_abc[8:33]

sapply(1:26, function(i){
  plot(UMAP_output_8_33[[i]])
  })

#PCA and UMAP for COAD
tumorlist_COAD = tumorlist[[6]]
PCA_COAD = RunPCA(as.matrix(tumorlist_COAD))
UMAP_COAD = uwot::umap(PCA_COAD@cell.embeddings)
UMAP_COAD_plot = ggplot (data = data.frame(UMAP_COAD), 
                         aes (x = X1, y = X2, color = "blue")) + 
  geom_point(size = 0.5, color = "blue")+
  ggtitle("COAD")
UMAP_COAD_plot
colnames(UMAP_COAD) = c("X1", "X2")

#PCA and UMAP for CHOL and DLBC but set custom npcs
tumorlist_CHOL = tumorlist [[5]]
PCA_CHOL = RunPCA(as.matrix(tumorlist_CHOL), npcs = ncol(tumorlist_CHOL)-1)
UMAP_CHOL = uwot::umap(PCA_CHOL@cell.embeddings)
UMAP_CHOL_plot = ggplot (data = data.frame(UMAP_CHOL), 
                         aes (x = X1, y = X2, color = "blue")) + 
  geom_point(size = 0.5, color = "blue")+
  ggtitle("CHOL")
UMAP_CHOL_plot

tumorlist_DLBC = tumorlist [[7]]
PCA_DLBC = RunPCA(as.matrix(tumorlist_DLBC), npcs = ncol(tumorlist_DLBC)-1)
UMAP_DLBC = uwot::umap(PCA_DLBC@cell.embeddings)
UMAP_DLBC_plot = ggplot (data = data.frame(UMAP_DLBC), 
                         aes (x = X1, y = X2, color = "blue")) + 
  geom_point(size = 0.5, color = "blue")+
  ggtitle("DLBC")
UMAP_DLBC_plot
```

```{r}
#PCA over all tumor types in one 
#set number of PCs to number of patients (-1 is because of RunPCA)

PCA_tumorlist_33 = lapply (1:length(tumorlist), function (i) {
  RunPCA(as.matrix(tumorlist[[i]]), npcs = (ncol(tumorlist[[i]]))-1)
         }) 

UMAP_tumorlist_33 = lapply (1:length(tumorlist), function (j) {
  uwot::umap(PCA_tumorlist_33[[j]]@cell.embeddings)
})

UMAP_output_33 = list ()
for (i in 1: length(tumorlist)) {
  UMAP_df = data.frame(UMAP_tumorlist_33[[i]])
  UMAP_output_33[[i]] = ggplot (data = UMAP_df,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")+ 
    ggtitle (cancer_abc [[i]])
}
names(UMAP_output_33) = cancer_abc

sapply(1:33, function(i){
  plot(UMAP_output_33[[i]])
  })
```
 
```{r}
umap_plot_33 = list ()
for (i in 1: length(UMAP_output_33)) {
  UMAP_tumor = UMAP_output_33[[i]]$data
  UMAP_output_33_df = data.frame(UMAP_tumor)
  umap_plot_33 = ggplot (data = UMAP_output_33_df, 
                         aes (x = X1, y = X2, color = cancer_types)) +
    geom_point(size = 0.5)
}
umap_plot_33
```


