---
title: "TCGA_subtyping_MMR/PID"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```


```{r data}
#load pathway activity matricesd for MMR and PID for all 33 tumortypes
#TCGA_pw_MMR = readRDS("../data/NES_OVERALL_MMR.RDS")
TCGA_pw_MMR = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/NES_OVERALL_MMR.RDS")
TCGA_pw_PID =  readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/NES_OVERALL_PID_cl.RDS")
cancer_abc = names(TCGA_pw_MMR) 
```

```{r}
xxx = c("PID_IL4_2PATHWAY","PID_IL6_7_PATHWAY","PID_IL8_CXCR1_PATHWAY","PID_IL8_CXCR2_PATHWAY","PID_INTEGRIN_A4B1_PATHWAY","PID_LYMPH_ANGIOGENESIS_PATHWAY","PID_LYSOPHOSPHOLIPID_PATHWAY","PID_MYC_ACTIV_PATHWAY","PID_NFAT_TFPATHWAY")
TG = list()
immune = c(PID_Tim,Anna_PID,Linda_PID,xxx)
for (i in 1:length(TCGA_pw_PID)){
  TG[[i]] = TCGA_pw_PID[[i]][which(rownames(TCGA_pw_PID[[i]])%in%immune),]
}
names(TG) = cancer_abc
TCGA_pw_PID = TG
```

```{r packages}
library(ggplot2)
library(tidyverse)
library(Seurat)
library(gridExtra)
library(cluster)
library(ggpubr)
library(factoextra)
library(scrime)
library("factoextra")
set.seed(69)
```

```{r PCA / umap for PID}

PCA_PID = lapply (1:length(TCGA_pw_PID), function (i) {
  RunPCA(as.matrix(TCGA_pw_PID[[i]]),npcs = (nrow(TCGA_pw_MMR[[i]])-1)
         )
         }) 

UMAP_PID = lapply (1:length(TCGA_pw_PID), function (j) {
  uwot::umap(PCA_PID[[j]]@cell.embeddings)
})

UMAP_output_PID = list ()
for (i in 1: length(TCGA_pw_PID)) {
  UMAP_df_PID = data.frame(UMAP_PID[[i]])
  UMAP_output_PID[[i]] = ggplot (data = UMAP_df_PID,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")+ 
    ggtitle (cancer_abc [[i]])
}
names(UMAP_output_PID) = cancer_abc
plot1234 = list(UMAP_output_PID[[1]],UMAP_output_PID[[2]],UMAP_output_PID[[3]])
ggarrange(plotlist=UMAP_output_PID, widths = c(1,0,1))
ggarrange(plotlist = plot1234)
UMAP_output_PID$ACC
```


```{r PCA / umap for MMR}
PCA_MMR = lapply (1:length(TCGA_pw_MMR), function (i) {
  RunPCA(as.matrix(TCGA_pw_MMR[[i]]), npcs = (nrow(TCGA_pw_MMR[[i]])))
         }) 

UMAP_MMR = lapply (1:length(TCGA_pw_MMR), function (j) {
  uwot::umap(PCA_MMR[[j]]@cell.embeddings)
})

UMAP_output_MMR = list ()
for (i in 1: length(TCGA_pw_MMR)) {
  UMAP_df_MMR = data.frame(UMAP_MMR[[i]])
  UMAP_output_MMR[[i]] = ggplot (data = UMAP_df_MMR,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")+ 
    ggtitle (cancer_abc [[i]])
}
names(UMAP_output_MMR) = cancer_abc
ggarrange(plotlist = UMAP_output_MMR, widths = c(0.1,0.1))
UMAP_output_MMR$KIRC
```


```{r kmeans for PID}
set.seed(69)
kmeans_PID = vector(mode = "list",33)
for (i in (1:length(UMAP_PID))){
  for (k in (1:5)) {
    x = UMAP_PID[[i]]
    kmeans_PID[[i]][[k]] = kmeans(x, centers = k, nstart = 200)
  }
}
names(kmeans_PID) = cancer_abc


cluster_PID = vector(mode = "list",33)
for(i in (1:length(cluster_PID))){
  for (k in (1:5)){
    y = kmeans_PID[[i]][[k]]
    z = data.frame(UMAP_PID[[i]])
    cluster_PID[[i]][[k]] = fviz_cluster(y, data = z,
             palette = c("orange", "blue","forestgreen","pink","yellow"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
  }
}

names(cluster_PID) = cancer_abc


cluster_PID_k2 = list()
for (i in (1:length(UMAP_PID))){
     cluster_PID_k2[[i]] = cluster_PID[[i]][[2]]
 }
names(cluster_PID_k2) = cancer_abc 
ggarrange(plotlist = cluster_PID_k2)
cluster_PID_k2$KIRC
```


```{r elbow plot for all}
n = data.frame()
for (i in (1:length(UMAP_PID))){
 for (k in (1:5)) {
     n[k,i] = data.frame(kmeans_PID[[i]][[k]]$tot.withinss)
 }
}
w = c(1:5)
tot_PID = list()
for (i in (1:length(UMAP_PID))){
    p  = data.frame(n[,i])
    colnames(p) = "b"
    t = cbind(p,w)
    tot_PID[[i]] = ggplot(data = t, aes(y = b, x = w ))+
      geom_point(size =2, color = "lightblue")+
      geom_line(group = 1, color = "lightblue")+
      labs (y = "tot withins",
        x = "cluster frequenz")+
      ggtitle(cancer_abc[i])
  }

names(tot_PID) = cancer_abc
tot1234 = list(tot_PID[[1]],tot_PID[[7]],tot_PID[[9]],tot_PID[[10]])
ggarrange(plotlist = tot1234)
```



```{r create df for 2 clusters per tumortype}
#extract cluster information 
cluster12_PID = list(list())
for (i in (1:length(UMAP_PID))){
     cluster12_PID[i] = list(kmeans_PID[[i]][[2]][["cluster"]])
 }
names(cluster12_PID) = cancer_abc

#patients in cluster 1
cluster1_PID = list()
for (i in (1:length(UMAP_PID))){
  z = cluster12_PID[[i]]
     cluster1_PID[[i]] = names(z[which(z == 1)])
}
names(cluster1_PID) = cancer_abc
#patients in cluster 2
cluster2_PID = list()
for (i in (1:length(UMAP_PID))){
  z = cluster12_PID[[i]]
     cluster2_PID[[i]] = names(z[which(z == 2)])
}
names(cluster2_PID) = cancer_abc

#filter for PIDs for cluster 1 patients
PID_c1_patients = list()
for (i in (1:length(UMAP_PID))){
  t = cluster1_PID[[i]]
  PID_c1_patients[[i]] = TCGA_pw_PID[[i]][,which(colnames(TCGA_pw_PID[[i]]) %in% t)]
}
names(PID_c1_patients) = cancer_abc

#filter for cluster 2 patients
PID_c2_patients = list()
for (i in (1:length(UMAP_PID))){
  t = cluster2_PID[[i]]
  PID_c2_patients[[i]] = TCGA_pw_PID[[i]][,colnames(TCGA_pw_PID[[i]]) %in% t]
}
names(PID_c2_patients) = cancer_abc
```


```{r calculate mean for each cluster}

PID_c1_mean = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_patients[[i]]
  PID_c1_mean[[i]] = data.frame(apply(r,1,mean))
}
names(PID_c1_mean) = cancer_abc

PID_c2_mean = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c2_patients[[i]]
  PID_c2_mean[[i]] = data.frame(apply(r,1,mean))
  
}
names(PID_c2_mean) = cancer_abc

PID_c1_c2_dif = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_mean[[i]]
  u = PID_c2_mean[[i]]
  PID_c1_c2_dif[[i]] = r - u
}
names(PID_c1_c2_dif) = cancer_abc

PID_c1_c2_dif_rank = list()
for (i in (1:length(UMAP_PID))){
  p = PID_c1_c2_dif[[i]]
  PID_c1_c2_dif_rank[[i]] = data.frame(PID_c1_c2_dif[[i]]$apply.r..1..mean.[order(PID_c1_c2_dif[[i]][,1],decreasing = TRUE)])
}
names(PID_c1_c2_dif_rank) = cancer_abc

PID_rownames = c(rownames(PID_c1_c2_dif[[1]]))
PID_rownames_rank = list()
for (i in (1:length(UMAP_PID))){
  s = c(PID_c1_c2_dif[[i]][,1])
  PID_rownames_rank[[i]] = c(PID_rownames[order(s,decreasing = TRUE)])
}
names(PID_rownames_rank) = cancer_abc

PID_c1_c2_dif_rank_df = list()
for (i in (1:length(UMAP_PID))){
  h = PID_c1_c2_dif_rank[[i]]
  g = PID_rownames_rank [[i]]
  PID_c1_c2_dif_rank_df[[i]] = as.data.frame(cbind(g,h))
  colnames(PID_c1_c2_dif_rank_df[[i]]) = c("Pathways", "Difference")
}
names(PID_c1_c2_dif_rank_df) = cancer_abc
```
```{r Z scaling}
probek = data.matrix(rowScales(TCGA_pw_PID$KIRC)) 
remove.dots = function(df){colnames(df) = sub(".","-",colnames(df));df}
colnames(probek) = colnames(TCGA_pw_PID$KIRC)


PID_c1k = probek[,which(colnames(probek)%in%cluster1_PID$KIRC)]
PID_c2k = probek[,which(colnames(probek)%in%cluster2_PID$KIRC)]

PID_c1k = PID_c1k[-64,]
PID_c2k = PID_c2k[-64,]
View(PID_c1k)
PID_c2k = probek[,which(colnames(probek)%in%cluster2_PID$KIRC)]

probe_kk = data.matrix(sapply(1:87,function(i){
  wilcox.test(PID_c1k[i,],PID_c2k[i,],paired = FALSE)
}$p.value
))
View(probe_kk)

```

```{r significance filtering: wilcoxon}

##filter constant genes 
PID_c1_min = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_patients[[i]]
  PID_c1_min[[i]] = data.frame(apply(r,1,min))
}
names(PID_c1_min) = cancer_abc

PID_c1_max = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_patients[[i]]
  PID_c1_max[[i]] = data.frame(apply(r,1,max))
}
names(PID_c1_max) = cancer_abc

PID_c1_constant = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_min[[i]]
  t = PID_c1_max[[i]]
  PID_c1_constant[[i]] = c(names(which(r == t)))
}
names(PID_c1_constant) = cancer_abc

r = PID_c1_min$ACC
  t = PID_c1_max$ACC
  PID_c1_constant = c(colnames(which(r == t)))
aaa = PID_c1_patients$ACC
acute = aaa[!PID_c1_constant,]
PID_c1_constant
dim(aaa)
View(acute)
 names(z[which(z == 1)])


 
PID_wilcox_pv = list()
for (i in (1:length(UMAP_PID))){
  v = as.matrix(PID_c1_patients[[i]])
  b = as.matrix(PID_c2_patients[[i]])
  PID_wilcox_pv[[i]] = data.matrix(sapply(1:nrow(v), function(x){
    wilcox.test(v[x,],b[x,], paired=FALSE)
  }$p.value))
  rownames(PID_wilcox_pv[[i]]) = rownames(PID_c1_patients[[i]])
  colnames(PID_wilcox_pv[[i]]) = "pvalue"
}
names(PID_wilcox_pv) = cancer_abc
View(PID_wilcox_pv$KIRC)

#Bonferroni-Korrektur 
alpha_PID=0.05/(nrow(TCGA_pw_PID[[1]]))

#convert NaN to pvalue 1
for (i in (1:length(UMAP_PID))){
  PID_wilcox_pv[[i]][is.nan(PID_wilcox_pv[[i]])] = 1
}

```


```{r alternative tests}
##H-test 
H_prep = data.frame()
H_total = list()
H_cluster1 = c()
H_cluster2 = c()
H_c1c2 = c()
for(i in (1:length(UMAP_PID))){
  H_cluster1 = c(rep(c(1),times = ncol(PID_c1_patients[[i]])))
  H_cluster2 = c(rep(c(2),times = ncol(PID_c2_patients[[i]])))
  H_c1c2 = c(H_cluster1,H_cluster2)
  H_prep = cbind(PID_c1_patients[[i]],PID_c2_patients[[i]])
  H_total[[i]] = data.frame(rbind(H_prep,H_c1c2))
  
}
View(H_total)
names(H_total) = cancer_abc
for (i in 1:length(UMAP_PID)){
  rownames(H_total[[i]][89,]) = c("Cluster")
}
View(H_total$KIRC)
H_pv = data.frame()
for(i in (1:nrow(H_total$KIRC)-1)){
p = as.numeric(H_total$KIRC[i,])
f = as.numeric(H_total$KIRC[89,])
H_pv[i,] = kruskal.test(x = p, g =f)}


p = as.numeric(H_total$KIRC[87,])
f = as.numeric(H_total$KIRC[89,])
y = kruskal.test(x = p, g =f)

#same results as wilcoxon
```


```{r alternative tests}
#try ks test
PID_ks_pv = list()
for (i in (1:length(UMAP_PID))){
  v = as.matrix(PID_c1_patients[[i]])
  b = as.matrix(PID_c2_patients[[i]])
  PID_ks_pv[[i]] = data.matrix(sapply(1:nrow(v), function(x){
    ks.test(v[x,],b[x,], alternative = "two.sided")
  }$p.value))
  rownames(PID_ks_pv[[i]]) = rownames(PID_c1_patients[[i]])
  colnames(PID_ks_pv[[i]]) = "pvalue"
}
names(PID_ks_pv) = cancer_abc
View(PID_ks_pv$KIRC)
#ks test appears to work!!
```



```{r pv cutoff}
PID_wilcox_pv_log = list()
for (i in (1:length(UMAP_PID))){
  a = PID_wilcox_pv[[i]]
  PID_wilcox_pv_log[[i]] = -log10(a)
  colnames(PID_wilcox_pv_log[[i]]) = "neg_log10_pv"
}
names(PID_wilcox_pv_log) = cancer_abc


for (i in (1:length(UMAP_PID))){
  PID_wilcox_pv_log[[i]][PID_wilcox_pv_log[[i]] == Inf] = 0
}

#combine FC and pv matrix
PID_pv_dif = list()
for (i in (1:length(UMAP_PID))){
  a = PID_c1_c2_dif[[i]]
  b = PID_wilcox_pv_log[[i]]
  PID_pv_dif[[i]] = as.data.frame(cbind(a,b))
  colnames(PID_pv_dif[[i]]) = c("Difference","neg_log10_pv")
}
names(PID_pv_dif) = cancer_abc

#extracting sign differently expressed genes (pvalue > cutoff) 
cutoffpv_PID = -log10(alpha_PID)

PID_pv_dif_sig = list()
for (i in (1:length(UMAP_PID))){
  a = PID_pv_dif[[i]]
  PID_pv_dif_sig[[i]] = a[which(a$neg_log10_pv>cutoffpv_PID),]
}
names(PID_pv_dif_sig) = cancer_abc
View(PID_pv_dif_sig$ACC)

#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_pv_dif_sigup = list()
for (i in (1:length(UMAP_PID))){
 t = PID_pv_dif_sig[[i]]
 PID_pv_dif_sigup[[i]] = t[which(abs(t[,1])>0),]
}
names(PID_pv_dif_sigup) = cancer_abc

PID_dif_sig = list()
for (i in (1:length(UMAP_PID))){
t = PID_pv_dif_sig[[i]]$Difference
PID_dif_sig[[i]] = data.frame(t)
}
names(PID_dif_sig) = cancer_abc
View(PID_dif_sig$ACC)

PID_dif_sig_names = list()
for (i in (1:length(UMAP_PID))){
 t = c(rownames(PID_pv_dif_sig[[i]]))
 PID_dif_sig_names [[i]] = t
}
names(PID_dif_sig_names) = cancer_abc


for (i in (1:length(UMAP_PID))){
 r = PID_dif_sig_names[[i]]
 u = PID_dif_sig[[i]]
 PID_dif_sig[[i]] = cbind(r,u)
 colnames(PID_dif_sig[[i]]) = c("Pathway", "Difference")
}
#sry hab hier per hand gefiltert, ging schneller 
PID_dif_sig_0 = list(PID_dif_sig$ACC,PID_dif_sig$CHOL,PID_dif_sig$DLBC,PID_dif_sig$KICH,PID_dif_sig$MESO,PID_dif_sig$READ,PID_dif_sig$TGCT,PID_dif_sig$UVM)
View(PID_dif_sig_0)
cancer_sig = c("ACC","CHOL","DLBC","KICH","MESO","READ","TGCT","UVM")
names(PID_dif_sig_0) = cancer_sig
```




```{r p value cutoff ks test}
PID_ks_pv_log = list()
for (i in (1:length(UMAP_PID))){
  a = PID_ks_pv[[i]]
  PID_ks_pv_log[[i]] = -log10(a)
  colnames(PID_ks_pv_log[[i]]) = "neg_log10_pv"
}
names(PID_ks_pv_log) = cancer_abc


for (i in (1:length(UMAP_PID))){
  PID_ks_pv_log[[i]][PID_ks_pv_log[[i]] == Inf] = 0
}

#combine FC and pv matrix
PID_ks_pv_dif = list()
for (i in (1:length(UMAP_PID))){
  a = PID_c1_c2_dif[[i]]
  b = PID_ks_pv_log[[i]]
  PID_ks_pv_dif[[i]] = as.data.frame(cbind(a,b))
  colnames(PID_ks_pv_dif[[i]]) = c("Difference","neg_log10_pv")
}
names(PID_ks_pv_dif) = cancer_abc

#extracting sign differently expressed genes (pvalue > cutoff) 
cutoffpv_PID = -log10(alpha_PID)

PID_ks_pv_dif_sig = list()
for (i in (1:length(UMAP_PID))){
  a = PID_ks_pv_dif[[i]]
  PID_ks_pv_dif_sig[[i]] = a[which(a$neg_log10_pv>cutoffpv_PID),]
}
names(PID_ks_pv_dif_sig) = cancer_abc

#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_ks_pv_dif_sigup = list()
for (i in (1:length(UMAP_PID))){
 t = PID_ks_pv_dif_sig[[i]]
 PID_ks_pv_dif_sigup[[i]] = t[which(abs(t[,1])>0),]
}
names(PID_ks_pv_dif_sigup) = cancer_abc

PID_ks_dif_sig = list()
for (i in (1:length(UMAP_PID))){
t = PID_ks_pv_dif_sig[[i]]$Difference
PID_ks_dif_sig[[i]] = data.frame(t)
}
names(PID_ks_dif_sig) = cancer_abc
View(PID_ks_dif_sig$ACC)

PID_ks_dif_sig_names = list()
for (i in (1:length(UMAP_PID))){
 t = c(rownames(PID_ks_pv_dif_sig[[i]]))
 PID_ks_dif_sig_names [[i]] = t
}
names(PID_ks_dif_sig_names) = cancer_abc


for (i in (1:length(UMAP_PID))){
 r = PID_ks_dif_sig_names[[i]]
 u = PID_ks_dif_sig[[i]]
 PID_ks_dif_sig[[i]] = cbind(r,u)
 colnames(PID_ks_dif_sig[[i]]) = c("Pathway", "Difference")
}
```


```{r padjust for ks test}

f = as.numeric(PID_ks_pv$KIRC)
v = p.adjust(f, method = "BH")

PID_ks_pv_BH = list()
for (i in (1:length(UMAP_PID))){
f = c(PID_ks_pv[[i]])
PID_ks_pv_BH[[i]] = p.adjust(f, method ="BH")
}
names(PID_ks_pv_BH) = cancer_abc


names(PID_ks_pv_log) = cancer_abc
PID_ks_pv_BH_log = list()
for (i in (1:length(UMAP_PID))){
  a = as.matrix(PID_ks_pv_BH[[i]])
  PID_ks_pv_BH_log[[i]] = -log10(a)
   colnames(PID_ks_pv_BH_log[[i]]) = "neg_log10_pv"
}
names(PID_ks_pv_BH_log) = cancer_abc


for (i in (1:length(UMAP_PID))){
  PID_ks_pv_BH_log[[i]][PID_ks_pv_log[[i]] == Inf] = 0
}

#combine FC and pv matrix
PID_ks_pv_dif_BH = list()
for (i in (1:length(UMAP_PID))){
  a = PID_c1_c2_dif[[i]]
  b = PID_ks_pv_BH_log[[i]]
  PID_ks_pv_dif_BH[[i]] = as.data.frame(cbind(a,b))
  colnames(PID_ks_pv_dif_BH[[i]]) = c("Difference","neg_log10_pv")
}
names(PID_ks_pv_dif_BH) = cancer_abc

#extracting sign differently expressed genes (pvalue > cutoff) 
cutoffpv_PID_BH = -log10(0.05)

PID_ks_pv_dif_sig_BH = list()
for (i in (1:length(UMAP_PID))){
  a = PID_ks_pv_dif_BH[[i]]
  PID_ks_pv_dif_sig_BH[[i]] = a[which(a$neg_log10_pv>cutoffpv_PID_BH),]
}
names(PID_ks_pv_dif_sig_BH) = cancer_abc

#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_ks_pv_dif_sigup_BH = list()
for (i in (1:length(UMAP_PID))){
 t = PID_ks_pv_dif_sig_BH[[i]]
 PID_ks_pv_dif_sigup_BH[[i]] = t[which(abs(t[,1])>0),]
}
names(PID_ks_pv_dif_sigup_BH) = cancer_abc

PID_ks_dif_sig_BH = list()
for (i in (1:length(UMAP_PID))){
t = PID_ks_pv_dif_sig_BH[[i]]$Difference
PID_ks_dif_sig_BH[[i]] = data.frame(t)
}
names(PID_ks_dif_sig_BH) = cancer_abc
View(PID_ks_dif_sig_BH$KIRC)

PID_ks_dif_sig_names_BH = list()
for (i in (1:length(UMAP_PID))){
 t = c(rownames(PID_ks_pv_dif_sig_BH[[i]]))
 PID_ks_dif_sig_names_BH[[i]] = t
}
names(PID_ks_dif_sig_names_BH) = cancer_abc


for (i in (1:length(UMAP_PID))){
 r = PID_ks_dif_sig_names_BH[[i]]
 u = PID_ks_dif_sig_BH[[i]]
 PID_ks_dif_sig_BH[[i]] = cbind(r,u)
 colnames(PID_ks_dif_sig_BH[[i]]) = c("Pathway", "Difference")
}


x = list()
for (i in (1:length(UMAP_PID))){
x[[i]] = which(nrow(PID_ks_dif_sig_BH[[i]])==0)
}
names(x) = cancer_abc
c = names(which(x == "integer(0)"))
PID_ks_dif_sig_BH_0 = PID_ks_dif_sig_BH[names(PID_ks_dif_sig_BH)%in%c]
cancer_sigBH = names(PID_ks_dif_sig_BH_0)
kirc_names = c((PID_ks_dif_sig_BH_0$KIRC[,1]))

```


```{r plot significant pathways}
PID_dif_plot = list()
for (i in (1:length(PID_dif_sig_0))){
  g = PID_dif_sig_0[[i]]
  PID_dif_plot[[i]] = ggplot(g, aes(x=reorder(Pathway,Difference), y=Difference)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PID pw with signif different NES in 2 clusters")+
  theme(plot.title = element_text(size=10))
}
names(PID_dif_plot) = cancer_sig
ggarrange(plotlist=PID_dif_plot)

plotlist1234 = list(PID_dif_plot$ACC,PID_dif_plot$CHOL,PID_dif_plot$DLBC,PID_dif_plot$KIRC)
ggarrange(plotlist = plotlist1234)
  
l = PID_dif_sig$ACC
ggplot(l, aes(x=reorder(Pathway,Difference), y=Difference)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PID pw with signif different NES in 2 KIRC clusters")+
  theme(plot.title = element_text(size=10))

ggarrange(plotlist=UMAP_output_PID, widths = c(1,0,1))
```

```{r plot significant pathways (BH)}
PID_dif_plot_BH = list()
for (i in (1:length(PID_ks_dif_sig_BH_0))){
  g = PID_ks_dif_sig_BH_0[[i]]
  PID_dif_plot_BH[[i]] = ggplot(g, aes(x=reorder(Pathway,Difference), y=Difference)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle(cancer_sigBH[[i]])+
  theme(plot.title = element_text(size=10))
}
names(PID_dif_plot_BH) = cancer_sigBH
p123 = list(PID_dif_plot_BH$ACC,PID_dif_plot_BH$BLCA,PID_dif_plot_BH$BRCA,PID_dif_plot_BH$CESC,PID_dif_plot_BH$CHOL,PID_dif_plot_BH$COAD,PID_dif_plot_BH$HNSC,PID_dif_plot_BH$KICH,PID_dif_plot_BH$KIRC)
p345 = list(PID_dif_plot_BH$KIRP,PID_dif_plot_BH$LAML,PID_dif_plot_BH$LGG,PID_dif_plot_BH$LIHC,PID_dif_plot_BH$LUAD,PID_dif_plot_BH$LUSC,PID_dif_plot_BH$MESO,PID_dif_plot_BH$OV)
p567 = list(PID_dif_plot_BH$PAAD,PID_dif_plot_BH$PCPG,PID_dif_plot_BH$PRAD,PID_dif_plot_BH$READ,PID_dif_plot_BH$SARC,PID_dif_plot_BH$SKCM,PID_dif_plot_BH$STAD,PID_dif_plot_BH$TGCT,PID_dif_plot_BH$THCA,PID_dif_plot_BH$THYM,PID_dif_plot_BH$UCEC)
ggarrange(plotlist = p567)


ggarrange(plotlist=PID_dif_plot_BH,ncol = 4,nrow = 7,widths = c(0.5,0.5),heights = c(0.5,0.5))
PID_dif_plot_BH$KIRC
```


```{r Seurat}
KIRC = NES_OVERALL_PID_cl[[12]]
KIRC_PID_pca = prcomp(t(KIRC))#center = F, scale. = F???
length(KIRC_PID_pca$sdev) #72 patients resulting in 72 PCs as rank of matrix = number of PCs

#dataframe with PCs (resulting from pathways) and patients
KIRC_PID_pca_x = data.frame(KIRC_PID_pca[["x"]])

library("factoextra")
KIRC_PID_pca_eigval = get_eigenvalue(KIRC_PID_pca)
rownames(KIRC_PID_pca_eigval) = colnames (KIRC_PID_pca_x)
barplot(KIRC_PID_pca_eigval$variance.percent,ylab='Proportion of variance in percent', xlab = "Principal Components")

KIRC_PCA_x1=data.frame(KIRC_PID_pca_x)
Seurat_PID = CreateSeuratObject(counts= KIRC)#create a Seurat object wiht the data, this object will be filled by the following commands (PCA;UMAP;clustering...)
VlnPlot(Seurat_PID, features = c("PID-TCR-PATHWAY"))

all.pathways = rownames(Seurat_PID)
Seurat_PID = ScaleData(Seurat_PID, features = all.pathways, verbose = FALSE)#scaling 
Seurat_PID = FindVariableFeatures(object = Seurat_PID)  #to run the PCA, otherwise Error
Seurat_PID = RunPCA(Seurat_PID, features = VariableFeatures(object = Seurat_PID), approx = FALSE, npcs = 71)# approx = F, because: "Hi, this is a warning not an error, just saying that you're running partial SVD but computing most (or all) of the singular values. You can set approx=FALSE to run standard SVD instead."

print(Seurat_PID[["pca"]], dims = 1:5, nfeatures = 5) #what influences the PCs?

DimPlot(Seurat_PID, reduction = "pca")#plot PCA
DimHeatmap(Seurat_PID, cells = 300, balance = TRUE) #heatmap for the influence on first PC

Seurat_PID = FindNeighbors(Seurat_PID, dims =1:7)#patients assign differently to clusters when diffenent number of dims
Seurat_PID = FindClusters(Seurat_PID, n.start = 20, n.iter = 50, resolution = 0.7) #"Identify clusters of cells by a shared nearest neighbor (SNN) modularity optimization based clustering algorithm. First calculate k-nearest neighbors and construct the SNN graph. Then optimize the modularity function to determine clusters."


#rename the clusters
cluster.ids = c("cluster1", "cluster2","cluster3")
names(cluster.ids) = levels(Seurat_PID) 
Seurat_PID = RenameIdents(Seurat_PID, cluster.ids)



Seurat_PID= RunUMAP(Seurat_PID, dims = 1:10) #UMAP
DimPlot(Seurat_PID, reduction = "umap", label = TRUE, pt.size = 0.5) #umap plot

cluster1.marker = FindMarkers(Seurat_PID, ident.1 = "cluster1", min.pct = 0.25)#find markers for cluster 1--> runs a wilcoxon between clusters to identify markers
VlnPlot(Seurat_PID, features = c(row.names(cluster1.marker)[1:nrow(cluster1.marker)]))#plot the markers


Seurat_PID_markers = FindAllMarkers(Seurat_PID, min.pct = 0.25) #find markers for all clusters

Seurat_PID_top_pw = Seurat_PID_markers %>% group_by(cluster) %>% top_n(n =5, wt =avg_log2FC) #top 10 pw that identify clusters (top 5 for each cluster)
FeaturePlot(Seurat_PID, features = Seurat_PID_top_pw$gene[1:10]) #umap with color for pw activity for top 10
FeaturePlot(Seurat_PID, features = "PID-CD8-TCR-DOWNSTREAM-PATHWAY")#umap with color for pw activity for one pathway

DoHeatmap(Seurat_PID, features = Seurat_PID_markers$gene)#heatmap clusterwise
```


```{r}
TCGA_pw_PID_KIRC_t = data.frame(t(TCGA_pw_PID[[1]]))
KIRC_TCR = TCGA_pw_PID_KIRC_t$PID_CD8_TCR_DOWNSTREAM_PATHWAY
KIRC_CD8_TCR = TCGA_pw_PID_KIRC_t$PID_CD8_TCR_PATHWAY
ggplot (data =data.frame(UMAP_PID[[1]]), 
                    aes(x = X1, y = X2 , color = KIRC_TCR))+
  geom_point(size = 1)+
  scale_color_viridis(option = "D")


```


