---
title: "UMAP_MMR_PID_KEGG_DF1"
author: "Linda Blaier"
date: '2022-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```
```{r load packages and data}
#load packages
library(Seurat)
library(ggplot2)
library(umap)

NES_mean_PID = readRDS("../data/NES_mean_PID.RDS")
```
```{r}
#PCA and UMAP over mean pathway activity matrix for PID 
PCA_NES_PID_mean = RunPCA(as.matrix(NES_mean_PID), npcs = 32)
UMAP_NES_PID_mean = uwot::umap(PCA_NES_PID_mean@cell.embeddings)
                               
UMAP_NES_PID_plot_mean = ggplot (data = data.frame(UMAP_NES_PID_mean), aes (x = X1, y = X2, color = cancer_names)) + 
  geom_point(size = 2)

UMAP_NES_PID_plot_mean
```

```{r}
#umap over pathway activity matrix with all pathways
pathway_activity_matrix <- readRDS("~/GitHub/2022-topic-02-team-02/data/pathway_activity_matrix.RDS")

mean_all_pam = rowMeans(pathway_activity_matrix)
sum(which(mean_all_pam == 0)) # no pathways with only NES = 0 -> try w/o cleaning
zeros_pam = rowMeans(pathway_activity_matrix== 0) 
length(which(zeros_pam == 0))

names_pam = colnames(pathway_activity_matrix)
names_pam_vector = unlist(strsplit(names_pam, split = ".", fixed = TRUE))
pam_tumor_type = names_pam_vector[c(TRUE, FALSE)]
pam_patients = names_pam_vector[c(FALSE, TRUE)]

PCA_pam = RunPCA(as.matrix(pathway_activity_matrix))
umap_pam = uwot::umap(PCA_pam@cell.embeddings)
plot_pam = ggplot (data = data.frame(umap_pam), aes (x = X1, y = X2)) +
  geom_point(size = 0.5  )
plot_pam

UMAP_pam_V1 = as.vector(umap_pam[,1])
UMAP_pam_V2 = as.vector(umap_pam[,2])
UMAP_pam_mat = data.frame (pam_tumor_type, pam_patients, UMAP_pam_V1, UMAP_pam_V2)

UMAP_pam_plot = ggplot(data = data.frame(UMAP_pam_mat), aes (x = UMAP_pam_V1, y = UMAP_pam_V2, color = pam_tumor_type)) + 
  geom_point(size = 0.5) +
  ggtitle("UMAP over pathway activity matrix")
UMAP_pam_plot

UMAP_pam_KIRC = data.frame(UMAP_pam_mat[pam_tumor_type == "KIRC",])
UMAP_pam_black = ggplot(data = data.frame(UMAP_pam_mat), aes (x = UMAP_pam_V1, y = UMAP_pam_V2, color = pam_tumor_type)) + 
  geom_point(size = 0.5) +
  geom_point(data= UMAP_pam_KIRC , aes(x = UMAP_pam_V1, y = UMAP_pam_V2), color = "black") + 
  ggtitle("UMAP over MMR pathways", "KIRC = black")
UMAP_pam_black

```

```{r}
#umap over MMR pathways
NES_OVERALL_MMR_alle <- readRDS("~/GitHub/2022-topic-02-team-02/data/NES_OVERALL_MMR_alle.RDS")

PCA_MMR = RunPCA(as.matrix(NES_OVERALL_MMR_alle))
umap_MMR = uwot::umap(PCA_MMR@cell.embeddings)
plot_MMR = ggplot (data = data.frame(umap_MMR), aes (x = X1, y = X2)) +
  geom_point(size = 0.5  )
plot_MMR

UMAP_MMR_V1 = as.vector(umap_MMR[,1])
UMAP_MMR_V2 = as.vector(umap_MMR[,2])
UMAP_MMR_mat = data.frame (pam_tumor_type, pam_patients, UMAP_MMR_V1, UMAP_MMR_V2)

UMAP_MMR_plot = ggplot(data = data.frame(UMAP_MMR_mat), aes (x = UMAP_MMR_V1, y = UMAP_MMR_V2, color = pam_tumor_type)) + 
  geom_point(size = 0.5) +
  ggtitle("UMAP over MMR pathways")
UMAP_MMR_plot

cancer_types = tcga_annot$cancer_type_abbreviation
UMAP_MMR_KIRC = data.frame(UMAP_MMR_mat[pam_tumor_type == "KIRC",])

UMAP_MMR_black = ggplot (data = as.data.frame(UMAP_MMR_mat), 
                    aes(x = UMAP_MMR_V1, y= UMAP_MMR_V2, color = pam_tumor_type))+
  geom_point(size = 0.5) +
  geom_point(data= UMAP_MMR_KIRC , aes(x = UMAP_MMR_V1, y = UMAP_MMR_V2), color = "black") + 
  ggtitle("UMAP over MMR pathways", "KIRC = black")
UMAP_MMR_black

```

```{r}
#UMAP over PID pathways
NES_OVERALL_PID_cl <- readRDS("~/GitHub/2022-topic-02-team-02/data/NES_OVERALL_PID_cl.RDS")

library(rlist)
NES_OVERALL_PID_cl_bound = list.cbind(NES_OVERALL_PID_cl)

mean_nes_PID = rowMeans(NES_OVERALL_PID_cl_bound)
sum(which(mean_nes_PID== 0)) # no pathways with only NES = 0 -> try w/o cleaning
zeros_PID = rowSums(NES_OVERALL_PID_cl_bound== 0) 
length(which(zeros_PID == 0))
plot(zeros_PID)

PCA_PID = RunPCA(as.matrix(NES_OVERALL_PID_cl_bound))
umap_umap_PID = umap(PCA_PID@cell.embeddings)
umap_umap_PID_layout = umap_umap_PID$layout
plot_umap_PID = ggplot (data = data.frame(umap_umap_PID_layout), 
                        aes (x = X1, y = X2, color = cancer_types)) +
  geom_point(size = 0.5) +
  ggtitle("UMAP over PID pathways")
plot_umap_PID

UMAP_PID_KIRC = data.frame(umap_umap_PID_layout[cancer_types == "KIRC",])
plot_umap_PID_black = ggplot (data = data.frame(umap_umap_PID_layout), 
                        aes (x = X1, y = X2, color = cancer_types)) +
  geom_point(size = 0.5) +
  geom_point(data = UMAP_PID_KIRC, aes(x = X1, y = X2), color = "black") +
  ggtitle("UMAP over PID pathways", "KIRC = black")
plot_umap_PID_black
```

```{r}
#UMAP over KEGG pathways

NES_OVERALL_KEGG_alle <- readRDS("~/GitHub/2022-topic-02-team-02/data/NES_OVERALL_KEGG_alle.RDS")

PCA_KEGG = RunPCA(as.matrix(NES_OVERALL_KEGG_alle))
umap_KEGG = umap(PCA_KEGG@cell.embeddings)
umap_KEGG_layout = umap_KEGG$layout
plot_KEGG = ggplot (data = data.frame(umap_KEGG_layout), aes (x = X1, y = X2)) +
  geom_point(size = 0.5  )
plot_KEGG

UMAP_KEGG_V1 = as.vector(umap_KEGG_layout[,1])
UMAP_KEGG_V2 = as.vector(umap_KEGG_layout[,2])
UMAP_KEGG_mat = data.frame (pam_tumor_type, pam_patients, UMAP_KEGG_V1, UMAP_KEGG_V2)

UMAP_KEGG_plot = ggplot(data = data.frame(UMAP_KEGG_mat), aes (x = UMAP_KEGG_V1, y = UMAP_KEGG_V2, color = pam_tumor_type)) + 
  geom_point(size = 0.5) +
  ggtitle("UMAP over KEGG pathways")
UMAP_KEGG_plot

UMAP_KEGG_KIRC = data.frame(UMAP_KEGG_mat[pam_tumor_type == "KIRC",])

UMAP_KEGG_black = ggplot (data = as.data.frame(UMAP_KEGG_mat), 
                    aes(x = UMAP_KEGG_V1, y= UMAP_KEGG_V2, color = pam_tumor_type))+
  geom_point(size = 0.5) +
  geom_point(data= UMAP_KEGG_KIRC , aes(x = UMAP_KEGG_V1, y = UMAP_KEGG_V2), color = "black") + 
  ggtitle("UMAP over KEGG pathways", "KIRC = black")
UMAP_KEGG_black
```

```{r}
#further investigation of PID clusters
#find optimal cluster number
library(ggpubr)
library(factoextra)

km_PID = kmeans(umap_umap_PID_layout, centers= 2, nstart = 50)

fviz_cluster(km_PID, data.frame(umap_umap_PID_layout),
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

km_PID_20 = kmeans (umap_umap_PID_layout, centers = 20, nstart = 50)

#elbow plot
km_PID_tw = sapply(1:20, function(k){
  kmeans(x = umap_umap_PID_layout, centers = k, nstart = 50 )$tot.withinss})

km_PID_elbow = plot(km_PID_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")

#find the optimal number of clusters, silhouette plot (average silhouette width)
library(cluster)
fviz_nbclust(umap_umap_PID_layout, kmeans, method='silhouette') #-> opt. cluster = 2
```
