---
title: "Immune deconvolution"
author: "Maja Glotz"
date: "7/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(69)
```

```{r load packages}
library(immunedeconv)
library("org.Hs.eg.db")
library(gplots)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(rlist)
library(tidyselect)
library(stringr)
```

```{r loading data}
tcga_annot = readRDS("data/tcga_tumor_annotation.RDS")
tcga_exp_cleaned = readRDS("data/tcga_exp_cleaned.RDS")
tcga_KIRC_tumor_cl <- readRDS("data/tcga_KIRC_tumor_cl.rds")
PID_c1_names <- readRDS("data/PID_c1_names.rds")
PID_c2_names <- readRDS("data/PID_c2_names.rds")
c1_patients <- readRDS("/data/c1_patients.RDS")
```

```{r immune deconvolution in small KIRC data set (DF2)}
#convert ensemble id into gene symbol
ensemblids = rownames(tcga_KIRC_tumor_cl)
symbols = mapIds(org.Hs.eg.db, keys = ensemblids, keytype = "ENSEMBL", column="SYMBOL")
rownames(tcga_KIRC_tumor_cl) = symbols
KIRC_tumor = as.matrix(tcga_KIRC_tumor_cl) #18645, all genes

#use immune deconvolution package
#xcell method 
immune_cells = deconvolute(KIRC_tumor, "xcell")
cell_types = immune_cells$cell_type
immune_cells = immune_cells[,-1]
rownames(immune_cells) = cell_types

immune_cells_matrix = as.matrix(immune_cells)
heatmap.2(immune_cells_matrix, dendrogram = "column", hclustfun = hclust, trace = "none", margins = c(11,11))

#reverse log2 operation --> Transcripts per million (TPM)
KIRC_tumor_tpm = 2^KIRC_tumor

#quantiseq method --> returns immune cell fractions
quantiseq_KIRC = deconvolute(KIRC_tumor_tpm, "quantiseq", tumor = "true")
cell_types_2 = quantiseq_KIRC$cell_type
quantiseq_matrix = quantiseq_KIRC[,-1]
rownames(quantiseq_matrix) = cell_types_2
quantiseq_matrix = as.matrix(quantiseq_matrix)
quantiseq_matrix = quantiseq_matrix[-c(11),]
```

```{r plotting immune cell fractions of quanTIseq DF2}
#plot immune cell fractions
Heatmap_quantiseq_KIRC = Heatmap(quantiseq_matrix, name = "mat", column_split = 4, cluster_rows = FALSE, column_names_gp = gpar(fontsize = 5.5), row_names_gp = gpar(fontsize = 10),width = ncol(quantiseq_matrix)*unit(3.5, "mm"), height = nrow(quantiseq_matrix)*unit(11, "mm"), column_dend_height = unit(15, "mm"), column_title = "Immune cell fractions in KIRC tumor", col = colorRamp2(c(0, 0.2), c("black", "red")))
Heatmap_quantiseq_KIRC

#split quantiseq matrix according to PID clustering (PCA, UMAP, k-means)
quantiseq_cluster1 = quantiseq_KIRC[, c("cell_type", PID_c1_names)]
quantiseq_cluster2 = quantiseq_KIRC[, c("cell_type",PID_c2_names)]

#barplot of immune infiltration QUANTISEQ
quantiseq_cluster1_plot = quantiseq_cluster1 %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster1))) +
    theme(axis.text.y = element_text(size = 4)) 

quantiseq_cluster2_plot = quantiseq_cluster2 %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster2))) +
    theme(axis.text.y = element_text(size = 4)) 

ggarrange(quantiseq_cluster1_plot, quantiseq_cluster2_plot, ncol = 1, nrow = 2)
```

```{r CD8 infiltration DF2}
#CD8 only
quantiseq_cluster1_CD8 = quantiseq_cluster1[8,]
quantiseq_cluster2_CD8 = quantiseq_cluster2[8,]
quantiseq_CD8 = cbind(quantiseq_cluster1_CD8, quantiseq_cluster2_CD8)
quantiseq_CD8 = quantiseq_CD8[, -c(42)]

sum(quantiseq_cluster1_CD8[1, 2:41]) #2.008835
sum(quantiseq_cluster2_CD8[1, 2:33]) #0.3102198 

#plot in one
quantiseq_CD8 %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_CD8))) +
    theme(axis.text.y = element_text(size = 4)) #order changes, clusters mixed...

#plot both separately
quantiseq_cluster1_plot_CD8 = quantiseq_cluster1_CD8 %>%
  gather(Upregulated, fraction, -cell_type) %>%
  ggplot(aes(x=Upregulated, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_manual(values = "Blue") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster1_CD8))) +
    theme(axis.text.y = element_text(size = 4))
quantiseq_cluster1_plot_CD8

quantiseq_cluster2_plot_CD8 = quantiseq_cluster2_CD8 %>%
  gather(Neutral, fraction, -cell_type) %>%
  ggplot(aes(x=Neutral, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_manual(values = "Blue") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster2_CD8))) +
    theme(axis.text.y = element_text(size = 4)) + 
    ylim(0,0.33)
quantiseq_cluster2_plot_CD8

ggarrange(quantiseq_cluster1_plot_CD8, quantiseq_cluster2_plot_CD8, ncol = 1, nrow = 2)

#"TCGA-CW-6087-01" patient with extremely high CD8+ immune infiltration!
```

```{r T-reg infiltration DF2}
#T-reg only:
quantiseq_cluster1_Treg = quantiseq_cluster1[9,]
quantiseq_cluster2_Treg = quantiseq_cluster2[9,]
quantiseq_Treg = cbind(quantiseq_cluster1_CD8, quantiseq_cluster2_CD8)
quantiseq_Treg = quantiseq_Treg[, -c(42)]

sum(quantiseq_cluster1_Treg[1, 2:41]) #0.2667334
sum(quantiseq_cluster2_Treg[1, 2:33]) #0.2479281

#plot both separately
quantiseq_cluster1_plot_Treg = quantiseq_cluster1_Treg %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster1_Treg))) +
    theme(axis.text.y = element_text(size = 4)) 

quantiseq_cluster2_plot_Treg = quantiseq_cluster2_Treg %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster2_Treg))) +
    theme(axis.text.y = element_text(size = 4)) 

ggarrange(quantiseq_cluster1_plot_Treg, quantiseq_cluster2_plot_Treg, ncol = 1, nrow = 2)
```


```{r Neutrophil infiltration DF2}
#Neutrophils only:
quantiseq_cluster1_neutro = quantiseq_cluster1[5,]
quantiseq_cluster2_neutro = quantiseq_cluster2[5,]
quantiseq_neutro = cbind(quantiseq_cluster1_neutro, quantiseq_cluster2_neutro)
quantiseq_neutro = quantiseq_neutro[, -c(42)]

sum(quantiseq_cluster1_neutro[1, 2:41]) #4.812149
sum(quantiseq_cluster2_neutro[1, 2:33]) #3.784561

#plot both separately
quantiseq_cluster1_plot_neutro = quantiseq_cluster1_neutro %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster1_neutro))) +
    theme(axis.text.y = element_text(size = 4)) 

quantiseq_cluster2_plot_neutro = quantiseq_cluster2_neutro %>%
  gather(sample, fraction, -cell_type) %>%
  ggplot(aes(x=sample, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_brewer(palette="Paired") + 
    scale_x_discrete(limits = rev(levels(quantiseq_cluster2_neutro))) +
    theme(axis.text.y = element_text(size = 4)) 

ggarrange(quantiseq_cluster1_plot_neutro, quantiseq_cluster2_plot_neutro, ncol = 1, nrow = 2)
```

```{r MCP method on DF2}
#MCP --> arbitrary values only for comparison between samples
mcp_counter = deconvolute(KIRC_tumor_tpm, "mcp_counter")
mcp_counter_matrix = as.matrix(mcp_counter)
mcp_counter_matrix = mcp_counter_matrix[-c(11),]
heatmap.2(quantiseq_matrix, dendrogram = "column", hclustfun = hclust, trace = "none", margins = c(11,11))

mcp_counter %>%
  gather(sample, score, -cell_type) %>%
  ggplot(aes(x=sample, y=score, color=cell_type)) +
    geom_point(size=4) +
    facet_wrap(~cell_type, scales="free_x", ncol=3) +
    scale_color_brewer(palette="Paired", guide=FALSE) +
    coord_flip() + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r immune deconvolution quanTIseq KIRC TCGA (DF1)}
#get dataframe with KIRC data from TCGA (DF1) (531 samples)
tcga_annot_KIRC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="KIRC"),]
tcga_exp_KIRC = tcga_exp_cleaned[, names(tcga_exp_cleaned) %in% tcga_annot_KIRC$sample]

#pathway activity matrix of KIRC samples (DF1)???????????
KIRC_tcga = pathway_activity_matrix %>% dplyr::select(starts_with('KIRC'))

#perform immune deconvolution on KIRC TCGA DS2 with quanTIseq

#transform values back to TPM
KIRC_tcga_tpm = 2^tcga_exp_KIRC

#convert ensemble ids to gene symbol
ensemblids_tcga_cleaned = rownames(KIRC_tcga_tpm)
symbols_tcga_cleaned = mapIds(org.Hs.eg.db, keys = ensemblids_tcga_cleaned, keytype = "ENSEMBL", column="SYMBOL") #336 duplicated
geneIDs <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemblids_tcga_cleaned, keytype = "GENEID", columns = c("SYMBOL","GENEID")) #only 9775 gene symbols found --> remove missing genes from data frame

#remove duplicated gene symbols (24)
geneIDs_unique = distinct(geneIDs,SYMBOL, .keep_all= TRUE)
ensemblid_found = as.vector(geneIDs_unique$GENEID)
KIRC_tcga_tpm_filtered = KIRC_tcga_tpm %>% dplyr::filter(rownames(KIRC_tcga_tpm) %in% ensemblid_found)
rownames(KIRC_tcga_tpm_filtered) = geneIDs_unique$SYMBOL
KIRC_tcga_tpm_matrix = as.matrix(KIRC_tcga_tpm_filtered)

#immune deconvolution with quanTIseq
quantiseq = deconvolute(KIRC_tcga_tpm_matrix, "quantiseq", tumor = "true")
cell_types_2 = quantiseq$cell_type
quantiseq_matrix = quantiseq[,-1]
rownames(quantiseq_matrix) = cell_types_2
quantiseq_matrix = as.matrix(quantiseq_matrix)

#remove unknown cell types, so that heatmap shows better colour scaling
quantiseq_matrix = quantiseq_matrix[-c(11),]

#plot immune deconvolution big KIRC
Heatmap_quantiseq_KIRC_tcga = Heatmap(quantiseq_matrix, name = "mat", column_split = 4, cluster_rows = FALSE, column_names_gp = gpar(fontsize = 2), row_names_gp = gpar(fontsize = 10),width = ncol(quantiseq_matrix)*unit(0.5, "mm"), height = nrow(quantiseq_matrix)*unit(11, "mm"), column_dend_height = unit(15, "mm"), column_title = "Immune cell fractions in KIRC TCGA", col = colorRamp2(c(0, 0.8), c("black", "red")))
Heatmap_quantiseq_KIRC_tcga

#plot CD8 only???????
```

```{r Plot CD8 infiltration in KIRC TCGA DF1}
#split quantiseq matrix according to PID clustering (PCA, UMAP, k-means)
cluster1_patients = colnames(c1_patients)
quantiseq_tcga_cluster1 = quantiseq[, c("cell_type", cluster1_patients)]
quantiseq_tcga_cluster2 = quantiseq[ , !(colnames(quantiseq) %in% cluster1_patients)]
quantiseq_tcga_cluster2 = quantiseq_tcga_cluster2_ct[,-1]

#CD8 only
quantiseq_tcga_cluster1_CD8 = quantiseq_tcga_cluster1[8,]
quantiseq_tcga_cluster2_CD8 = quantiseq_tcga_cluster2[8,]
quantiseq_tcga_CD8 = cbind(quantiseq_tcga_cluster1_CD8, quantiseq_tcga_cluster2_CD8)

sum(quantiseq_tcga_cluster1_CD8[1, 2:109])/108 #0.2584095
sum(quantiseq_tcga_cluster2_CD8[1,])/423 #0.05836277

#plot both separately
quantiseq_tcga_cluster1_plot_CD8 = quantiseq_tcga_cluster1_CD8 %>%
  gather(Upregulated, fraction, -cell_type) %>%
  ggplot(aes(x=Upregulated, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_manual(values = "Blue") + 
    scale_x_discrete(limits = rev(levels(quantiseq_tcga_cluster1_CD8))) +
    theme(axis.text.y = element_text(size = 4))
quantiseq_tcga_cluster1_plot_CD8


quantiseq_tcga_cluster2_plot_CD8 = quantiseq_tcga_cluster2_CD8 %>%
  gather(Neutral, fraction) %>%
  ggplot(aes(x=Neutral, y=fraction, fill=cell_type)) +
    geom_bar(stat='identity') +
    coord_flip() +
    scale_fill_manual(values = "Blue") + 
    scale_x_discrete(limits = rev(levels(quantiseq_tcga_cluster2_CD8))) +
    theme(axis.text.y = element_text(size = 4)) + 
    ylim(0,0.9)
quantiseq_cluster2_plot_CD8

ggarrange(quantiseq_tcga_cluster1_plot_CD8, quantiseq_cluster2_plot_CD8, ncol = 1, nrow = 2)
```


