---
title: '123'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
NES_OVERALL_PID1 = list()
PID_names = colnames(KIRC_GSEA_activity_PID)
for (j in 1:33) {
  for (i in 1:(ncol(tumorlist_z[[j]]))){
  NES_OVERALL_PID[[j]] = data.frame(row.names = PID_names)
  for (k in 1:ncol(tumorlist_z[[j]])){
    t = GSEA_OVERALL_PID[[j]][[k]][,6]
    NES_OVERALL_PID1[[j]][1:length(metabolic_genesets_PID),k] = t
  }}}
```


```{r data}
#load pathway activity matricesd for MMR and PID for all 33 tumortypes
TCGA_pw_MMR = readRDS("../data/NES_OVERALL_MMR.RDS")
TCGA_pw_PID = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/tumorlist_z.RDS")
names(TCGA_pw_PID) = cancer_abc
```


```{r packages}
library(ggplot2)
library(tidyverse)
library(Seurat)
library(gridExtra)
library(cluster)
library(ggpubr)
library(factoextra)
library(scrime)
set.seed(69)
```

```{r PCA / umap for PID}

cancer_abc = names(TCGA_pw_MMR)
PCA_PID = lapply (1:length(TCGA_pw_PID), function (i) {
  RunPCA(as.matrix(TCGA_pw_PID[[i]]),npcs = (nrow(TCGA_pw_MMR[[i]])-1)
         )
         }) 

UMAP_PID = lapply (1:length(TCGA_pw_PID), function (j) {
  uwot::umap(PCA_PID[[j]]@cell.embeddings)
})

UMAP_output_PID = list ()
for (i in 1: length(TCGA_pw_PID)) {
  UMAP_df_PID = data.frame(UMAP_PID[[i]])
  UMAP_output_PID[[i]] = ggplot (data = UMAP_df_PID,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")+ 
    ggtitle (cancer_abc [[i]])
}
names(UMAP_output_PID) = cancer_abc
plot1234 = list(UMAP_output_PID[[1]],UMAP_output_PID[[2]],UMAP_output_PID[[3]])
ggarrange(plotlist=UMAP_output_PID)
ggarrange(plotlist = plot1234)
UMAP_output_PID$KIRC
```


```{r kmeans for PID}
set.seed(69)
kmeans_PID = vector(mode = "list",33)
for (i in (1:length(UMAP_PID))){
  for (k in (1:5)) {
    x = UMAP_PID[[i]]
    kmeans_PID[[i]][[k]] = kmeans(x, centers = k, nstart = 200)
  }
}
names(kmeans_PID) = cancer_abc


cluster_PID = vector(mode = "list",33)
for(i in (1:length(cluster_PID))){
  for (k in (1:5)){
    y = kmeans_PID[[i]][[k]]
    z = data.frame(UMAP_PID[[i]])
    cluster_PID[[i]][[k]] = fviz_cluster(y, data = z,
             palette = c("orange", "blue","forestgreen","pink","yellow"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
  }
}

names(cluster_PID) = cancer_abc
ggarrange(plotlist = cluster_PID$KIRC)

cluster_PID_k2 = list()
for (i in (1:length(UMAP_PID))){
     cluster_PID_k2[[i]] = cluster_PID[[i]][[2]]
 }
names(cluster_PID_k2) = cancer_abc 
ggarrange(plotlist = cluster_PID_k2)
cluster_PID_k2$KIRC
```


```{r elbow plot for all}
n = data.frame()
for (i in (1:length(UMAP_PID))){
 for (k in (1:5)) {
     n[k,i] = data.frame(kmeans_PID[[i]][[k]]$tot.withinss)
 }
}

tot_PID = list()
for (i in (1:length(UMAP_PID))){
    p  = data.frame(n[,i])
    colnames(p) = "b"
    t = cbind(p,w)
    tot_PID[[i]] = ggplot(data = t, aes(y = b, x = w ))+
      geom_point(size =2, color = "lightblue")+
      geom_line(group = 1, color = "lightblue")+
      labs (y = "tot withins",
        x = "cluster frequenz")+
      ggtitle(cancer_abc[i])
  }

names(tot_PID) = cancer_abc
tot1234 = list(tot_PID[[1]],tot_PID[[7]],tot_PID[[9]],tot_PID[[10]])
ggarrange(plotlist = tot1234)
```



```{r create df for 2 clusters per tumortype}
#extract cluster information 
cluster12_PID = list(list())
for (i in (1:length(UMAP_PID))){
     cluster12_PID[i] = list(kmeans_PID[[i]][[2]][["cluster"]])
 }
names(cluster12_PID) = cancer_abc

#patients in cluster 1
cluster1_PID = list()
for (i in (1:length(UMAP_PID))){
  z = cluster12_PID[[i]]
     cluster1_PID[[i]] = names(z[which(z == 1)])
}
names(cluster1_PID) = cancer_abc
#patients in cluster 2
cluster2_PID = list()
for (i in (1:length(UMAP_PID))){
  z = cluster12_PID[[i]]
     cluster2_PID[[i]] = names(z[which(z == 2)])
}
names(cluster2_PID) = cancer_abc

#filter for PIDs for cluster 1 patients
PID_c1_patients = list()
for (i in (1:length(UMAP_PID))){
  t = cluster1_PID[[i]]
  PID_c1_patients[[i]] = TCGA_pw_PID[[i]][,which(colnames(TCGA_pw_PID[[i]]) %in% t)]
}
names(PID_c1_patients) = cancer_abc

#filter for cluster 2 patients
PID_c2_patients = list()
for (i in (1:length(UMAP_PID))){
  t = cluster2_PID[[i]]
  PID_c2_patients[[i]] = TCGA_pw_PID[[i]][,colnames(TCGA_pw_PID[[i]]) %in% t]
}
names(PID_c2_patients) = cancer_abc
```


```{r calculate mean for each cluster}

PID_c1_mean = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_patients[[i]]
  PID_c1_mean[[i]] = data.frame(apply(r,1,mean))
}
names(PID_c1_mean) = cancer_abc

PID_c2_mean = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c2_patients[[i]]
  PID_c2_mean[[i]] = data.frame(apply(r,1,mean))
  
}
names(PID_c2_mean) = cancer_abc

PID_c1_c2_dif = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_mean[[i]]
  u = PID_c2_mean[[i]]
  PID_c1_c2_dif[[i]] = r - u
  
}
names(PID_c1_c2_dif) = cancer_abc

PID_c1_c2_dif_rank = list()
for (i in (1:length(UMAP_PID))){
  p = PID_c1_c2_dif[[i]]
  PID_c1_c2_dif_rank[[i]] = data.frame(PID_c1_c2_dif[[i]]$apply.PID_c1_patients..i....1..mean.[order(PID_c1_c2_dif[[i]][,1],decreasing = TRUE)])
}
names(PID_c1_c2_dif_rank) = cancer_abc

PID_rownames = c(rownames(PID_c1_c2_dif$ACC))
PID_rownames_rank = list()
for (i in (1:length(UMAP_PID))){
  s = c(PID_c1_c2_dif[[i]][,1])
  PID_rownames_rank[[i]] = c(PID_rownames[order(s,decreasing = TRUE)])
}
names(PID_rownames_rank) = cancer_abc

PID_c1_c2_dif_rank_df = list()
for (i in (1:length(UMAP_PID))){
  h = PID_c1_c2_dif_rank[[i]]
  g = PID_rownames_rank [[i]]
  PID_c1_c2_dif_rank_df[[i]] = as.data.frame(cbind(g,h))
  colnames(PID_c1_c2_dif_rank_df[[i]]) = c("Pathways", "Difference")
}
names(PID_c1_c2_dif_rank_df) = cancer_abc
```

```{r Z scaling}
probek = data.matrix(rowScales(TCGA_pw_PID$KIRC)) 
remove.dots = function(df){colnames(df) = sub(".","-",colnames(df));df}
colnames(probek) = colnames(TCGA_pw_PID$KIRC)
}

PID_c1k = probek[,which(colnames(probek)%in%cluster1_PID$KIRC)]
PID_c2k = probek[,which(colnames(probek)%in%cluster2_PID$KIRC)]

PID_c1k = PID_c1k[-64,]
PID_c2k = PID_c2k[-64,]
View(PID_c1k)
PID_c2k = probek[,which(colnames(probek)%in%cluster2_PID$KIRC)]

probe_kk = data.matrix(sapply(1:87,function(i){
  wilcox.test(PID_c1k[i,],PID_c2k[i,],paired = FALSE)
}$p.value
))
View(probe_kk)

```

```{r significance filtering: wilcoxon}

##filter constant genes 
PID_c1_min = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_patients[[i]]
  PID_c1_min[[i]] = data.frame(apply(r,1,min))
}
names(PID_c1_min) = cancer_abc

PID_c1_max = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_patients[[i]]
  PID_c1_max[[i]] = data.frame(apply(r,1,max))
}
names(PID_c1_max) = cancer_abc

PID_c1_constant = list()
for (i in (1:length(UMAP_PID))){
  r = PID_c1_min[[i]]
  t = PID_c1_max[[i]]
  PID_c1_constant[[i]] = c(names(which(r == t)))
}
names(PID_c1_constant) = cancer_abc

r = PID_c1_min$ACC
  t = PID_c1_max$ACC
  PID_c1_constant = c(colnames(which(r == t)))
aaa = PID_c1_patients$ACC
acute = aaa[!PID_c1_constant,]
PID_c1_constant
dim(aaa)
View(acute)
 names(z[which(z == 1)])


 
PID_wilcox_pv = list()
for (i in (1:length(UMAP_PID))){
  v = as.matrix(PID_c1_patients[[i]])
  b = as.matrix(PID_c2_patients[[i]])
  PID_wilcox_pv[[i]] = data.matrix(sapply(1:nrow(v), function(x){
    wilcox.test(v[x,],b[x,], paired=FALSE)
  }$p.value))
  rownames(PID_wilcox_pv[[i]]) = rownames(PID_c1_patients[[i]])
  colnames(PID_wilcox_pv[[i]]) = "pvalue"
}
names(PID_wilcox_pv) = cancer_abc
View(PID_wilcox_pv$KIRC)

#Bonferroni-Korrektur 
alpha_PID=0.05/(nrow(PID_wilcox_pv[[i]]))

#convert NaN to pvalue 1
for (i in (1:length(UMAP_PID))){
  PID_wilcox_pv[[i]][is.nan(PID_wilcox_pv[[i]])] = 1
}
```

```{r pv cutoff}
PID_wilcox_pv_log = list()
for (i in (1:length(UMAP_PID))){
  a = PID_wilcox_pv[[i]]
  PID_wilcox_pv_log[[i]] = -log10(a)
  colnames(PID_wilcox_pv_log[[i]]) = "neg_log10_pv"
}
names(PID_wilcox_pv_log) = cancer_abc


for (i in (1:length(UMAP_PID))){
  PID_wilcox_pv_log[[i]][PID_wilcox_pv_log[[i]] == Inf] = 0
}

#combine FC and pv matrix
PID_pv_dif = list()
for (i in (1:length(UMAP_PID))){
  a = PID_c1_c2_dif[[i]]
  b = PID_wilcox_pv_log[[i]]
  PID_pv_dif[[i]] = as.data.frame(cbind(a,b))
  colnames(PID_pv_dif[[i]]) = c("Difference","neg_log10_pv")
}
names(PID_pv_dif) = cancer_abc

#extracting sign differently expressed genes (pvalue > cutoff) 
cutoffpv_PID = -log10(alpha_PID)

PID_pv_dif_sig = list()
for (i in (1:length(UMAP_PID))){
  a = PID_pv_dif[[i]]
  PID_pv_dif_sig[[i]] = a[which(a$neg_log10_pv>cutoffpv_PID),]
}
names(PID_pv_dif_sig) = cancer_abc
View(PID_pv_dif_sig$ACC)

#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_pv_dif_sigup = list()
for (i in (1:length(UMAP_PID))){
 t = PID_pv_dif_sig[[i]]
 PID_pv_dif_sigup[[i]] = t[which(abs(t[,1])>0),]
}
names(PID_pv_dif_sigup) = cancer_abc

PID_dif_sig = list()
for (i in (1:length(UMAP_PID))){
t = PID_pv_dif_sig[[i]]$Difference
PID_dif_sig[[i]] = data.frame(t)
}
names(PID_dif_sig) = cancer_abc
View(PID_dif_sig$ACC)

PID_dif_sig_names = list()
for (i in (1:length(UMAP_PID))){
 t = c(rownames(PID_pv_dif_sig[[i]]))
 PID_dif_sig_names [[i]] = t
}
names(PID_dif_sig_names) = cancer_abc


for (i in (1:length(UMAP_PID))){
 r = PID_dif_sig_names[[i]]
 u = PID_dif_sig[[i]]
 PID_dif_sig[[i]] = cbind(r,u)
 colnames(PID_dif_sig[[i]]) = c("Pathway", "Difference")
}
#sry hab hier per hand gefiltert, ging schneller 
PID_dif_sig_0 = list(PID_dif_sig$ACC,PID_dif_sig$CHOL,PID_dif_sig$DLBC,PID_dif_sig$KICH,PID_dif_sig$MESO,PID_dif_sig$READ,PID_dif_sig$TGCT,PID_dif_sig$UVM)
View(PID_dif_sig_0)
cancer_sig = c("ACC","CHOL","DLBC","KICH","MESO","READ","TGCT","UVM")
names(PID_dif_sig_0) = cancer_sig
```

```{r try p adjust function}
## beginning

PID_wilcox_pv_BH = list()
for (i in (1:length(UMAP_PID))){
f = c(PID_wilcox_pv[[i]])
PID_wilcox_pv_BH[[i]] = p.adjust(f, method ="bonferroni", n = length(f))
}
names(PID_wilcox_pv_BH) = cancer_abc

PID_pv_dif1 = list()
for (i in (1:length(UMAP_PID))){
  a = PID_c1_c2_dif[[i]]
  b = PID_wilcox_pv_BH[[i]]
  PID_pv_dif1[[i]] = as.data.frame(cbind(a,b))
  colnames(PID_pv_dif1[[i]]) = c("Difference","neg_log10_pv")
}
names(PID_pv_dif1) = cancer_abc

#extracting sign differently expressed genes (pvalue > cutoff) 

PID_pv_dif_sig1 = list()
for (i in (1:length(UMAP_PID))){
  a = PID_pv_dif1[[i]]
  PID_pv_dif_sig1[[i]] = a[which(a$neg_log10_pv>0.05),]
}
names(PID_pv_dif_sig1) = cancer_abc


#upregulated genes (FC >1) of the sig diff expressed genes (blue in plot)
PID_pv_dif_sigup1 = list()
for (i in (1:length(UMAP_PID))){
 t = PID_pv_dif_sig1[[i]]
 PID_pv_dif_sigup1[[i]] = t[which(abs(t[,1])>0),]
}
names(PID_pv_dif_sigup1) = cancer_abc


for (i in (1:length(UMAP_PID))){
t = PID_pv_dif_sig1[[i]]$Difference
PID_dif_sig1[[i]] = data.frame(t)
}
names(PID_dif_sig1) = cancer_abc


PID_dif_sig_names1 = list()
for (i in (1:length(UMAP_PID))){
 t = c(rownames(PID_pv_dif_sig1[[i]]))
 PID_dif_sig_names1[[i]] = t
}
names(PID_dif_sig_names1) = cancer_abc


for (i in (1:length(UMAP_PID))){
 r = PID_dif_sig_names1[[i]]
 u = PID_dif_sig1[[i]]
 PID_dif_sig1[[i]] = cbind(r,u)
 colnames(PID_dif_sig1[[i]]) = c("Pathway", "Difference")
}

View(PID_dif_sig1)


## end 
```




```{r plot significant pathways}
PID_dif_plot = list()
for (i in (1:length(PID_dif_sig_0))){
  g = PID_dif_sig_0[[i]]
  PID_dif_plot[[i]] = ggplot(g, aes(x=reorder(Pathway,Difference), y=Difference)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PID pw with signif different NES in 2 clusters")+
  theme(plot.title = element_text(size=10))
}
names(PID_dif_plot) = cancer_sig
ggarrange(plotlist=PID_dif_plot)

plotlist1234 = list(PID_dif_plot$ACC,PID_dif_plot$CHOL,PID_dif_plot$DLBC,PID_dif_plot$KICH)
ggarrange(plotlist = plotlist1234)
  
l = PID_dif_sig$ACC
ggplot(l, aes(x=reorder(Pathway,Difference), y=Difference)) +
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("PID pw with signif different NES in 2 KIRC clusters")+
  theme(plot.title = element_text(size=10))

```


```

