---
title: "Descriptive_Analysis_Anna"
author: "Anna von Bachmann"
date: '2022-05-12'
output: html_document
---

```{r setup, include=FALSE}
library(reshape2)
library(ggplot2)
library(ggdendro)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
tcga_exp_protein_coding = readRDS("~/Desktop/GitHub/2022-topic-02-team-02/data/tcga_exp_cleaned.RDS")
tcga_annot = readRDS("../data/tcga_tumor_annotation.RDS")
tcga_exp_colnames_new = c(substr(colnames(tcga_exp_protein_coding),1, nchar(colnames(tcga_exp_protein_coding))-3))
colnames(tcga_exp_protein_coding) = tcga_exp_colnames_new
```

```{r}
#dividig tcga_annot according to cancer types, saving each in a new data frame
tcga_annot_ACC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="ACC"),]
tcga_annot_BLCA = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="BLCA"),]
tcga_annot_BRCA = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="BRCA"),]
tcga_annot_CESC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="CESC"),]
tcga_annot_CHOL = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="CHOL"),]
tcga_annot_COAD = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="COAD"),]
tcga_annot_DLBC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="DLBC"),]
tcga_annot_ESCA = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="ESCA"),]
tcga_annot_GBM = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="GBM"),]
tcga_annot_HNSC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="HNSC"),]
tcga_annot_KICH = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="KICH"),]
tcga_annot_KIRC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="KIRC"),]
tcga_annot_KIRP = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="KIRP"),]
tcga_annot_LAML = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="LAML"),]
tcga_annot_LGG = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="LGG"),]
tcga_annot_LIHC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="LIHC"),]
tcga_annot_LUAD = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="LUAD"),]
tcga_annot_LUSC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="LUSC"),]
tcga_annot_MESO = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="MESO"),]
tcga_annot_OV = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="OV"),]
tcga_annot_PAAD = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="PAAD"),]
tcga_annot_PCPG= tcga_annot[which(tcga_annot$cancer_type_abbreviation=="PCPG"),]
tcga_annot_PRAD = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="PRAD"),]
tcga_annot_READ = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="READ"),]
tcga_annot_SARC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="SARC"),]
tcga_annot_SKCM = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="SKCM"),]
tcga_annot_STAD = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="STAD"),]
tcga_annot_TGCT = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="TGCT"),]
tcga_annot_THCA = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="THCA"),]
tcga_annot_THYM = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="THYM"),]
tcga_annot_UCEC = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="UCEC"),]
tcga_annot_UCS = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="UCS"),]
tcga_annot_UVM = tcga_annot[which(tcga_annot$cancer_type_abbreviation=="UVM"),]
```



```{r}
#create new dataframe for each cancer type containing gene expression values specificly for this cancer type
tcga_exp_clean_ACC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_ACC$PATIENT]

tcga_exp_c_BLCA =  tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_BLCA$PATIENT]
  
tcga_exp_c_BRCA  = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_BRCA$PATIENT]

tcga_exp_c_CESC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_CESC$PATIENT]

tcga_exp_c_CHOL = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_CHOL$PATIENT]

tcga_exp_c_COAD  = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_COAD$PATIENT]

tcga_exp_c_DLBC = tcga_exp_protein_coding[,names(tcga_exp_protein_coding) %in% tcga_annot_DLBC$PATIENT]

tcga_exp_c_ESCA = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_ESCA$PATIENT]

tcga_exp_c_GBM = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_GBM$PATIENT]

tcga_exp_c_HNSC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_HNSC$PATIENT]

tcga_exp_c_KICH = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_KICH$PATIENT]

tcga_exp_c_KIRC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_KIRC$PATIENT]

tcga_exp_c_KIRP = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_KIRP$PATIENT]

tcga_exp_c_LAML = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_LAML$PATIENT]

tcga_exp_c_LGG = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_LGG$PATIENT]

tcga_exp_c_LIHC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_LIHC$PATIENT]

tcga_exp_c_LUAD = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_LUAD$PATIENT]

tcga_exp_c_LUSC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_LUSC$PATIENT]

tcga_exp_c_MESO = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_MESO$PATIENT]

tcga_exp_c_OV = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_OV$PATIENT]

tcga_exp_c_PAAD = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_PAAD$PATIENT]

tcga_exp_c_PCPG = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_PCPG$PATIENT]

tcga_exp_c_PRAD = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_PRAD$PATIENT]

tcga_exp_c_READ = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_READ$PATIENT]

tcga_exp_c_SARC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_SARC$PATIENT]

tcga_exp_c_SKCM = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_SKCM$PATIENT]

tcga_exp_c_STAD = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_STAD$PATIENT]

tcga_exp_c_TGCT = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_TGCT$PATIENT]

tcga_exp_c_THCA = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_THCA$PATIENT]

tcga_exp_c_THYM = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_THYM$PATIENT]

tcga_exp_c_UCEC = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_UCEC$PATIENT]

tcga_exp_c_UCS = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_UCS$PATIENT]

tcga_exp_c_UVM = tcga_exp_protein_coding[, names(tcga_exp_protein_coding) %in% tcga_annot_ACC$PATIENT]

```


```{r}
tcga_exp_dataframes_complete = list(tcga_exp_clean_ACC,tcga_exp_c_BLCA,tcga_exp_c_BRCA,tcga_exp_c_CESC,tcga_exp_c_CHOL,tcga_exp_c_COAD,tcga_exp_c_DLBC,tcga_exp_c_ESCA,tcga_exp_c_GBM,tcga_exp_c_HNSC,tcga_exp_c_KICH,tcga_exp_c_KIRC,tcga_exp_c_KIRP,tcga_exp_c_LAML,tcga_exp_c_LGG,tcga_exp_c_LIHC,tcga_exp_c_LUAD,tcga_exp_c_LUSC,tcga_exp_c_MESO,tcga_exp_c_OV,tcga_exp_c_PAAD,tcga_exp_c_PCPG,tcga_exp_c_PRAD,tcga_exp_c_READ,tcga_exp_c_SARC,tcga_exp_c_SKCM,tcga_exp_c_STAD,tcga_exp_c_TGCT,tcga_exp_c_THCA,tcga_exp_c_THYM,tcga_exp_c_UCEC,tcga_exp_c_UCS,tcga_exp_c_UVM)

ACC_mean = apply(tcga_exp_clean_ACC,1, mean)
BLCA_mean = apply(tcga_exp_c_BLCA,1, mean)
BRCA_mean = apply(tcga_exp_c_BRCA,1, mean)
CESC_mean = apply(tcga_exp_c_CESC,1, mean)
CHOL_mean = apply(tcga_exp_c_CHOL,1, mean)
COAD_mean = apply(tcga_exp_c_COAD,1, mean)
DLBC_mean = apply(tcga_exp_c_DLBC,1, mean)
ESCA_mean = apply(tcga_exp_c_ESCA,1, mean)
GBM_mean = apply(tcga_exp_c_GBM,1, mean)
HNSC_mean = apply(tcga_exp_c_HNSC,1, mean)
KICH_mean = apply(tcga_exp_c_KICH,1, mean)
KIRC_mean = apply(tcga_exp_c_KIRC,1, mean)
KIRP_mean = apply(tcga_exp_c_KIRP,1, mean)
LAML_mean = apply(tcga_exp_c_LAML,1, mean)
LGG_mean = apply(tcga_exp_c_LGG,1, mean)
LIHC_mean = apply(tcga_exp_c_LIHC,1, mean)
LUAD_mean = apply(tcga_exp_c_LUAD,1, mean)
LUSC_mean = apply(tcga_exp_c_LUSC,1, mean)
MESO_mean = apply(tcga_exp_c_MESO,1, mean)
OV_mean = apply(tcga_exp_c_OV,1, mean)
PAAD_mean = apply(tcga_exp_c_PAAD,1, mean)
PCPG_mean = apply(tcga_exp_c_PCPG,1, mean)
PRAD_mean = apply(tcga_exp_c_PRAD,1, mean)
READ_mean = apply(tcga_exp_c_READ,1, mean)
SARC_mean = apply(tcga_exp_c_SARC,1, mean)
SKCM_mean = apply(tcga_exp_c_SKCM,1, mean)
STAD_mean = apply(tcga_exp_c_STAD,1, mean)
TGCT_mean = apply(tcga_exp_c_TGCT,1, mean)
THCA_mean = apply(tcga_exp_c_THCA,1, mean)
THYM_mean = apply(tcga_exp_c_THYM,1, mean)
UCEC_mean = apply(tcga_exp_c_UCEC,1, mean)
UCS_mean = apply(tcga_exp_c_UCS,1, mean)
UVM_mean = apply(tcga_exp_c_UVM,1, mean)
View(UVM_mean)
```

```{r}
mean_all =as.data.frame(cbind(ACC_mean,BLCA_mean,BRCA_mean,CESC_mean,CHOL_mean,COAD_mean,DLBC_mean,ESCA_mean,GBM_mean,HNSC_mean,KICH_mean,KIRC_mean,KIRP_mean,LAML_mean,LGG_mean,LIHC_mean,LUAD_mean,LUSC_mean,MESO_mean,OV_mean,PAAD_mean,PCPG_mean,PRAD_mean,READ_mean,SARC_mean,SKCM_mean,STAD_mean,TGCT_mean,THCA_mean,THYM_mean,UCEC_mean,UCS_mean,UVM_mean))

#View(mean_all)

tumornames = data.frame("ACC","BLCA","BRCA","CESC","CHOL","COAD","DLBC","ESCA","GBM","HNSC","KICH","KIRC","KIRP","LAML","LGG","LIHC","LUAD","LUSC","MESO","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THCA","THYM","UCEC","UCS","UVM")

colnames(mean_all) = tumornames


boxplot_mean =
ggplot(data = melt(mean_all), aes(x = reorder(variable, -value, FUN = median), y =value, fill = variable))+
  geom_boxplot()+
  stat_summary(fun = mean, geom="point", colour = "blue", size=0.7)+
  ggtitle("mean expression of all tumortypes")+
  ylab ("mean expression values")+
  xlab("tumor types")+
  theme(plot.title = element_text(size = 12))+
  theme(axis.title.x = element_text(size = 12))+
  theme(axis.title.y = element_text(size = 12))
  

  boxplot_mean + coord_flip()
  
                
#fill = variable instead of colour
  
#ACC,BLCA,BRCA,CESC,CHOL,COAD,DLBC,ESCA,GBM,HNSC,KICH,KIRC,KIRP,LAML,LGG,LIHC,LUAD,LUSC,MESO,OV,PAAD,PCPG,PRAD,READ,SARC,SKCM,STAD,TGCT,THCA,THYM,UCEC,UCS,UVM
```
```{r}
d = (dist(t(mean_all)))
ggdendrogram(hclust(d, method = "ward.D2"))
h


f = as.matrix(mean_all)
n = RunPCA(f, npcs = 32)
u =data.frame(uwot::umap(n@cell.embeddings))
ggplot (data = u,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 0.5 , color = "blue")
z = kmeans(u, centers   = 5)
h = fviz_cluster()
```

