---
title: "PCA_pan_cancer"
author: "Linda Blaier"
date: '2022-05-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load data = run Biotypes.Rmd 
```

```{r}
# work with tcga_exp_prc_clean -> w/o low variable under p50
#dim (tcga_exp_prc_clean)
#tcga_exp_pca = prcomp (t(tcga_exp_prc_clean), center = F, scale. = F)
#pca_var = tcga_exp_pca$sdev^2
#proportion_pca_var = pca_var/sum(pca_var)
#names_prop_pca_var = 1:length(proportion_pca_var)
#barplot(proportion_pca_var[1:20])
#tcga_exp_pca$sdev
```

```{r}
#attempt to save data from environment
#saveRDS(tcga_exp_prc_clean, file = "exp_prc_clean.Rds")
#tcga_exp_prc_clean_copy = readRDS(file = "exp_prc_clean.Rds")
```

```{r}
# tcga_exp_pca2 = PCA(tcga_exp_prc_clean)

```

```{r}
library(Seurat)
library(ggplot2)
library(tidyverse)
```

```{r}
#Run PCA 
PCA_exp = RunPCA(as.matrix(tcga_exp_prc_clean))
#create data frame with PCs and respective genes
PCA_exp_PCs = PCA_exp@cell.embeddings
#visualize PCs with respect to explained variance
PCA_exp_var = PCA_exp@stdev^2
PCA_exp_proportion_var = PCA_exp_var/sum(PCA_exp_var)
PC_exp = (PCA_exp_PCs[1:20])
PCs_20 = PCA_exp@cell.embeddings[1:20]

#plot PCA, PC1 vs PC2 KIRC = black --> outlier
pca_kirc = data.frame(PCA_exp[cancer_types == "KIRC",])
PCA_exp_scatter2 = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y = PC_2, color = cancer_types)) +
  geom_point(point = 0.5)+ 
  geom_point(data= pca_kirc , aes(x = PC_1, y = PC_2), color = "black")
print(PCA_exp_scatter2) 

#plot PCA, PC1 vs PC2, KIRC = black --> outlier
PCA_exp_scatter3 = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y = PC_3, color = cancer_types )) +
  geom_point(point = 0.5) + 
  geom_point(data= pca_kirc , aes(x = PC_1, y = PC_3), color = "black")
print(PCA_exp_scatter3) 

# plot scatter plot regarding gender -> no clustering detectable
exp_gender = ifelse(tcga_annot$gender
                        == "FEMALE", "orange", "blue")
PCA_exp_gender = ggplot (data = as.data.frame(PCA_exp_PCs), aes(x = PC_1, y= PC_2)) + 
  geom_point(size = 0.5, color = exp_gender) + 
  ggtitle ("PCA regarding gender")
PCA_exp_gender
```

```{r}
#run UMAP

library(tidyverse)

cancer_types = tcga_annot$cancer_type_abbreviation
data_kirc = which(cancer_types == "KIRC")

#calculate UMAP on PCA 
dim(UMAP_exp)
UMAP_exp= uwot::umap(PCA_exp@cell.embeddings)
UMAP_exp_KIRC = data.frame(UMAP_exp[cancer_types == "KIRC",])
UMAP_plot = ggplot (data = as.data.frame(UMAP_exp), 
                    aes(x = V1, y= V2, color = cancer_types))+
  geom_point(size = 2) +
  geom_point(data= UMAP_exp_KIRC , aes(x = X1, y = X2), color = "black")
UMAP_plot

#kirc in different color
UMAP_plot_1 = ggplot (data = as.data.frame(UMAP_exp), 
                    aes(x = V1, y= V2, color = cancer_types=="KIRC"))+
  geom_point(size = 2) 
UMAP_plot_1

#plot umap for each cancer type (umap of all cancer types split into 33 plots per cancer type)
cancer_names = unique(cancer_types)
UMAP_output = list ()
for (i in 1:length(cancer_names)) {
  cancer = c(which(cancer_types == cancer_names[i]))
  cancer_df = data.frame(UMAP_exp[cancer,])
  UMAP_output[[i]] = ggplot (data = cancer_df,
  aes (x = X1, y =X2, color = "blue")) + 
    geom_point(size = 2 , color = "blue")+ 
    ggtitle (cancer_names [[i]])
}

UMAP_output[[1]]
cancer = c(which(cancer_types == cancer_names[1]))
names(UMAP_output) = cancer_names

#use UMAP_output$"cancer name" to acces individual Umap plots

UMAP_output$KIRC

#plot Umaps for all 33 cancer types
sapply(1:33, function(i){
  plot(UMAP_output[[i]])
  })

```


```{r}#

#find optimal clusternumber
library(ggpubr)
library(factoextra)

kmeans(UMAP_exp, centers= 20, nstart = 50)##
# for 4 centers
km.4 = kmeans(UMAP_exp, centers= 20, nstart = 50)

fviz_cluster(km.4, data.frame(UMAP_exp),
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
UMAP_plot

#extract tot.withinss --> for silhouette plot (elbow method)
tcga_UMAP_kmeans_tw = sapply(1:20, function(k){
  kmeans(x = UMAP_exp , centers = k, nstart = 50 )$tot.withinss})

#elbow plot
plot(tcga_UMAP_kmeans_tw, type = "b", pch= 20, xlab = "centers", ylab = "Total within-clusters sum of squares")
umap_elbow


fviz_nbclust(UMAP_exp, kmeans, method='silhouette')

#extract cluster values for silhouette plot
tcga_UMAP_kmeans_c = sapply(2:20, function(k){
  kmeans(x = UMAP_exp , centers = k, nstart = 50 )$cluster})

library(cluster)


#silhouette plot
sapply(1:19, function(x){
  plot(silhouette(tcga_UMAP_kmeans_c[,x], dist(UMAP_exp)), main ="Silhouette plot")})
```
```{r}
tumorlist = readRDS("../data/tumorlist_z.RDS")

#calculate PCA for each tumor type 
tumorlist_ACC_BLCA = tumorlist[c(1,2)]
PCA_tumorlist1 = lapply (1:33, function (i) {
  RunPCA(as.matrix(tumorlist[[i]], npcs = 50 ))
})
#Error in irlba(A = t(x = object), nv = npcs, ...) : 
#max(nu, nv) must be strictly less than min(nrow(A), ncol(A))
6.
stop("max(nu, nv) must be strictly less than min(nrow(A), ncol(A))")
5.
irlba(A = t(x = object), nv = npcs, ...)
4.
RunPCA.default(as.matrix(tumorlist[[i]]))
3.
RunPCA(as.matrix(tumorlist[[i]]))
2.
FUN(X[[i]], ...)
1.
lapply(1:9, function(i) {
RunPCA(as.matrix(tumorlist[[i]]))
})

 cancer_abc = sort(cancer_names)
names(PCA_tumorlist) = cancer_abc

UMAP_tumorlist = lapply (1:length(tumorlist), function (j) {
  uwot::umap(PCA_tumorlist1@cell.embeddings)
})
```
```{r}
tumorlist = readRDS("../data/tumorlist_z.RDS")

#calculate PCA for each tumor type --> tried with the first two tumor types
tumorlist_ACC_BLCA = tumorlist[c(1,2)]
PCA_tumorlist_ACC_BLCA = lapply (1:2, function (i) {
  RunPCA(as.matrix(tumorlist_ACC_BLCA[[i]]))
})

 cancer_abc = sort(cancer_names)
names(PCA_tumorlist_ACC_BLCA) = cancer_abc[1:2]
```

```{r}
UMAP_tumorlist1 = lapply (1:length(PCA_tumorlist_ACC_BLCA), function (j) {
  uwot::umap(PCA_tumorlist_ACC_BLCA[[j]]@cell.embeddings)
})

is.na(PCA_tumorlist_ACC_BLCA[[1]])
```
```{r}
#funktioniert alles nicht --> von Hand machen ...
tumor_ACC = tumorlist [[1]]
PCA_1 = RunPCA (as.matrix(tumor_ACC))
UMAP_1 = uwot:: umap(PCA_1@cell.embeddings)

ACC = which(tcga_exp_cleaned == "ACC")
PCA_ACC = RunPCA (as.matrix(ACC))
```

